import { randomUUID } from 'node:crypto';
import { ConflictError, NotFoundError, ValidationError } from '../core/errors.js';

const MODES = new Set(['OWNER', 'SHARED_STORAGE', 'HELPER_KEEP']);
const TERMINAL = new Set(['COMPLETED', 'FAILED', 'CANCELLED']);

export function createHelpService({ repository, bots, fleetTransfer, logistics, events }) {
  if (!repository || !bots || !fleetTransfer || !logistics) throw new ValidationError('Help service requires repository, bots, fleet transfer, and logistics');
  const create = async input => {
    const ownerBotId = botId(input.ownerBotId, 'ownerBotId'); const owner = bots.get(ownerBotId); const goal = normalizeGoal(input.goal); const outputPolicy = normalizePolicy(input.outputPolicy, ownerBotId, input.fleetWide === true); const workers = normalizeWorkers(input.workers, ownerBotId, goal.target).map(worker => ({ ...worker, inventoryBaseline: inventoryCount(bots.get(worker.botId), goal.item) }));
    const initial = Number.isInteger(input.initialProgress) ? input.initialProgress : inventoryCount(owner, goal.item); if (initial < 0 || initial > goal.target) throw new ValidationError('initialProgress must be between 0 and goal target'); const now = new Date().toISOString(); const session = { id: randomUUID(), parentTaskId: String(input.parentTaskId ?? randomUUID()), ownerBotId, status: 'ACTIVE', outputPolicy, goal, progress: progress(goal.target, initial, 0), workers, outputs: [], createdAt: now, updatedAt: now, version: 1 };
    const created = await repository.create(session); await publish(events, 'help.session.created', created); return created;
  };
  const get = id => repository.find(id);
  const list = () => repository.list();
  const recordCollected = async input => mutate(repository, input.sessionId, async session => {
    const worker = findWorker(session, input.botId); const count = positive(input.count, 'Collected count'); if (String(input.item).toLowerCase() !== session.goal.item) throw new ValidationError(`Help output item must be '${session.goal.item}'`); if (worker.collected + count > worker.assigned) throw new ConflictError(`Worker '${worker.botId}' collected more than assigned`, { assigned: worker.assigned, collected: worker.collected, attempted: count });
    const verifiedAvailable = inventoryCount(bots.get(worker.botId), session.goal.item) - worker.inventoryBaseline - worker.collected; if (count > verifiedAvailable) throw new ConflictError(`Worker '${worker.botId}' has only ${Math.max(0, verifiedAvailable)} newly verified '${session.goal.item}'`, { requested: count, verifiedAvailable: Math.max(0, verifiedAvailable) }); worker.collected += count; worker.status = 'OUTPUT_READY'; session.outputs.push({ id: randomUUID(), workerBotId: worker.botId, item: session.goal.item, produced: count, location: { type: 'BOT', id: worker.botId }, destination: destination(session.outputPolicy), delivered: 0, credited: 0, status: 'OUTPUT_READY', createdAt: new Date().toISOString() }); await publish(events, 'help.output.ready', { sessionId: session.id, worker: worker.botId, item: session.goal.item, count }); return session;
  });
  const handoff = async input => {
    const session = await get(input.sessionId); const worker = findWorker(session, input.botId); const amount = worker.collected - worker.delivered; if (amount < 1) throw new ConflictError(`Worker '${worker.botId}' has no undelivered output`); const donor = bots.get(worker.botId); await publish(events, 'help.handoff.planned', { sessionId: session.id, workerBotId: worker.botId, item: session.goal.item, count: amount, policy: session.outputPolicy });
    try {
      let delivery;
      if (session.outputPolicy.mode === 'OWNER') { const owner = bots.get(session.outputPolicy.targetBotId); delivery = donor.id === owner.id ? verifyOwnerPossession(owner, session.goal.item, amount) : await fleetTransfer.transfer({ donor, receiver: owner, item: session.goal.item, count: amount, signal: input.signal }); }
      else if (session.outputPolicy.mode === 'SHARED_STORAGE') delivery = await logistics.store({ runtime: donor, storageName: session.outputPolicy.storageName, item: session.goal.item, count: amount });
      else delivery = verifyOwnerPossession(donor, session.goal.item, amount);
      return await mutate(repository, session.id, async current => { const currentWorker = findWorker(current, worker.botId); const delivered = amount; const credit = Math.min(delivered, current.progress.remaining); currentWorker.delivered += delivered; currentWorker.credited += credit; currentWorker.status = currentWorker.credited >= currentWorker.assigned ? 'COMPLETED' : credit ? 'PARTIAL' : 'OUTPUT_READY'; current.progress = progress(current.goal.target, current.progress.initial, current.progress.credited + credit); const output = current.outputs.find(entry => entry.workerBotId === currentWorker.botId && entry.status === 'OUTPUT_READY'); if (output) { output.location = destination(current.outputPolicy); output.delivered += delivered; output.credited += credit; output.status = credit === delivered ? 'COMPLETED' : 'SURPLUS'; }
        if (delivered > credit) await publish(events, 'help.surplus.detected', { sessionId: current.id, workerBotId: currentWorker.botId, item: current.goal.item, surplus: delivered - credit }); if (current.progress.remaining === 0) current.status = 'COMPLETED'; await publish(events, 'help.handoff.completed', { sessionId: current.id, workerBotId: currentWorker.botId, delivery, delivered, credited: credit }); await publish(events, 'help.output.credited', { sessionId: current.id, workerBotId: currentWorker.botId, credited: credit, progress: current.progress }); return current;
      });
    } catch (error) { await mutate(repository, session.id, async current => { const currentWorker = findWorker(current, worker.botId); currentWorker.status = error.code === 'INVENTORY_FULL' ? 'WAITING_DESTINATION' : 'WAITING_TRANSFER'; current.status = currentWorker.status === 'WAITING_DESTINATION' ? 'WAITING_DESTINATION' : 'ACTIVE'; await publish(events, currentWorker.status === 'WAITING_DESTINATION' ? 'help.destination.full' : 'help.handoff.failed', { sessionId: current.id, workerBotId: worker.botId, code: error.code ?? 'TRANSFER_FAILED', error: error.message }); return current; }); throw error; }
  };
  const handleBotDeath = async botIdValue => { const affected = []; for (const session of await list()) { if (TERMINAL.has(session.status)) continue; const worker = session.workers.find(entry => entry.botId === botIdValue && entry.delivered < entry.collected); if (!worker) continue; affected.push(await mutate(repository, session.id, async current => { const share = findWorker(current, botIdValue); share.status = 'HELPER_LOST'; current.status = 'RECOVERY_REQUIRED'; await publish(events, 'help.output.partial', { sessionId: current.id, workerBotId: botIdValue, collected: share.collected, delivered: share.delivered, credited: share.credited }); return current; })); } return affected; };
  const reconcileRecovery = async input => mutate(repository, input.sessionId, async session => { const worker = findWorker(session, input.botId); const recovered = itemCount(input.recoveredItems, session.goal.item); const outstanding = worker.collected - worker.delivered; worker.collected = worker.delivered + Math.min(outstanding, recovered); worker.lost = Math.max(0, outstanding - recovered); worker.status = recovered ? 'OUTPUT_READY' : 'WAITING_RESOURCE'; session.status = 'ACTIVE'; await publish(events, 'help.output.partial', { sessionId: session.id, workerBotId: worker.botId, recovered, lost: worker.lost, credited: worker.credited }); return session; });
  const status = async () => { const sessions = await list(); return { status: 'HEALTHY', sessions: sessions.length, active: sessions.filter(session => !TERMINAL.has(session.status)).length, completed: sessions.filter(session => session.status === 'COMPLETED').length }; };
  return Object.freeze({ create, get, list, recordCollected, handoff, handleBotDeath, reconcileRecovery, status });
}

async function mutate(repository, id, operation) { const current = await repository.find(id); const next = structuredClone(current); const result = await operation(next); result.updatedAt = new Date().toISOString(); result.version = (current.version ?? 0) + 1; return repository.update(id, result); }
function normalizeGoal(value) { if (!value || typeof value !== 'object') throw new ValidationError('Help session requires goal'); const item = String(value.item ?? '').trim().toLowerCase(); const target = positive(value.target, 'Goal target'); if (!/^[a-z0-9_.:-]{1,128}$/.test(item)) throw new ValidationError('Help goal item must be a valid registry name'); return { type: String(value.type ?? 'collect').toLowerCase(), item, target }; }
function normalizePolicy(value, ownerBotId, fleetWide) { const mode = String(value?.mode ?? 'OWNER').toUpperCase(); if (!MODES.has(mode)) throw new ValidationError('Help output policy mode must be OWNER, SHARED_STORAGE, or HELPER_KEEP'); if (mode === 'HELPER_KEEP' && !fleetWide) throw new ValidationError('HELPER_KEEP requires fleetWide ownership'); const targetBotId = mode === 'OWNER' ? botId(value?.targetBotId ?? ownerBotId, 'outputPolicy.targetBotId') : null; const storageName = mode === 'SHARED_STORAGE' ? String(value?.storageName ?? '').trim() : null; if (mode === 'SHARED_STORAGE' && !storageName) throw new ValidationError('SHARED_STORAGE requires outputPolicy.storageName'); return { mode, targetBotId, storageName, allowFallbackStorage: value?.allowFallbackStorage === true, creditOn: mode === 'OWNER' ? 'VERIFIED_DELIVERY' : mode === 'SHARED_STORAGE' ? 'VERIFIED_STORAGE' : 'FLEET_POSSESSION', fleetWide }; }
function normalizeWorkers(value, ownerBotId, target) { const entries = Array.isArray(value) && value.length ? value : [{ botId: ownerBotId, assigned: target }]; let total = 0; const ids = new Set(); return entries.map(entry => { const botIdValue = botId(entry.botId, 'worker.botId'); if (ids.has(botIdValue)) throw new ValidationError(`Duplicate help worker '${botIdValue}'`); ids.add(botIdValue); const assigned = positive(entry.assigned, 'Worker assigned'); total += assigned; if (total > target) throw new ValidationError('Total worker assignments cannot exceed goal target'); return { botId: botIdValue, assigned, collected: 0, delivered: 0, credited: 0, lost: 0, status: 'ASSIGNED' }; }); }
function findWorker(session, id) { const worker = session.workers.find(entry => entry.botId === botId(id, 'worker botId')); if (!worker) throw new NotFoundError('Help worker', id); return worker; }
function progress(target, initial, credited) { const current = Math.min(target, initial + credited); return { initial, credited, current, remaining: target - current }; }
function destination(policy) { return policy.mode === 'OWNER' ? { type: 'BOT', id: policy.targetBotId } : policy.mode === 'SHARED_STORAGE' ? { type: 'STORAGE', id: policy.storageName } : { type: 'BOT', id: null }; }
function verifyOwnerPossession(runtime, item, amount) { const count = inventoryCount(runtime, item); if (count < amount) throw new ConflictError(`Destination bot '${runtime.id}' does not possess ${amount} '${item}'`, { item, expected: amount, actual: count }); return { item, requested: amount, transferred: amount, verified: true, retainedBy: runtime.id }; }
function inventoryCount(runtime, item) { return (runtime.adapter.snapshot().inventorySummary ?? []).filter(entry => String(entry?.name).toLowerCase() === item).reduce((sum, entry) => sum + Number(entry.count ?? 0), 0); }
function itemCount(items, item) { return (Array.isArray(items) ? items : []).filter(entry => String(entry?.name).toLowerCase() === item).reduce((sum, entry) => sum + Number(entry.count ?? 0), 0); }
function botId(value, label) { const id = String(value ?? '').trim(); if (!/^[A-Za-z0-9_.:-]{1,128}$/.test(id)) throw new ValidationError(`${label} must be a valid bot id`); return id; }
function positive(value, label) { const count = Number(value); if (!Number.isInteger(count) || count < 1 || count > 10_000) throw new ValidationError(`${label} must be an integer between 1 and 10000`); return count; }
async function publish(events, type, payload) { await events?.publish(type, payload, { source: 'help' }); }
