import { randomUUID } from 'node:crypto';
import { ConflictError, NotFoundError, ValidationError } from '../core/errors.js';
import { Task, TaskStatus } from '../tasks/task.js';
import { analyzeHelpTask } from './task-analyzer.js';
import { validateHelper } from './helper-validator.js';
import { splitWork } from './work-splitter.js';

const MODES = new Set(['OWNER', 'SHARED_STORAGE', 'HELPER_KEEP']);
const TERMINAL = new Set(['COMPLETED', 'FAILED', 'CANCELLED']);

export function createHelpService({ repository, workShareRepository, contributionRepository, bots, fleetTransfer, logistics, goals, executor, events, maxHelpersPerSession, minimumChunk }) {
  if (!repository || !workShareRepository || !contributionRepository || !bots || !fleetTransfer || !logistics || !goals || !executor) throw new ValidationError('Help service requires session, work share, contribution, bot, logistics, goal, and executor services');
  const limits = normalizeLimits(maxHelpersPerSession, minimumChunk);
  const tails = new Map();
  const create = async input => {
    const parentTaskId = requiredId(input.parentTaskId, 'parentTaskId'); const parent = goals.task(parentTaskId); const analysis = analyzeHelpTask(parent); const ownerBotId = botId(input.ownerBotId ?? parent.assignedBot, 'ownerBotId'); const outputPolicy = normalizePolicy(input.outputPolicy, ownerBotId, input.fleetWide === true); const initial = await resolveProgress({ outputPolicy, ownerBotId, bots, logistics, item: analysis.item });
    if (initial > analysis.target) throw new ValidationError(`Progress source already has more '${analysis.item}' than parent target`);
    const active = (await repository.list()).find(session => session.parentTaskId === parentTaskId && !TERMINAL.has(session.status)); if (active) throw new ConflictError(`Parent task '${parentTaskId}' already has an active help session`);
    const remaining = analysis.target - initial; if (!remaining) throw new ConflictError(`Parent task '${parentTaskId}' has no remaining work`);
    const workerIds = normalizeWorkerIds(input.workers, ownerBotId); validateHelperLimit(workerIds, ownerBotId, limits.maxHelpersPerSession); const workerPreview = workerIds.includes(ownerBotId) ? [{ botId: ownerBotId, role: 'OWNER', status: 'ASSIGNED' }] : []; for (const helperBotId of workerIds.filter(id => id !== ownerBotId)) { validateHelper({ bots, goals, helperBotId, ownerBotId, activeShares: workerPreview, maxHelpers: limits.maxHelpersPerSession, minimumChunk: limits.minimumChunk, remaining }); workerPreview.push({ botId: helperBotId, role: 'HELPER', status: 'ASSIGNED' }); } const requested = validateRequestedAssignments(input.workers, remaining); const assignments = requested.length ? requested : splitWork(remaining, workerIds); const total = assignments.reduce((sum, share) => sum + share.assigned, 0);
    if (total > remaining) throw new ValidationError(`Total worker assignments ${total} exceed remaining work ${remaining}`);
    const now = new Date().toISOString(); const id = randomUUID(); const session = { id, parentTaskId, parentGoalId: parent.goalId, ownerBotId, generation: 1, status: 'ACTIVE', analysis, outputPolicy, goal: { item: analysis.item, target: analysis.target }, progress: progress(analysis.target, initial, 0, initial), createdAt: now, updatedAt: now, version: 1 };
    const created = await repository.create(session); for (const assignment of assignments) await workShareRepository.create(createShare({ sessionId: id, parentTaskId, botId: assignment.botId, assigned: assignment.assigned, role: assignment.botId === ownerBotId ? 'OWNER' : 'HELPER', generation: 1 }));
    await publish(events, 'help.requested', { sessionId: id, parentTaskId }); await publish(events, 'help.analysis.completed', { sessionId: id, analysis }); return view(created, await sharesFor(workShareRepository, id));
  };
  const previewCreate = async input => {
    const parentTaskId = requiredId(input.parentTaskId, 'parentTaskId'); const parent = goals.task(parentTaskId); const analysis = analyzeHelpTask(parent); const ownerBotId = botId(input.ownerBotId ?? parent.assignedBot, 'ownerBotId'); const outputPolicy = normalizePolicy(input.outputPolicy, ownerBotId, input.fleetWide === true); const initial = await resolveProgress({ outputPolicy, ownerBotId, bots, logistics, item: analysis.item }); const remaining = Math.max(0, analysis.target - initial);
    return { parentTaskId, ownerBotId, outputPolicy, analysis, progress: progress(analysis.target, initial, 0, initial), remaining };
  };
  const get = async id => view(await repository.find(id), await sharesFor(workShareRepository, id));
  const list = async () => Promise.all((await repository.list()).map(session => get(session.id)));
  const remaining = async sessionId => authoritativeRemaining(await repository.find(sessionId), bots, logistics);
  const activeForOwner = async ownerBotId => { const session = (await repository.list()).find(entry => entry.ownerBotId === ownerBotId && !TERMINAL.has(entry.status)); return session ? get(session.id) : null; };
  const join = async input => locked(tails, input.sessionId, async () => {
    const session = await repository.find(input.sessionId); ensureActive(session); const botIdValue = botId(input.botId, 'botId'); const shares = await sharesFor(workShareRepository, session.id); const active = activeShares(shares); const remainingValue = await authoritativeRemaining(session, bots, logistics); validateHelper({ bots, goals, helperBotId: botIdValue, ownerBotId: session.ownerBotId, activeShares: active, maxHelpers: limits.maxHelpersPerSession, minimumChunk: limits.minimumChunk, remaining: remainingValue }); return rebalance({ session, participants: participantIds(active, [botIdValue]), repository, workShareRepository, bots, logistics, events });
  });
  const joinMany = async input => locked(tails, input.sessionId, async () => {
    const session = await repository.find(input.sessionId); ensureActive(session); const additions = normalizeBotIds(input.botIds, 'botId'); const shares = await sharesFor(workShareRepository, session.id); const preview = [...activeShares(shares)]; const remainingValue = await authoritativeRemaining(session, bots, logistics); for (const botIdValue of additions) { validateHelper({ bots, goals, helperBotId: botIdValue, ownerBotId: session.ownerBotId, activeShares: preview, maxHelpers: limits.maxHelpersPerSession, minimumChunk: limits.minimumChunk, remaining: remainingValue }); preview.push({ botId: botIdValue, role: 'HELPER', status: 'ASSIGNED' }); } return rebalance({ session, participants: participantIds(preview, []), repository, workShareRepository, bots, logistics, events });
  });
  const leave = async input => locked(tails, input.sessionId, async () => {
    let session = await repository.find(input.sessionId); ensureActive(session); const botIdValue = botId(input.botId, 'botId'); if (botIdValue === session.ownerBotId) throw new ConflictError('Owner cannot leave an active help session'); const shares = await sharesFor(workShareRepository, session.id); const active = activeShares(shares).filter(share => share.botId === botIdValue); if (!active.length) throw new NotFoundError('Active help worker', botIdValue);
    for (const share of active.filter(entry => entry.completed > entry.delivered)) { if (!destinationAvailable(session, bots)) { share.status = 'WAITING_DESTINATION'; await workShareRepository.update(share.shareId, share); session = { ...session, status: 'WAITING_DESTINATION' }; await repository.update(session.id, session); throw new ConflictError(`WAITING_TRANSFER '${botIdValue}' cannot deliver output because destination is unavailable`, { botId: botIdValue, sessionId: session.id }); } await handoffShare(session, share, input.signal); session = await repository.find(session.id); }
    for (const share of active) { const current = await workShareRepository.find(share.shareId); if (current.status !== 'COMPLETED') await workShareRepository.update(share.shareId, { ...current, status: 'CANCELLED' }); }
    const refreshed = await sharesFor(workShareRepository, session.id); return rebalance({ session, participants: participantIds(activeShares(refreshed).filter(share => share.botId !== botIdValue), []), repository, workShareRepository, bots, logistics, events });
  });
  const executeShare = async input => locked(tails, input.sessionId, async () => {
    const session = await repository.find(input.sessionId); ensureActive(session); const share = await shareFor(workShareRepository, session.id, input.shareId, input.botId); if (!['ASSIGNED', 'REASSIGN_REQUIRED'].includes(share.status)) throw new ConflictError(`Work share '${share.shareId}' is not assignable`, { status: share.status });
    const amount = Math.min(share.assigned - share.completed, await authoritativeRemaining(session, bots, logistics)); if (amount < 1) throw new ConflictError(`Work share '${share.shareId}' has no remaining assignment`);
    const before = inventoryCount(bots.get(share.botId), session.goal.item); const task = new Task({ id: `help:${share.shareId}:${share.attempt + 1}`, goalId: session.parentGoalId, type: 'help-collection', input: { block: session.goal.item, item: session.goal.item, count: amount }, requiredCapabilities: ['minecraft.collection'], retries: 0, timeout: 300_000, reportLifecycle: false }); task.update(TaskStatus.ASSIGNED, { assignedBot: share.botId });
    share.status = 'RUNNING'; share.taskId = task.id; share.attempt += 1; await workShareRepository.update(share.shareId, share); await publish(events, 'help.worker.assigned', { sessionId: session.id, shareId: share.shareId, botId: share.botId, assigned: amount });
    try { await executor.execute(task); } catch (error) { share.status = error.code === 'CANCELLED' ? 'CANCELLED' : 'FAILED'; await workShareRepository.update(share.shareId, share); throw error; }
    const after = inventoryCount(bots.get(share.botId), session.goal.item); const contribution = await recordContribution({ contributionRepository, session, share, before, after, delta: Math.min(Math.max(0, after - before), amount), contributionId: `CONTRIB-${share.shareId}-${share.attempt}` });
    share.completed += contribution.delta; share.status = contribution.delta ? 'OUTPUT_READY' : 'ASSIGNED'; await workShareRepository.update(share.shareId, share); await publish(events, 'help.worker.progress', { sessionId: session.id, shareId: share.shareId, completed: share.completed, delta: contribution.delta }); return get(session.id);
  });
  const recordCollected = async input => locked(tails, input.sessionId, async () => {
    const session = await repository.find(input.sessionId); const share = await shareFor(workShareRepository, session.id, input.shareId, input.botId); const before = integer(input.before, 'before'); const after = integer(input.after, 'after'); const delta = after - before; const contributionId = requiredId(input.contributionId, 'contributionId'); if (delta < 1) throw new ValidationError('after must be greater than before'); if (!await contributionExists(contributionRepository, contributionId) && delta > share.assigned - share.completed) throw new ConflictError(`Contribution exceeds available assignment for '${share.shareId}'`); const contribution = await recordContribution({ contributionRepository, session, share, before, after, delta, contributionId }); share.completed += contribution.delta; share.status = 'OUTPUT_READY'; await workShareRepository.update(share.shareId, share); await publish(events, 'help.output.ready', { sessionId: session.id, shareId: share.shareId, contributionId: contribution.id, delta }); return get(session.id);
  });
  const handoffShare = async (session, share, signal) => {
    const outputs = (await contributionRepository.list()).filter(entry => entry.sessionId === session.id && entry.shareId === share.shareId && entry.delivered < entry.delta); if (!outputs.length) throw new ConflictError(`Work share '${share.shareId}' has no undelivered output`); const donor = bots.get(share.botId);
    if (!destinationAvailable(session, bots)) { share.status = 'WAITING_DESTINATION'; await workShareRepository.update(share.shareId, share); session.status = 'WAITING_DESTINATION'; await repository.update(session.id, session); throw new ConflictError(`Destination bot '${session.outputPolicy.targetBotId}' is unavailable`); }
    for (const output of outputs) { const amount = output.delta - output.delivered; const delivery = await deliver({ session, donor, amount, fleetTransfer, logistics, bots, signal }); const current = await repository.find(session.id); const before = current.progress.current; const after = await resolveProgress({ outputPolicy: current.outputPolicy, ownerBotId: current.ownerBotId, bots, logistics, item: current.goal.item }); const credit = Math.min(amount, Math.max(0, after - before), current.progress.remaining); output.delivered += amount; output.credited += credit; output.status = credit === amount ? 'CREDITED' : 'SURPLUS'; await contributionRepository.update(output.id, output); share.delivered += amount; share.credited += credit; await publish(events, 'help.output.credited', { sessionId: session.id, shareId: share.shareId, contributionId: output.id, delivery, credited: credit }); const next = await updateSessionProgress(repository, current, credit, after); if (next.progress.remaining === 0) await completeParent(goals, next.parentTaskId); }
    share.status = share.credited >= share.assigned ? 'COMPLETED' : 'PARTIAL'; await workShareRepository.update(share.shareId, share); return get(session.id);
  };
  const handoff = async input => locked(tails, input.sessionId, async () => {
    const session = await repository.find(input.sessionId); const share = await shareFor(workShareRepository, session.id, input.shareId, input.botId); return handoffShare(session, share, input.signal);
  });
  const cancel = async (sessionId, reason) => locked(tails, sessionId, async () => { const session = await repository.find(sessionId); for (const share of await sharesFor(workShareRepository, sessionId)) { if (share.taskId) executor.cancel(share.taskId, reason); if (!['COMPLETED', 'FAILED'].includes(share.status)) { share.status = 'CANCELLED'; await workShareRepository.update(share.shareId, share); } } session.status = 'CANCELLED'; await repository.update(session.id, session); await publish(events, 'help.cancelled', { sessionId, reason }); return get(sessionId); });
  const cancelForParent = async (parentTaskId, reason) => Promise.all((await repository.list()).filter(session => session.parentTaskId === parentTaskId && !TERMINAL.has(session.status)).map(session => cancel(session.id, reason)));
  const handleBotDeath = async botIdValue => { const affected = []; for (const session of await repository.list()) { if (TERMINAL.has(session.status)) continue; if (session.outputPolicy.mode === 'OWNER' && session.outputPolicy.targetBotId === botIdValue) { session.status = 'WAITING_DESTINATION'; await repository.update(session.id, session); affected.push(await get(session.id)); continue; } const shares = (await sharesFor(workShareRepository, session.id)).filter(share => share.botId === botIdValue && share.delivered < share.completed); if (!shares.length) continue; await locked(tails, session.id, async () => { for (const share of shares) { share.status = 'HELPER_LOST'; await workShareRepository.update(share.shareId, share); } session.status = 'HELPER_LOST'; await repository.update(session.id, session); }); affected.push(await get(session.id)); } return affected; };
  const reconcileRecovery = async input => locked(tails, input.sessionId, async () => { const session = await repository.find(input.sessionId); const share = await shareFor(workShareRepository, session.id, input.shareId, input.botId); const recovered = itemCount(input.recoveredItems, session.goal.item); share.completed = Math.min(share.assigned, share.delivered + recovered); share.status = recovered ? 'OUTPUT_READY' : 'WAITING_RESOURCE'; await workShareRepository.update(share.shareId, share); session.status = 'ACTIVE'; await repository.update(session.id, session); return get(session.id); });
  const initialize = async () => { let reconciled = 0; const activeTaskIds = activeExecutorTaskIds(executor.status()); for (const session of await repository.list()) { if (TERMINAL.has(session.status)) continue; for (const share of await sharesFor(workShareRepository, session.id)) { if (share.status === 'RUNNING' && !activeTaskIds.has(share.taskId)) { share.status = 'REASSIGN_REQUIRED'; await workShareRepository.update(share.shareId, share); reconciled++; } } } return reconciled; };
  const status = async () => { const sessions = await repository.list(); return { status: 'HEALTHY', sessions: sessions.length, active: sessions.filter(session => !TERMINAL.has(session.status)).length, completed: sessions.filter(session => session.status === 'COMPLETED').length }; };
  return Object.freeze({ create, previewCreate, get, list, remaining, activeForOwner, join, joinMany, leave, executeShare, recordCollected, handoff, cancel, cancelForParent, handleBotDeath, reconcileRecovery, initialize, status });
}

function createShare({ sessionId, parentTaskId, botId, assigned, role, generation }) { const now = new Date().toISOString(); const shareId = randomUUID(); return { id: shareId, shareId, sessionId, parentTaskId, botId, role, generation, assigned, completed: 0, delivered: 0, credited: 0, status: 'ASSIGNED', taskId: null, attempt: 0, createdAt: now, updatedAt: now }; }
async function recordContribution({ contributionRepository, session, share, before, after, delta, contributionId }) { try { const existing = await contributionRepository.find(contributionId); if (existing.sessionId !== session.id || existing.shareId !== share.shareId || existing.before !== before || existing.after !== after) throw new ConflictError(`Contribution '${contributionId}' conflicts with existing ledger entry`); return { ...existing, delta: 0 }; } catch (error) { if (!(error instanceof NotFoundError)) throw error; } const record = { id: contributionId, sessionId: session.id, shareId: share.shareId, parentTaskId: session.parentTaskId, botId: share.botId, before, after, delta, credited: 0, delivered: 0, destination: destinationFor(session.outputPolicy, share.botId), status: 'OUTPUT_READY', createdAt: new Date().toISOString() }; await contributionRepository.create(record); return record; }
async function contributionExists(repository, id) { try { await repository.find(id); return true; } catch (error) { if (error instanceof NotFoundError) return false; throw error; } }
async function deliver({ session, donor, amount, fleetTransfer, logistics, bots, signal }) { if (session.outputPolicy.mode === 'OWNER') { const owner = bots.get(session.outputPolicy.targetBotId); return donor.id === owner.id ? verifyOwnerPossession(owner, session.goal.item, amount) : fleetTransfer.transfer({ donor, receiver: owner, item: session.goal.item, count: amount, signal }); } if (session.outputPolicy.mode === 'SHARED_STORAGE') return logistics.store({ runtime: donor, storageName: session.outputPolicy.storageName, item: session.goal.item, count: amount }); return verifyOwnerPossession(donor, session.goal.item, amount); }
async function updateSessionProgress(repository, session, credit, current) { const next = structuredClone(session); next.progress = progress(next.goal.target, next.progress.initial, next.progress.credited + credit, current); next.status = next.progress.remaining === 0 ? 'COMPLETED' : 'ACTIVE'; next.version += 1; next.updatedAt = new Date().toISOString(); return repository.update(next.id, next); }
async function completeParent(goals, parentTaskId) { await goals.completeExternalTask(parentTaskId, { source: 'help-session', verified: true }); }
async function sharesFor(repository, sessionId) { return (await repository.list()).filter(share => share.sessionId === sessionId); }
async function rebalance({ session, participants, repository, workShareRepository, bots, logistics, events }) {
  const current = await sharesFor(workShareRepository, session.id); const preserved = current.filter(share => !['SUPERSEDED', 'CANCELLED'].includes(share.status) && share.completed > share.delivered); const remaining = await authoritativeRemaining(session, bots, logistics); const reserved = preserved.reduce((sum, share) => sum + share.completed - share.delivered, 0); const distributable = Math.max(0, remaining - reserved); if (distributable && !participants.length) throw new ConflictError('No workers available for help rebalancing');
  await publish(events, 'help.rebalance.started', { sessionId: session.id, remaining, reserved, participants }); for (const share of current.filter(share => !['SUPERSEDED', 'CANCELLED', 'COMPLETED'].includes(share.status) && share.completed === share.delivered)) { share.status = 'SUPERSEDED'; await workShareRepository.update(share.shareId, share); await publish(events, 'help.share.superseded', { sessionId: session.id, shareId: share.shareId }); }
  const generation = (session.generation ?? 1) + 1; const allocations = distributable ? splitWork(distributable, participants) : []; for (const allocation of allocations) { const share = createShare({ sessionId: session.id, parentTaskId: session.parentTaskId, botId: allocation.botId, assigned: allocation.assigned, role: allocation.botId === session.ownerBotId ? 'OWNER' : 'HELPER', generation }); await workShareRepository.create(share); await publish(events, 'help.share.created', { sessionId: session.id, shareId: share.shareId, botId: share.botId, assigned: share.assigned, generation }); }
  const next = { ...session, generation, status: remaining === 0 ? 'COMPLETED' : 'ACTIVE', updatedAt: new Date().toISOString(), version: (session.version ?? 0) + 1 }; await repository.update(session.id, next); await publish(events, 'help.rebalance.completed', { sessionId: session.id, generation, remaining, reserved, allocated: distributable }); return view(next, await sharesFor(workShareRepository, session.id));
}
function activeShares(shares) { return shares.filter(share => !['SUPERSEDED', 'CANCELLED', 'COMPLETED', 'FAILED'].includes(share.status)); }
function participantIds(shares, additions) { return [...new Set([...shares.map(share => share.botId), ...additions])]; }
function normalizeLimits(maxHelpersPerSession, minimumChunk) { const maxHelpers = positive(maxHelpersPerSession, 'maxHelpersPerSession'); const chunk = positive(minimumChunk, 'minimumChunk'); return { maxHelpersPerSession: maxHelpers, minimumChunk: chunk }; }
function validateHelperLimit(workerIds, ownerBotId, maxHelpers) { const helpers = new Set(workerIds.filter(id => id !== ownerBotId)); if (helpers.size > maxHelpers) throw new ConflictError(`MAX_HELPERS_REACHED ${maxHelpers}`, { code: 'MAX_HELPERS_REACHED', maxHelpers }); }
function normalizeBotIds(values, label) { if (!Array.isArray(values) || !values.length) throw new ConflictError('At least one helper is required'); const ids = values.map(value => botId(value, label)); if (new Set(ids).size !== ids.length) throw new ConflictError('ALREADY_HELPING duplicate helper requested', { code: 'ALREADY_HELPING' }); return ids; }
async function shareFor(repository, sessionId, shareId, botIdValue) { const shares = await sharesFor(repository, sessionId); const share = shares.find(entry => (shareId && entry.shareId === shareId) || (!shareId && entry.botId === botIdValue)); if (!share) throw new NotFoundError('Work share', shareId ?? botIdValue); return share; }
async function locked(tails, sessionId, operation) { const previous = tails.get(sessionId) ?? Promise.resolve(); const next = previous.then(operation, operation); tails.set(sessionId, next.catch(() => undefined)); return next; }
function view(session, shares) { return { ...session, workShares: shares, workers: shares }; }
function ensureActive(session) { if (TERMINAL.has(session.status)) throw new ConflictError(`Help session '${session.id}' is ${session.status}`); }
function normalizeWorkerIds(value, ownerBotId) { const entries = Array.isArray(value) && value.length ? value : [{ botId: ownerBotId }]; return entries.map(entry => botId(typeof entry === 'string' ? entry : entry.botId, 'worker.botId')); }
function validateRequestedAssignments(value, remaining) { if (!Array.isArray(value) || !value.some(entry => Number.isInteger(entry?.assigned))) return []; const assignments = value.map(entry => ({ botId: botId(entry.botId, 'worker.botId'), assigned: positive(entry.assigned, 'Worker assigned') })); if (new Set(assignments.map(entry => entry.botId)).size !== assignments.length) throw new ValidationError('Help workers must be unique'); const total = assignments.reduce((sum, entry) => sum + entry.assigned, 0); if (total > remaining) throw new ValidationError(`Total worker assignments ${total} exceed remaining work ${remaining}`); return assignments; }
function normalizePolicy(value, ownerBotId, fleetWide) { const mode = String(value?.mode ?? 'OWNER').toUpperCase(); if (!MODES.has(mode)) throw new ValidationError('Help output policy mode must be OWNER, SHARED_STORAGE, or HELPER_KEEP'); if (mode === 'HELPER_KEEP' && !fleetWide) throw new ValidationError('HELPER_KEEP requires fleetWide ownership'); const targetBotId = mode === 'OWNER' ? botId(value?.targetBotId ?? ownerBotId, 'outputPolicy.targetBotId') : null; const storageName = mode === 'SHARED_STORAGE' ? String(value?.storageName ?? '').trim() : null; if (mode === 'SHARED_STORAGE' && !storageName) throw new ValidationError('SHARED_STORAGE requires outputPolicy.storageName'); return { mode, targetBotId, storageName, fleetWide }; }
function progress(target, initial, credited, current) { const resolved = Math.min(target, current); return { initial, credited, current: resolved, remaining: target - resolved }; }
async function authoritativeRemaining(session, bots, logistics) { const current = await resolveProgress({ outputPolicy: session.outputPolicy, ownerBotId: session.ownerBotId, bots, logistics, item: session.goal.item }); return Math.max(0, session.goal.target - current); }
async function resolveProgress({ outputPolicy, ownerBotId, bots, logistics, item }) { if (outputPolicy.mode === 'OWNER') return inventoryCount(bots.get(ownerBotId), item); if (outputPolicy.mode === 'HELPER_KEEP') return bots.list().reduce((sum, runtime) => sum + inventoryCount(runtime, item), 0); const storages = await logistics.storages(); const storage = storages.find(entry => entry.name === outputPolicy.storageName); if (!storage) throw new NotFoundError('Storage', outputPolicy.storageName); return itemCount(storage.inventory, item); }
function destinationAvailable(session, bots) { if (session.outputPolicy.mode !== 'OWNER') return true; const runtime = bots.get(session.outputPolicy.targetBotId); return !['OFFLINE', 'DEAD', 'FAILED', 'DISCONNECTED'].includes(runtime.status); }
function destinationFor(policy, helperBotId) { return policy.mode === 'OWNER' ? { type: 'BOT', id: policy.targetBotId } : policy.mode === 'SHARED_STORAGE' ? { type: 'STORAGE', id: policy.storageName } : { type: 'BOT', id: helperBotId }; }
function activeExecutorTaskIds(status) { return new Set([...(Object.values(status.running ?? {})), ...Object.values(status.queues ?? {}).flat().map(entry => entry.taskId)]); }
function inventoryCount(runtime, item) { return (runtime.adapter.snapshot().inventorySummary ?? []).filter(entry => String(entry?.name).toLowerCase() === item).reduce((sum, entry) => sum + Number(entry.count ?? 0), 0); }
function itemCount(items, item) { return (Array.isArray(items) ? items : []).filter(entry => String(entry?.name).toLowerCase() === item).reduce((sum, entry) => sum + Number(entry.count ?? 0), 0); }
function verifyOwnerPossession(runtime, item, amount) { const count = inventoryCount(runtime, item); if (count < amount) throw new ConflictError(`Destination bot '${runtime.id}' does not possess ${amount} '${item}'`); return { item, transferred: amount, verified: true }; }
function requiredId(value, label) { const id = String(value ?? '').trim(); if (!id) throw new ValidationError(`${label} is required`); return id; }
function botId(value, label) { const id = requiredId(value, label); if (!/^[A-Za-z0-9_.:-]{1,128}$/.test(id)) throw new ValidationError(`${label} must be a valid bot id`); return id; }
function integer(value, label) { const number = Number(value); if (!Number.isInteger(number) || number < 0) throw new ValidationError(`${label} must be a non-negative integer`); return number; }
function positive(value, label) { const number = integer(value, label); if (number < 1 || number > 10_000) throw new ValidationError(`${label} must be an integer between 1 and 10000`); return number; }
async function publish(events, type, payload) { await events?.publish(type, payload, { source: 'help' }); }
