import test from 'node:test';
import assert from 'node:assert/strict';
import { createClientBridgeService } from '../src/client/client-bridge-service.js';
function setup() {
  const calls = { begin: [], control: [], release: [], move: [] }; const runtimes = new Map();
  for (const id of ['bot1', 'bot2']) { const adapter = { snapshot: () => ({ position: { x: id === 'bot1' ? 0 : 4, y: 64, z: 0 }, dimension: 'overworld', health: 20, food: 20, inventorySummary: [] }), beginClientControl: async input => calls.begin.push({ id, input }), applyClientControl: async input => { calls.control.push({ id, input }); return { position: { x: 1, y: 64, z: 0 } }; }, releaseClientControl: async input => calls.release.push({ id, input }) }; const runtime = { machine: { state: 'READY' }, options: { username: id.toUpperCase() }, adapter, snapshot: () => ({ id, name: id, status: 'READY', runtime: adapter.snapshot() }) }; runtimes.set(id, runtime); }
  const bots = { get: id => { const value = runtimes.get(id); if (!value) throw new Error('missing'); return value; }, list: () => [...runtimes.values()].map(item => item.snapshot()) };
  const navigation = { moveTo: async input => { calls.move.push(input); return { status: 'ARRIVED' }; } }; const building = { list: async () => [{ id: 'house', name: 'House', status: 'READY', revision: 2 }] };
  return { service: createClientBridgeService({ bots, navigation, building, leaseTtlMs: 10_000 }), calls };
}
test('client bridge switches by bot identity and rejects a second lease owner', async t => { const { service, calls } = setup(); t.after(() => service.dispose()); const first = await service.open({ playerName: 'Alice' }); const second = await service.open({ playerName: 'Bob' }); const selected = await service.switchBody({ sessionId: first.id, botId: 'bot1' }); assert.equal(selected.session.controlledBotId, 'bot1'); assert.equal(calls.begin.length, 1); await assert.rejects(service.switchBody({ sessionId: second.id, botId: 'bot1' }), error => error.code === 'CONFLICT'); await service.switchBody({ sessionId: first.id, botId: 'bot2' }); assert.equal(calls.release[0].id, 'bot1'); assert.equal(calls.begin[1].id, 'bot2'); });
test('client bridge ignores stale controls and exposes fleet/building state', async t => { const { service, calls } = setup(); t.after(() => service.dispose()); const session = await service.open({ playerName: 'Alice' }); await service.switchBody({ sessionId: session.id, botId: 'bot1' }); assert.equal((await service.control({ sessionId: session.id, sequence: 2, forward: true, yaw: 90, pitch: 0 })).accepted, true); assert.equal((await service.control({ sessionId: session.id, sequence: 1, forward: false })).stale, true); assert.equal(calls.control.length, 1); const state = await service.state(session.id); assert.equal(state.bots[0].username, 'BOT1'); assert.equal(state.blueprints[0].id, 'house'); });
test('RTS move fans out safe navigation targets with formation offsets', async t => { const { service, calls } = setup(); t.after(() => service.dispose()); const session = await service.open({ playerName: 'Alice' }); const result = await service.rtsMove({ sessionId: session.id, botIds: ['bot1', 'bot2'], target: { x: 20, y: 64, z: 20 }, formation: 'LINE' }); assert.equal(result.completed, 2); assert.equal(calls.move.length, 2); assert.equal(calls.move[0].source, 'GROUP'); assert.notEqual(calls.move[0].target.x, calls.move[1].target.x); });
