import test from 'node:test';
import assert from 'node:assert/strict';
import { collectWorkerStates, createCoordinationMonitor, EventBus, MemoryRepository, Task, TaskStatus, createFleetTransferService, createHelpCommandService, createHelpService, splitWeightedWork } from '../src/index.js';
import { CapabilityRegistry } from '../src/bots/capabilities.js';
import { MetricsManager } from '../src/core/health.js';
import { FleetScheduler } from '../src/fleet/scheduler.js';
import { GoalService } from '../src/goals/goal-service.js';
import { DeterministicPlanner } from '../src/goals/planner.js';
import { resolveActiveHelpTask } from '../src/help/active-task-resolver.js';
import { TaskExecutor } from '../src/tasks/task-executor.js';

class BotAdapter {
  constructor(items, position) { this.items = items; this.position = position; }
  snapshot() { return { inventorySummary: structuredClone(this.items), inventorySlots: this.slots ?? null, inventorySlotsUsed: this.slotsUsed ?? 0, inventorySlotsFree: this.slotsFree ?? (this.capacity ?? 36), freeItemCapacity: this.capacityUnits ?? ((this.capacity ?? 36) * 64), position: this.position, dimension: 'overworld' }; }
  async smartMove() {}
  async dropItem({ item, count }) { change(this.items, item, -count); }
  async pickupItem({ item, count }) { change(this.items, item, count); }
}

function setup(target = 64, options = {}) {
  const owner = runtime('owner', options.ownerStone ?? 34, 0); const helper = runtime('helper', options.helperStone ?? 0, 8); const helper2 = runtime('helper2', options.helper2Stone ?? 0, 16); const helper3 = runtime('helper3', options.helper3Stone ?? 0, 24); const runtimes = { owner, helper, helper2, helper3 }; const parent = new Task({ id: 'parent-collect', goalId: 'goal-1', type: 'collect', input: { block: 'stone', count: target }, requiredCapabilities: ['minecraft.collection'] });
  const events = new EventBus(); const goals = { task: id => { if (id !== parent.id) throw new Error(`Task '${id}' not found`); return parent; }, allTasks: () => [parent.toDTO()], completeExternalTask: async (id, result) => { if (id !== parent.id) throw new Error(`Task '${id}' not found`); parent.update(TaskStatus.COMPLETED, { result }); return parent.toDTO(); }, transitionTaskToCollaborative: async (id, helpSessionId) => { if (id !== parent.id) throw new Error(`Task '${id}' not found`); parent.update(TaskStatus.COLLABORATIVE, { helpSessionId }); return parent.toDTO(); } }; const executor = options.executorFactory ? options.executorFactory(runtimes) : { cancel: () => true, status: () => ({ running: {}, queues: {} }), execute: async task => { change(runtimes[task.assignedBot].adapter.items, 'stone', task.input.count); task.update(TaskStatus.COMPLETED); return { collected: task.input.count }; } }; const logistics = { store: async ({ runtime: value, item, count }) => { change(value.adapter.items, item, -count); return { stored: count }; }, storages: async () => options.storages ?? [] };
  const repositories = { sessions: new MemoryRepository(), shares: new MemoryRepository(), contributions: new MemoryRepository() }; const service = createHelpService({ repository: repositories.sessions, workShareRepository: repositories.shares, contributionRepository: repositories.contributions, bots: { get: id => runtimes[id], list: () => Object.values(runtimes) }, fleetTransfer: createFleetTransferService({ events }), logistics, goals, executor, events, maxHelpersPerSession: options.maxHelpersPerSession ?? 4, minimumChunk: options.minimumChunk ?? 4, coordination: options.coordination }); return { owner, helper, helper2, helper3, parent, service, repositories, bots: { get: id => runtimes[id], list: () => Object.values(runtimes) }, fleetTransfer: createFleetTransferService({ events }), logistics, goals, executor, events };
}

test('uses actual parent task and splits remaining 30 equally', async () => {
  const { service } = setup(); await assert.rejects(service.create({ ownerBotId: 'owner', workers: ['helper'] }), /parentTaskId/); await assert.rejects(service.create({ parentTaskId: 'fake', ownerBotId: 'owner', workers: ['helper'] }), /not found/);
  const session = await service.create({ parentTaskId: 'parent-collect', ownerBotId: 'owner', workers: ['helper', 'helper2'] }); assert.equal(session.progress.remaining, 30); assert.deepEqual(session.workShares.map(share => share.assigned), [15, 15]);
});

test('splits odd remaining work across three workers without over-assignment', async () => {
  const { service } = setup(65); const session = await service.create({ parentTaskId: 'parent-collect', ownerBotId: 'owner', workers: ['helper', 'helper2', 'helper3'] }); assert.deepEqual(session.workShares.map(share => share.assigned), [11, 10, 10]);
  await assert.rejects(service.create({ parentTaskId: 'parent-collect', ownerBotId: 'owner', workers: [{ botId: 'helper', assigned: 31 }] }), /active help session/);
  const { service: fresh } = setup(); await assert.rejects(fresh.create({ parentTaskId: 'parent-collect', ownerBotId: 'owner', workers: [{ botId: 'helper', assigned: 31 }] }), /exceed remaining work 30/);
});

test('executes a WorkShare through TaskExecutor and credits verified handoff', async () => {
  const { owner, parent, service } = setup(49); const session = await service.create({ parentTaskId: parent.id, ownerBotId: 'owner', workers: ['helper'] }); const active = await service.executeShare({ sessionId: session.id, shareId: session.workShares[0].shareId }); assert.equal(active.workShares[0].completed, 15);
  const complete = await service.handoff({ sessionId: session.id, shareId: session.workShares[0].shareId }); assert.equal(complete.status, 'COMPLETED'); assert.equal(complete.progress.credited, 15); assert.equal(count(owner.adapter.items, 'stone'), 49); assert.equal(parent.status, TaskStatus.COMPLETED);
});

test('records separate multi-batch contributions and rejects duplicate credit', async () => {
  const { helper, service } = setup(50); const session = await service.create({ parentTaskId: 'parent-collect', ownerBotId: 'owner', workers: [{ botId: 'helper', assigned: 16 }] }); const shareId = session.workShares[0].shareId;
  change(helper.adapter.items, 'stone', 8); await service.recordCollected({ sessionId: session.id, shareId, contributionId: 'CONTRIB-001', before: 0, after: 8 }); await service.handoff({ sessionId: session.id, shareId });
  change(helper.adapter.items, 'stone', 8); await service.recordCollected({ sessionId: session.id, shareId, contributionId: 'CONTRIB-002', before: 0, after: 8 }); const duplicate = await service.recordCollected({ sessionId: session.id, shareId, contributionId: 'CONTRIB-002', before: 0, after: 8 }); assert.equal(duplicate.workShares[0].completed, 16); const complete = await service.handoff({ sessionId: session.id, shareId }); assert.equal(complete.progress.credited, 16);
});

test('rejects unsupported parent tasks', async () => {
  const { service } = setup(); const invalid = { id: 'parent-collect', goalId: 'goal-1', input: { count: 1 }, requiredCapabilities: ['minecraft.crafting'] }; const invalidService = createHelpService({ repository: new MemoryRepository(), workShareRepository: new MemoryRepository(), contributionRepository: new MemoryRepository(), bots: { get: () => runtime('owner', 0, 0) }, fleetTransfer: createFleetTransferService({ events: new EventBus() }), logistics: {}, goals: { task: () => invalid }, executor: { execute: async () => {}, cancel: () => false }, maxHelpersPerSession: 4, minimumChunk: 4 }); await assert.rejects(invalidService.create({ parentTaskId: 'parent-collect', ownerBotId: 'owner' }), /not a supported collection task/); assert.ok(service);
});

test('uses shared storage and fleet possession as authoritative progress sources', async () => {
  const storage = { name: 'warehouse', inventory: [{ name: 'stone', count: 700 }] }; const shared = setup(1000, { ownerStone: 0, storages: [storage] }); const sharedSession = await shared.service.create({ parentTaskId: shared.parent.id, ownerBotId: 'owner', workers: ['helper'], outputPolicy: { mode: 'SHARED_STORAGE', storageName: 'warehouse' } }); assert.equal(sharedSession.progress.remaining, 300);
  const fleet = setup(100, { ownerStone: 10, helperStone: 20, helper2Stone: 30 }); const fleetSession = await fleet.service.create({ parentTaskId: fleet.parent.id, ownerBotId: 'owner', workers: ['helper3'], fleetWide: true, outputPolicy: { mode: 'HELPER_KEEP' } }); assert.equal(fleetSession.progress.current, 60); assert.equal(fleetSession.workShares[0].assigned, 40);
});

test('owner death pauses delivery until the owner is available again', async () => {
  const { owner, parent, service } = setup(49); const session = await service.create({ parentTaskId: parent.id, ownerBotId: 'owner', workers: ['helper'] }); await service.executeShare({ sessionId: session.id, shareId: session.workShares[0].shareId }); owner.status = 'DEAD'; const affected = await service.handleBotDeath('owner'); assert.equal(affected.length, 1); assert.equal((await service.get(session.id)).status, 'WAITING_DESTINATION'); await assert.rejects(service.handoff({ sessionId: session.id, shareId: session.workShares[0].shareId }), /unavailable/); owner.status = 'READY'; const complete = await service.handoff({ sessionId: session.id, shareId: session.workShares[0].shareId }); assert.equal(complete.status, 'COMPLETED');
});

test('concurrent helper handoffs serialize progress without over-credit', async () => {
  const { owner, parent, service } = setup(); const session = await service.create({ parentTaskId: parent.id, ownerBotId: 'owner', workers: ['helper', 'helper2'] }); await Promise.all(session.workShares.map(share => service.executeShare({ sessionId: session.id, shareId: share.shareId }))); const complete = await Promise.all(session.workShares.map(share => service.handoff({ sessionId: session.id, shareId: share.shareId }))); assert.equal(complete.at(-1).progress.credited, 30); assert.equal(count(owner.adapter.items, 'stone'), 64); assert.equal((await service.get(session.id)).status, 'COMPLETED');
});

test('restart reconciliation reassigns orphaned running shares and preserves output-ready shares', async () => {
  const context = setup(49); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper'] }); const share = session.workShares[0]; await context.repositories.shares.update(share.shareId, { ...share, status: 'RUNNING', taskId: 'missing-task' }); const restored = createHelpService({ repository: context.repositories.sessions, workShareRepository: context.repositories.shares, contributionRepository: context.repositories.contributions, bots: context.bots, fleetTransfer: context.fleetTransfer, logistics: context.logistics, goals: context.goals, executor: { ...context.executor, status: () => ({ running: {}, queues: {} }) }, events: context.events, maxHelpersPerSession: 4, minimumChunk: 4 }); assert.equal(await restored.initialize(), 1); assert.equal((await restored.get(session.id)).workShares[0].status, 'REASSIGN_REQUIRED');
});

test('manual helper request creates one collaborative session and rebalances joins', async () => {
  const context = setup(); context.parent.update(TaskStatus.ASSIGNED, { assignedBot: 'owner' }); const commands = createHelpCommandService({ help: context.service, goals: context.goals, bots: context.bots, events: context.events, maxHelpersPerSession: 4, minimumChunk: 4 }); const first = await commands.requestHelp({ helperBotId: 'helper', ownerBotId: 'owner' }); assert.equal(first.workShares.length, 2); assert.deepEqual(first.workShares.map(share => share.assigned), [15, 15]); assert.equal(context.parent.status, TaskStatus.COLLABORATIVE);
  const joined = await commands.requestHelp({ helperBotId: 'helper2', ownerBotId: 'owner' }); const active = joined.workShares.filter(share => share.status !== 'SUPERSEDED'); assert.deepEqual(active.map(share => share.assigned), [10, 10, 10]);
});

test('active task resolver skips unsupported running task and selects helpable assigned task', () => {
  const unsupported = new Task({ id: 'unsupported', goalId: 'goal-1', type: 'craft', input: { item: 'stick', count: 1 }, requiredCapabilities: ['minecraft.crafting'], priority: 100 }); unsupported.update(TaskStatus.RUNNING, { assignedBot: 'owner' }); const supported = new Task({ id: 'supported', goalId: 'goal-1', type: 'collect', input: { block: 'stone', count: 16 }, requiredCapabilities: ['minecraft.collection'], priority: 10 }); supported.update(TaskStatus.ASSIGNED, { assignedBot: 'owner' }); const tasks = new Map([[unsupported.id, unsupported], [supported.id, supported]]); const goals = { allTasks: () => [...tasks.values()].map(task => task.toDTO()), task: id => tasks.get(id) };
  assert.equal(resolveActiveHelpTask(goals, 'owner').id, supported.id);
});

test('joinMany enforces max helpers and minimum chunk with an incremental preview', async () => {
  const limited = setup(100, { ownerStone: 0, maxHelpersPerSession: 2 }); const session = await limited.service.create({ parentTaskId: limited.parent.id, ownerBotId: 'owner', workers: ['owner', 'helper'] }); await assert.rejects(limited.service.joinMany({ sessionId: session.id, botIds: ['helper2', 'helper3'] }), /MAX_HELPERS_REACHED/); assert.equal((await limited.service.get(session.id)).workShares.filter(share => !['SUPERSEDED', 'CANCELLED'].includes(share.status)).length, 2);
  const small = setup(10, { ownerStone: 0, minimumChunk: 4 }); const smallSession = await small.service.create({ parentTaskId: small.parent.id, ownerBotId: 'owner', workers: ['owner', 'helper'] }); await assert.rejects(small.service.joinMany({ sessionId: smallSession.id, botIds: ['helper2'] }), /Minimum work chunk/);
});

test('first manual join validates authoritative remaining before creating a session', async () => {
  const context = setup(64, { ownerStone: 62, minimumChunk: 4 }); context.parent.update(TaskStatus.ASSIGNED, { assignedBot: 'owner' }); const commands = createHelpCommandService({ help: context.service, goals: context.goals, bots: context.bots, events: context.events, maxHelpersPerSession: 4, minimumChunk: 4 }); await assert.rejects(commands.requestHelp({ helperBotId: 'helper', ownerBotId: 'owner' }), /Minimum work chunk/); assert.equal((await context.service.list()).length, 0);
});

test('stop helping hands off pending output before helper leaves', async () => {
  const context = setup(49); context.parent.update(TaskStatus.ASSIGNED, { assignedBot: 'owner' }); const commands = createHelpCommandService({ help: context.service, goals: context.goals, bots: context.bots, events: context.events, maxHelpersPerSession: 4, minimumChunk: 4 }); const session = await commands.requestHelp({ helperBotId: 'helper', ownerBotId: 'owner' }); const share = session.workShares.find(entry => entry.botId === 'helper'); change(context.helper.adapter.items, 'stone', share.assigned); await context.service.recordCollected({ sessionId: session.id, shareId: share.shareId, contributionId: 'CONTRIB-LEAVE', before: 0, after: share.assigned }); const result = await commands.stopHelping({ botId: 'helper' }); assert.equal(count(context.owner.adapter.items, 'stone'), 34 + share.assigned); assert.equal(result.progress.credited, share.assigned); assert.equal(result.workShares.some(entry => entry.botId === 'helper' && entry.status === 'OUTPUT_READY'), false);
});

test('owner removal hands off pending output before removing the helper', async () => {
  const context = setup(49); context.parent.update(TaskStatus.ASSIGNED, { assignedBot: 'owner' }); const commands = createHelpCommandService({ help: context.service, goals: context.goals, bots: context.bots, events: context.events, maxHelpersPerSession: 4, minimumChunk: 4 }); const session = await commands.requestHelp({ helperBotId: 'helper', ownerBotId: 'owner' }); const share = session.workShares.find(entry => entry.botId === 'helper'); change(context.helper.adapter.items, 'stone', share.assigned); await context.service.recordCollected({ sessionId: session.id, shareId: share.shareId, contributionId: 'CONTRIB-REMOVE', before: 0, after: share.assigned }); const result = await commands.removeHelper({ ownerBotId: 'owner', helperBotId: 'helper' }); assert.equal(count(context.owner.adapter.items, 'stone'), 34 + share.assigned); assert.equal(result.workShares.some(entry => entry.botId === 'helper' && entry.status === 'OUTPUT_READY'), false);
});

test('manual help rejects helpers in recovery state', async () => {
  const context = setup(); context.parent.update(TaskStatus.ASSIGNED, { assignedBot: 'owner' }); context.helper.status = 'RECOVERY'; const commands = createHelpCommandService({ help: context.service, goals: context.goals, bots: context.bots, events: context.events, maxHelpersPerSession: 4, minimumChunk: 4 }); await assert.rejects(commands.requestHelp({ helperBotId: 'helper', ownerBotId: 'owner' }), /HELPER_BUSY/); context.helper.status = 'READY'; const recovery = new Task({ id: 'recovery-task', goalId: 'goal-2', type: 'recovery', input: {}, requiredCapabilities: ['minecraft.collection'] }); recovery.update(TaskStatus.RUNNING, { assignedBot: 'helper' }); context.goals.allTasks = () => [context.parent.toDTO(), recovery.toDTO()]; await assert.rejects(commands.requestHelp({ helperBotId: 'helper', ownerBotId: 'owner' }), /executing RECOVERY/); assert.equal((await context.service.list()).length, 0);
});

test('concurrent command joins create one session without duplicate work shares', async () => {
  const context = setup(100, { ownerStone: 0 }); context.parent.update(TaskStatus.ASSIGNED, { assignedBot: 'owner' }); const commands = createHelpCommandService({ help: context.service, goals: context.goals, bots: context.bots, events: context.events, maxHelpersPerSession: 4, minimumChunk: 4 }); const joined = await Promise.all([commands.requestHelp({ helperBotId: 'helper', ownerBotId: 'owner' }), commands.requestHelp({ helperBotId: 'helper2', ownerBotId: 'owner' }), commands.requestHelp({ helperBotId: 'helper3', ownerBotId: 'owner' })]); const sessions = await context.service.list(); const current = await context.service.get(joined[0].id); const active = current.workShares.filter(share => !['SUPERSEDED', 'CANCELLED', 'COMPLETED', 'FAILED'].includes(share.status)); assert.equal(sessions.length, 1); assert.deepEqual([...new Set(active.map(share => share.botId))].sort(), ['helper', 'helper2', 'helper3', 'owner']);
});

test('running parent takeover waits for executor stop and never publishes task.cancelled', async () => {
  const events = new EventBus(); const metrics = new MetricsManager(); const capabilities = new CapabilityRegistry(); capabilities.register({ name: 'minecraft.collection', execute: async (_input, context) => new Promise((resolve, reject) => { context.signal.addEventListener('abort', () => reject(context.signal.reason), { once: true }); }) }); const botManager = { list: () => [{ id: 'owner', status: 'READY', capabilities: ['minecraft.collection'] }] }; const scheduler = new FleetScheduler({ botManager }); const executor = new TaskExecutor({ capabilities, scheduler, eventBus: events, metrics, checkpointRepository: null, maxQueuePerBot: 10 }); const goals = new GoalService({ planner: new DeterministicPlanner(), scheduler, executor, eventBus: events, metrics }); let cancellations = 0; events.subscribe('task.cancelled', async () => { cancellations += 1; }); const goal = goals.create({ description: 'collect stone', constraints: { preferredBot: 'owner' }, steps: [{ type: 'collect', input: { block: 'stone', count: 64 }, requiredCapabilities: ['minecraft.collection'] }] }); const parent = goals.tasks(goal.id)[0]; const running = goals.run(goal.id); await waitFor(() => goals.task(parent.id).status === TaskStatus.RUNNING, 100, 10); const collaborative = await goals.transitionTaskToCollaborative(parent.id, 'help-session-1'); await running; assert.equal(collaborative.status, TaskStatus.COLLABORATIVE); assert.equal(goals.task(parent.id).status, TaskStatus.COLLABORATIVE); assert.equal(cancellations, 0); assert.deepEqual(executor.status().running, {});
});

test('weighted splitter is deterministic and respects worker capacity', () => {
  const allocations = splitWeightedWork({ remaining: 30, workerStates: [
    { botId: 'fast', available: true, alive: true, connected: true, toolSuitable: true, inventoryFreeSlots: 20, currentRate: 2, remaining: 0 },
    { botId: 'slow', available: true, alive: true, connected: true, toolSuitable: true, inventoryFreeSlots: 10, currentRate: 0, remaining: 8 },
    { botId: 'offline', available: false, alive: true, connected: false, toolSuitable: true, inventoryFreeSlots: 36, currentRate: 9, remaining: 0 }
  ] });
  assert.deepEqual(allocations.map(entry => [entry.botId, entry.assigned]), [['fast', 20], ['slow', 10]]);
});

test('rebalance creates a new generation once per idempotency key without changing credited progress', async () => {
  const context = setup(64, { ownerStone: 0 }); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['owner', 'helper', 'helper2'] }); const first = await context.service.rebalanceSession({ sessionId: session.id, reason: 'MANUAL_REBALANCE', rebalanceKey: 'rebalance-1' }); const repeated = await context.service.rebalanceSession({ sessionId: session.id, reason: 'MANUAL_REBALANCE', rebalanceKey: 'rebalance-1' });
  assert.equal(first.generation, 2); assert.equal(repeated.generation, 2); assert.equal(repeated.workShares.filter(share => share.generation === 2).reduce((total, share) => total + share.assigned, 0), 64); assert.equal(repeated.progress.credited, 0); assert.ok(repeated.workShares.filter(share => share.generation === 1).every(share => share.status === 'SUPERSEDED'));
});

test('an idle helper steals only unfinished work through a fresh generation', async () => {
  const context = setup(64, { ownerStone: 0 }); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper', 'helper2'] }); const helper2Share = session.workShares.find(share => share.botId === 'helper2'); await context.repositories.shares.update(helper2Share.shareId, { ...helper2Share, status: 'COMPLETED', completed: helper2Share.assigned, delivered: helper2Share.assigned, credited: helper2Share.assigned });
  change(context.owner.adapter.items, 'stone', helper2Share.assigned);
  const stolen = await context.service.stealWork({ sessionId: session.id, botId: 'helper2' }); const active = stolen.workShares.filter(share => share.generation === stolen.generation); assert.ok(active.some(share => share.botId === 'helper2' && share.assigned > 0)); assert.ok(active.reduce((total, share) => total + share.assigned, 0) <= stolen.progress.remaining);
});

test('pause and resume preserve progress while creating a fresh assignment generation', async () => {
  const context = setup(49); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper'] }); const paused = await context.service.pause({ sessionId: session.id, botId: 'helper' }); assert.equal(paused.workShares[0].status, 'PAUSED'); const resumed = await context.service.resume({ sessionId: session.id, botId: 'helper' }); assert.ok(resumed.generation > paused.generation); assert.ok(resumed.workShares.some(share => share.generation === resumed.generation && share.botId === 'helper'));
});

test('helper loss preserves verified output and redistributes only unfinished work', async () => {
  const context = setup(64, { ownerStone: 0 }); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper', 'helper2'] }); const helperShare = session.workShares.find(share => share.botId === 'helper'); await context.repositories.shares.update(helperShare.shareId, { ...helperShare, completed: 8, delivered: 8, credited: 8, status: 'PARTIAL' }); change(context.owner.adapter.items, 'stone', 8);
  const affected = await context.service.handleBotDeath('helper'); const recovered = affected[0]; const replacement = recovered.workShares.filter(share => share.generation === recovered.generation); assert.equal(recovered.progress.current, 8); assert.ok(replacement.every(share => share.botId === 'helper2')); assert.equal(replacement.reduce((total, share) => total + share.assigned, 0), 56);
});

test('different helpers execute shares concurrently without holding the session lock', async () => {
  const started = []; const releases = []; const context = setup(64, { ownerStone: 0, executorFactory: runtimes => ({ cancel: () => true, execute: task => new Promise(resolve => { started.push(task); releases.push(() => { change(runtimes[task.assignedBot].adapter.items, 'stone', task.input.count); resolve({ collected: task.input.count }); }); }) }) }); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper', 'helper2'] }); const running = session.workShares.map(share => context.service.executeShare({ sessionId: session.id, shareId: share.shareId })); await waitFor(() => started.length === 2, 100, 5); assert.deepEqual(started.map(task => task.assignedBot).sort(), ['helper', 'helper2']); await assert.rejects(context.service.rebalanceSession({ sessionId: session.id, reason: 'MANUAL_REBALANCE' }), /HELP_RECONCILIATION_REQUIRED/); releases.forEach(release => release()); await Promise.all(running);
});

test('pause cancels a running helper without waiting for its execution lock', async () => {
  const cancelled = []; let runningTaskId = null; const context = setup(49, { executorFactory: () => { const pending = new Map(); return { cancel: taskId => { cancelled.push(taskId); pending.get(taskId)?.(); return true; }, execute: task => new Promise((resolve, reject) => { runningTaskId = task.id; pending.set(task.id, () => reject(Object.assign(new Error('cancelled'), { code: 'CANCELLED' }))); }) }; } }); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper'] }); const execution = context.service.executeShare({ sessionId: session.id, shareId: session.workShares[0].shareId }); await waitFor(() => Boolean(runningTaskId), 100, 5); const paused = await context.service.pause({ sessionId: session.id, botId: 'helper' }); assert.equal(cancelled.length, 1); assert.equal(paused.workShares[0].status, 'PAUSED'); await assert.rejects(execution, /cancelled/);
});

test('large work shares run in verified 64-item batches until parent completion', async () => {
  const context = setup(162, { ownerStone: 34 }); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper'] }); let current = session; for (let batch = 0; batch < 2; batch++) { current = await context.service.executeShare({ sessionId: current.id, shareId: current.workShares.at(-1).shareId }); assert.equal(current.workShares.at(-1).completed, (batch + 1) * 64); current = await context.service.handoff({ sessionId: current.id, shareId: current.workShares.at(-1).shareId }); } assert.equal(current.status, 'COMPLETED'); assert.equal(context.parent.status, TaskStatus.COMPLETED);
});

test('a 300-item share resumes safely after restart between verified batches', async () => {
  const context = setup(334, { ownerStone: 34 }); let session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper'] }); session = await context.service.executeShare({ sessionId: session.id, shareId: session.workShares[0].shareId }); session = await context.service.handoff({ sessionId: session.id, shareId: session.workShares[0].shareId }); const restored = createHelpService({ repository: context.repositories.sessions, workShareRepository: context.repositories.shares, contributionRepository: context.repositories.contributions, bots: context.bots, fleetTransfer: context.fleetTransfer, logistics: context.logistics, goals: context.goals, executor: context.executor, events: context.events, maxHelpersPerSession: 4, minimumChunk: 4 }); await restored.initialize(); for (let batch = 0; batch < 4; batch++) { session = await restored.executeShare({ sessionId: session.id, shareId: session.workShares[0].shareId }); session = await restored.handoff({ sessionId: session.id, shareId: session.workShares[0].shareId }); } assert.equal(session.status, 'COMPLETED'); assert.equal(count(context.owner.adapter.items, 'stone'), 334);
});

test('worker capacity uses real slot fields including partial target stacks', () => {
  const context = setup(); context.helper.adapter.slotsUsed = 36; context.helper.adapter.slotsFree = 0; context.helper.adapter.capacityUnits = 0; const full = collectWorkerStates({ session: { id: 'session', goal: { item: 'stone' } }, shares: [{ shareId: 'share', botId: 'helper', role: 'HELPER', status: 'ASSIGNED', assigned: 16, completed: 0, delivered: 0, credited: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }], bots: context.bots, now: Date.now() })[0]; assert.equal(full.inventoryFreeSlots, 0); assert.equal(full.capacityUnits, 0); context.helper.adapter.slotsUsed = 35; context.helper.adapter.slotsFree = 1; context.helper.adapter.capacityUnits = 80; const partial = collectWorkerStates({ session: { id: 'session', goal: { item: 'stone' } }, shares: [{ shareId: 'share', botId: 'helper', role: 'HELPER', status: 'ASSIGNED', assigned: 16, completed: 0, delivered: 0, credited: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }], bots: context.bots, now: Date.now() })[0]; assert.equal(partial.inventoryFreeSlots, 1); assert.equal(partial.capacityUnits, 64);
});

test('target capacity ignores partial stacks of unrelated items', () => {
  const context = setup(); context.helper.adapter.slots = [{ name: 'stone', count: 60, stackSize: 64 }, { name: 'dirt', count: 1, stackSize: 64 }, null]; const state = collectWorkerStates({ session: { id: 'session', goal: { item: 'stone' } }, shares: [{ shareId: 'share', botId: 'helper', role: 'HELPER', status: 'ASSIGNED', assigned: 16, completed: 0, delivered: 0, credited: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }], bots: context.bots, now: Date.now() })[0]; assert.equal(state.capacityUnits, 68); context.helper.adapter.slots = [{ name: 'dirt', count: 1, stackSize: 64 }]; const full = collectWorkerStates({ session: { id: 'session', goal: { item: 'stone' } }, shares: [{ shareId: 'share', botId: 'helper', role: 'HELPER', status: 'ASSIGNED', assigned: 16, completed: 0, delivered: 0, credited: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }], bots: context.bots, now: Date.now() })[0]; assert.equal(full.capacityUnits, 0);
});

test('tool suitability enforces stone, iron, diamond, obsidian, and deepslate ore tiers', () => {
  const context = setup(); const share = item => ({ shareId: item, botId: 'helper', role: 'HELPER', status: 'ASSIGNED', assigned: 1, completed: 0, delivered: 0, credited: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); const state = item => collectWorkerStates({ session: { id: 'session', goal: { item } }, shares: [share(item)], bots: context.bots, now: Date.now() })[0]; context.helper.adapter.items = [{ name: 'wooden_pickaxe', count: 1 }]; assert.equal(state('stone').toolSuitable, true); assert.equal(state('iron_ore').toolSuitable, false); context.helper.adapter.items = [{ name: 'stone_pickaxe', count: 1 }]; assert.equal(state('deepslate_iron_ore').toolSuitable, true); assert.equal(state('diamond_ore').toolSuitable, false); context.helper.adapter.items = [{ name: 'iron_pickaxe', count: 1 }]; assert.equal(state('diamond_ore').toolSuitable, true); assert.equal(state('obsidian').toolSuitable, false); context.helper.adapter.items = [{ name: 'diamond_pickaxe', count: 1 }]; assert.equal(state('obsidian').toolSuitable, true);
});

test('stalled running helper is cancelled, reconciled, and only unfinished work is reassigned', async () => {
  let released = false; let rejectExecution; const context = setup(64, { ownerStone: 0, executorFactory: runtimes => { const running = {}; return { status: () => ({ running, queues: {} }), cancel: taskId => { released = true; delete running.helper; change(runtimes.helper.adapter.items, 'stone', 8); rejectExecution(Object.assign(new Error('stalled'), { code: 'CANCELLED' })); return true; }, execute: task => new Promise((resolve, reject) => { running[task.assignedBot] = task.id; rejectExecution = reject; }) }; } }); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper', 'helper2'] }); const helperShare = session.workShares.find(share => share.botId === 'helper'); const execution = context.service.executeShare({ sessionId: session.id, shareId: helperShare.shareId }); await waitFor(() => Boolean(rejectExecution), 100, 5); const recovered = await context.service.recoverStalledWorker({ sessionId: session.id, shareId: helperShare.shareId, botId: 'helper' }); assert.equal(released, true); assert.equal((await context.service.get(session.id)).workShares.find(share => share.shareId === helperShare.shareId).completed, 8); assert.equal(recovered.workShares.filter(share => share.generation === recovered.generation).reduce((total, share) => total + share.assigned, 0), 56); await assert.rejects(execution, /stalled/);
});

test('coordination monitor reports a failed session without rejecting its timer tick', async () => {
  const events = new EventBus(); const failures = []; events.subscribe('help.rebalance.failed', event => { failures.push(event.payload); }); const monitor = createCoordinationMonitor({ help: { list: async () => [{ id: 'session', parentTaskId: 'task', status: 'ACTIVE' }], stalledWorkers: async () => { throw new Error('monitor failure'); } }, events, intervalMs: 5000 }); await monitor.tick(); assert.equal(failures.length, 1); assert.match(failures[0].error.message, /monitor failure/); monitor.dispose();
});

test('stall detection requires no progress beyond the configured threshold and rebalance completion uses GoalService', async () => {
  const context = setup(64, { ownerStone: 0, coordination: { minRebalanceIntervalMs: 1, minimumTransferUnits: 4, minimumBenefitRatio: 0.15, maxRebalancesPerSession: 20, progressStallThresholdMs: 10 } }); const session = await context.service.create({ parentTaskId: context.parent.id, ownerBotId: 'owner', workers: ['helper'] }); const share = session.workShares[0]; await context.repositories.shares.update(share.shareId, { ...share, lastProgressAt: new Date(Date.now() - 20).toISOString() }); assert.equal((await context.service.stalledWorkers(session.id)).length, 1); change(context.owner.adapter.items, 'stone', 64); const complete = await context.service.rebalanceSession({ sessionId: session.id, reason: 'MANUAL_REBALANCE', rebalanceKey: 'complete-parent' }); assert.equal(complete.status, 'COMPLETED'); assert.equal(context.parent.status, TaskStatus.COMPLETED);
});

function runtime(id, stone, x) { return { id, status: 'READY', bot: { id }, options: { host: 'server', port: 25565 }, adapter: new BotAdapter([{ name: 'stone_pickaxe', count: 1 }, ...(stone ? [{ name: 'stone', count: stone }] : [])], { x, y: 64, z: 0 }) }; }
function count(items, name) { return items.filter(item => item.name === name).reduce((sum, item) => sum + item.count, 0); }
function change(items, name, amount) { const item = items.find(entry => entry.name === name); if (!item && amount > 0) items.push({ name, count: amount }); else if (item) { item.count += amount; if (item.count === 0) items.splice(items.indexOf(item), 1); } }
async function waitFor(predicate, maxAttempts, intervalMs) { for (let attempt = 0; attempt < maxAttempts; attempt++) { if (predicate()) return; await new Promise(resolveWait => setTimeout(resolveWait, intervalMs)); } throw new Error(`Condition was not met within ${maxAttempts * intervalMs}ms`); }
