import test from 'node:test';
import assert from 'node:assert/strict';
import { EventBus, MemoryRepository, createMemoryIntegrityService } from '../src/index.js';

function fixture(overrides = {}) { const events = new EventBus(); const candidates = new MemoryRepository(); const decisions = new MemoryRepository(); const recovery = new MemoryRepository(); const archives = []; const service = createMemoryIntegrityService({ repositories: { candidates, decisions, recovery }, events, governance: { record: async () => {}, archive: async (record, reason) => archives.push({ record, reason }) }, ...overrides }); return { service, events, candidates, decisions, recovery, archives }; }
function claim(overrides = {}) { return { claimKey: 'world:server:overworld:village:oak', layer: 'WORLD', value: { position: { x: 10, y: 64, z: 10 } }, visibility: 'HIVE', confidence: 0.8, directObservation: true, source: { id: 'bot-a', type: 'BOT_OBSERVATION', reliability: 0.8 }, confirmationCount: 1, observedAt: new Date().toISOString(), ...overrides }; }

test('deterministic conflict resolution chooses the more trustworthy fresh observation', async () => {
  const { service } = fixture(); await service.initialize(); const older = await service.submit(claim({ confidence: 0.75, source: { id: 'bot-old', type: 'BOT_OBSERVATION', reliability: 0.6 }, observedAt: '2026-01-01T00:00:00.000Z' })); const newer = await service.submit(claim({ value: { position: { x: 40, y: 64, z: 40 } }, confidence: 0.95, source: { id: 'bot-new', type: 'BOT_OBSERVATION', reliability: 0.95 } })); assert.equal(newer.status, 'AUTHORITATIVE'); assert.deepEqual(newer.value.position, { x: 40, y: 64, z: 40 }); const records = await service.candidates({ claimKey: newer.claimKey }); assert.equal(records.find(item => item.id === older.id).status, 'SUPERSEDED'); const decision = (await service.decisions()).find(item => item.candidateIds.length === 2); assert.equal(decision.winnerId, newer.id); assert.deepEqual(decision.factors, ['timestamp', 'confidence', 'directObservation', 'sourceReliability', 'confirmationCount', 'freshness']); service.dispose();
});

test('unverified candidate is rejected into bounded recovery and can be corrected', async () => {
  const { service } = fixture({ maxRecoveryAttempts: 2 }); await service.initialize(); const pending = await service.submit(claim({ directObservation: false, confirmationCount: 0, confidence: 0.5, source: { id: 'rumor', type: 'CHAT', reliability: 0.2 } })); assert.equal(pending.status, 'PENDING_VERIFICATION'); const rejected = await service.verify(pending.id, { passed: false, verifierId: 'bot-verifier', evidence: { observed: false } }); assert.equal(rejected.status, 'REJECTED'); const [recovery] = await service.recovery(); assert.equal(recovery.status, 'RETRY_REQUIRED'); const fixed = await service.retry(recovery.id, claim({ source: { id: 'bot-verifier', type: 'BOT_OBSERVATION', reliability: 0.9 } })); assert.equal(fixed.status, 'RECOVERED'); assert.equal((await service.status()).authoritative, 1); service.dispose();
});

test('visibility-aware retrieval enforces private and team boundaries with hard context caps', async () => {
  const { service } = fixture({ maxContextItems: 5, maxContextCharacters: 2500 }); await service.initialize(); await service.submit(claim({ claimKey: 'private', visibility: 'PRIVATE', ownerBotId: 'bot-a', source: { id: 'private-source', reliability: 0.9 } })); await service.submit(claim({ claimKey: 'team', visibility: 'TEAM', teamId: 'miners', source: { id: 'team-source', reliability: 0.9 } })); for (let index = 0; index < 6; index++) await service.submit(claim({ claimKey: `hive-${index}`, source: { id: `hive-source-${index}`, reliability: 0.9 } })); const outsider = await service.retrieve({ actorBotId: 'bot-b', teamId: 'scouts' }); assert.equal(outsider.some(item => item.claimKey === 'private' || item.claimKey === 'team'), false); assert.ok(outsider.length <= 5); assert.ok(JSON.stringify(outsider).length <= 2500); const owner = await service.retrieve({ actorBotId: 'bot-a', teamId: 'miners' }); assert.equal(owner.some(item => item.claimKey === 'private'), true); assert.equal(owner.some(item => item.claimKey === 'team'), true); service.dispose();
});

test('startup quarantines corrupt persisted candidates into recovery', async () => {
  const value = fixture(); await value.candidates.create({ id: 'corrupt', claimKey: '', layer: 'NOPE' }); const result = await value.service.initialize(); assert.equal(result.quarantined, 1); assert.equal((await value.candidates.list()).length, 0); assert.equal((await value.service.recovery())[0].status, 'QUARANTINED'); assert.equal(value.archives[0].reason, 'memory-integrity-corrupt'); value.service.dispose();
});

test('SYSTEM visibility requires direct observation and multiple confirmations', async () => {
  const { service } = fixture({ minimumConfirmations: 2 }); await service.initialize(); const pending = await service.submit(claim({ claimKey: 'system:critical', layer: 'SYSTEM', visibility: 'SYSTEM', directObservation: true, confirmationCount: 1 })); assert.equal(pending.status, 'PENDING_VERIFICATION'); const authoritative = await service.submit(claim({ claimKey: 'system:critical', layer: 'SYSTEM', visibility: 'SYSTEM', directObservation: true, confirmationCount: 2 })); assert.equal(authoritative.status, 'AUTHORITATIVE'); service.dispose();
});

test('invalid recovery is bounded and terminates in dead-letter', async () => {
  const { service } = fixture({ maxRecoveryAttempts: 2 }); await service.initialize(); const pending = await service.submit(claim({ directObservation: false, confirmationCount: 0, confidence: 0.2, source: { id: 'bad-source', reliability: 0.1 } })); await service.verify(pending.id, { passed: false, verifierId: 'verifier' }); const [recovery] = await service.recovery(); assert.equal((await service.retry(recovery.id, { layer: 'NOPE' })).status, 'RETRY_REQUIRED'); assert.equal((await service.retry(recovery.id, { layer: 'NOPE' })).status, 'DEAD_LETTER'); await assert.rejects(service.retry(recovery.id, claim()), /terminal/); assert.equal((await service.status()).deadLetters, 1); service.dispose();
});
