const state = { token: localStorage.getItem('minehive.token') ?? '', bots: [], goals: [], admins: [], health: null, ai: null, settings: null, autonomyObjectives: [], editorBotId: null, memoryBrowser: { offset: 0, limit: 50, loading: false, data: null }, recovery: { loading: false, data: null, timer: null }, polling: { timer: null, running: false, failures: 0 } };
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
$('#apiToken').value = state.token;

async function api(path, options = {}) {
  const headers = { ...(options.body ? { 'content-type': 'application/json' } : {}), ...(state.token ? { authorization: `Bearer ${state.token}` } : {}), ...options.headers };
  const response = await fetch(path, { ...options, headers, signal: options.signal ?? AbortSignal.timeout(15_000) }); const payload = await response.json().catch(() => ({}));
  if (!response.ok) { const error = new Error(payload.error?.message ?? `HTTP ${response.status}`); error.status = response.status; error.retryAfterMs = Math.max(0, Number(response.headers.get('retry-after') ?? 0) * 1000); throw error; } return payload.data ?? payload;
}
function toast(message, error = false) { const el = $('#toast'); el.textContent = message; el.className = `${error ? 'error ' : ''}show`; clearTimeout(toast.timer); toast.timer = setTimeout(() => { el.className = ''; }, 3500); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[char]); }
function position(bot) { const p = bot.runtime?.position; return p ? `${p.x.toFixed(1)}, ${p.y.toFixed(1)}, ${p.z.toFixed(1)}` : '—'; }
function online(bot) { return ['READY', 'ACTIVE', 'PAUSED'].includes(bot.status); }

async function refresh() {
  if (state.polling.running || document.hidden) return; state.polling.running = true;
  try {
    const snapshot = await api('/api/v1/dashboard/snapshot'); Object.assign(state, snapshot); render();
    state.polling.failures = 0; $('#connectionDot').style.background = '#77e39e'; $('#connectionText').textContent = 'Connected'; $('#lastUpdate').textContent = new Date().toLocaleTimeString();
  } catch (error) { state.polling.failures++; state.polling.retryAfterMs = error.retryAfterMs; $('#connectionDot').style.background = '#ff7474'; $('#connectionText').textContent = error.status === 429 ? 'Rate limited' : 'Disconnected'; $('#lastUpdate').textContent = error.message; }
  finally { state.polling.running = false; scheduleRefresh(); }
}
function scheduleRefresh() { clearTimeout(state.polling.timer); if (document.hidden) return; const backoff = Math.min(30_000, 3000 * (2 ** state.polling.failures)); const delay = Math.max(3000, state.polling.retryAfterMs ?? 0, backoff); state.polling.retryAfterMs = 0; state.polling.timer = setTimeout(refresh, delay); }
function render() {
  $('#statOnline').textContent = state.bots.filter(online).length; $('#statBots').textContent = state.bots.length;
  $('#statGoals').textContent = state.goals.filter(goal => goal.status === 'ACTIVE').length; $('#statHealth').textContent = state.health?.status ?? '—';
  $('#statAi').textContent = state.ai?.llm?.enabled ? state.ai.llm.provider : 'RULES'; $('#statAiModel').textContent = state.ai?.llm?.model ? `${state.ai.llm.model}${state.ai.llm.keyCount ? ` · key ${state.ai.llm.activeKey} · ready ${state.ai.llm.availableKeys}/${state.ai.llm.keyCount}` : ''}` : 'Deterministic fallback';
  const memory = state.health?.checks?.memory; $('#statMemory').textContent = memory?.count ?? 0; $('#statMemoryDetail').textContent = memory ? `Short ${memory.byType?.SHORT_TERM ?? 0} · Long ${memory.byType?.LONG_TERM ?? 0}` : 'Short 0 · Long 0'; $('#statHive').textContent = state.health?.checks?.hivemind?.activeMembers ?? 0; $('#statMl').textContent = state.health?.checks?.ml?.outcomeCount ?? 0; $('#statProcess').textContent = state.diagnostics ? `${state.diagnostics.rssMb} MB` : '—'; $('#statProcessHeap').textContent = state.diagnostics ? `Heap ${state.diagnostics.heapUsedMb} MB · uptime ${state.diagnostics.uptimeSeconds}s` : 'Runtime diagnostics';
  $('#statLogistics').textContent = state.logistics?.activeStorages ?? 0; $('#statLogisticsDetail').textContent = state.logistics ? `${state.logistics.stockItems} items · ${state.logistics.activeReservations} reserved` : 'Storage backbone';
  $('#statQueue').textContent = state.taskQueue?.queuedTasks ?? 0; $('#statQueueDetail').textContent = state.taskQueue ? `${state.taskQueue.activeBots} bots running · ${state.ai?.queuedOperations ?? 0} coordinator waiting` : 'Sequential per bot';
  $('#overviewBots').innerHTML = state.bots.length ? state.bots.map(botRow).join('') : empty('No bots registered');
  $('#goalList').innerHTML = state.goals.length ? state.goals.slice(-6).reverse().map(goal => `<div class="goal-row"><div><b>${escapeHtml(goal.description)}</b><small>${goal.progress}% · ${new Date(goal.updatedAt).toLocaleTimeString()}</small></div><span class="badge">${goal.status}</span></div>`).join('') : empty('No goals yet');
  $('#botManager').innerHTML = state.bots.length ? state.bots.map(botCard).join('') : empty('Add your first bot using the form');
  const classes = [...new Set(state.bots.map(bot => bot.metadata?.className).filter(Boolean))];
  replaceOptions($('#commandBot'), `<option value="scope:global">All bots · !global</option>${classes.map(name => `<option value="class:${escapeHtml(name)}">Class ${escapeHtml(name)} · !${escapeHtml(name)}</option>`).join('')}${state.bots.map(bot => `<option value="bot:${escapeHtml(bot.id)}">${escapeHtml(bot.name)} · !${escapeHtml(bot.metadata?.commandAlias ?? bot.name)} · ${bot.status}</option>`).join('')}`);
  $('#adminList').innerHTML = state.admins.length ? state.admins.map(admin => `<div class="admin-row"><div><b>${escapeHtml(admin.username)}</b><div class="source">${admin.source}</div></div>${admin.removable ? `<button class="button danger" data-remove-admin="${escapeHtml(admin.username)}">Remove</button>` : '<span class="badge">.env</span>'}</div>`).join('') : empty('No chat admins configured');
  renderSettings(); renderOpenBotInventory();
  renderCameras(); bindDynamic();
}
function renderSettings() {
  if (!state.settings) return; const llm = state.settings.llm; const autonomy = state.settings.autonomy; const acquisition = state.settings.acquisition ?? {};
  hydrateFormOnce($('#llmSettingsForm'), () => { $('#llmProvider').value = llm.provider ?? 'none'; $('#openRouterModel').value = llm.openrouter.model; $('#openRouterEndpoint').value = llm.openrouter.endpoint; $('#nvidiaNimModel').value = llm.nvidia.model; $('#nvidiaNimEndpoint').value = llm.nvidia.endpoint; });
  $('#llmSettingStatus').textContent = llm.status?.enabled ? `${llm.status.provider} · ${llm.status.model}` : 'disabled'; const keySummary = provider => provider.configuredKeys.map((configured, index) => `#${index + 1} ${configured ? 'configured' : 'empty'}`).join(' · '); $('#keyStatus').textContent = `OpenRouter: ${keySummary(llm.openrouter)}. NVIDIA: ${keySummary(llm.nvidia)}. Mengisi key baru hanya mengganti pool provider tersebut.`;
  hydrateCleanForm($('#logSettingsForm'), () => { $('#logLevel').value = state.settings.log.level; }); hydrateCleanForm($('#autonomySettingsForm'), () => { $('#autonomyEnabled').checked = autonomy.status === 'ACTIVE'; $('#autonomyInterval').value = autonomy.intervalMs; $('#autonomyBudget').value = autonomy.maxActionsPerHour; }); $('#autonomySettingStatus').textContent = autonomy.status;
  hydrateCleanForm($('#acquisitionSettingsForm'), () => {
    $('#acquisitionEnabled').checked = Boolean(acquisition.enabled);
    $('#acquisitionMaxDepth').value = acquisition.maxDepth ?? 8;
    $('#acquisitionMaxSubtasks').value = acquisition.maxSubtasks ?? 32;
    $('#acquisitionMaxAttempts').value = acquisition.maxAttempts ?? 3;
    $('#acquisitionMaxDistance').value = acquisition.maxDistance ?? 2000;
    $('#acquisitionStorageFirst').checked = Boolean(acquisition.storageFirst);
    $('#acquisitionAllowFleet').checked = Boolean(acquisition.allowFleet);
    $('#acquisitionAllowCraft').checked = Boolean(acquisition.allowCraft);
    $('#acquisitionAllowSmelt').checked = Boolean(acquisition.allowSmelt);
    $('#acquisitionAllowCollect').checked = Boolean(acquisition.allowCollect);
    $('#acquisitionAllowPartial').checked = Boolean(acquisition.allowPartial);
    $('#acquisitionToolPreservation').checked = Boolean(acquisition.toolPreservation);
  });
  $('#acquisitionSettingStatus').textContent = acquisition.enabled ? 'ENABLED' : 'DISABLED';
  $('#autonomyObjectives').innerHTML = state.autonomyObjectives.length ? state.autonomyObjectives.map(objective => `<div class="goal-row"><div><b>${escapeHtml(objective.text)}</b><small>${escapeHtml(objective.selector)} · runs ${objective.runs} · success ${objective.successes} · failed ${objective.failures}</small></div><button class="button danger" data-remove-objective="${escapeHtml(objective.id)}">Remove</button></div>`).join('') : empty('No autonomous objectives');
}
function replaceOptions(select, html) { const selected = select.value; select.innerHTML = html; if ([...select.options].some(option => option.value === selected)) select.value = selected; }
function hydrateCleanForm(form, operation) { if (form.dataset.dirty !== 'true') operation(); }
function hydrateFormOnce(form, operation) { if (form.dataset.hydrated === 'true') return; const hasDraft = form.dataset.dirty === 'true' || [...form.querySelectorAll('input[type="password"]')].some(input => input.value); if (!hasDraft) operation(); form.dataset.hydrated = 'true'; form.dataset.dirty = hasDraft ? 'true' : 'false'; }
function trackDirty(form) { const dirty = () => { form.dataset.dirty = 'true'; }; form.addEventListener('input', dirty); form.addEventListener('change', dirty); }
function markClean(form) { form.dataset.dirty = 'false'; }
function resetHydration(form) { form.dataset.hydrated = 'false'; form.dataset.dirty = 'false'; }
function botRow(bot) { return `<div class="bot-row"><div class="bot-main"><i class="status-dot ${bot.status.toLowerCase()}"></i><div><b>${escapeHtml(bot.name)}</b><small>${bot.status} · ${position(bot)}</small></div></div><span class="badge">HP ${bot.runtime?.health ?? '—'}</span></div>`; }
function botCard(bot) { const ready = online(bot); const activeCamera = bot.runtime?.camera?.active; const inventory = bot.runtime?.inventorySummary ?? []; const preview = inventory.length ? inventory.slice(0, 4).map(item => `${escapeHtml(item.name)}:${item.count}`).join(' · ') : 'Inventory empty'; const cameraButtons = activeCamera ? `<button class="button secondary" data-camera="stop" data-bot="${bot.id}">Stop viewer</button>` : `<button class="button secondary" data-camera="start" data-camera-mode="first_person" data-bot="${bot.id}" ${ready ? '' : 'disabled'}>First person</button><button class="button secondary" data-camera="start" data-camera-mode="surrounding" data-bot="${bot.id}" ${ready ? '' : 'disabled'}>3D area</button>`; return `<article class="bot-card"><div class="bot-card-head"><div><h3>${escapeHtml(bot.name)}</h3><small>!${escapeHtml(bot.metadata?.commandAlias ?? bot.name)} · class !${escapeHtml(bot.metadata?.className ?? 'worker')}</small></div><i class="status-dot ${bot.status.toLowerCase()}"></i></div><dl><div><dt>Status</dt><dd>${bot.status}</dd></div><div><dt>Health / food</dt><dd>${bot.runtime?.health ?? '—'} / ${bot.runtime?.food ?? '—'}</dd></div><div><dt>Position</dt><dd>${position(bot)}</dd></div><div><dt>Dimension</dt><dd>${bot.runtime?.dimension ?? '—'}</dd></div></dl><div class="inventory-preview"><b>Inventory:</b> ${preview}${inventory.length > 4 ? ` · +${inventory.length - 4} stacks` : ''}</div><div class="actions"><button class="button primary" data-bot-action="${ready ? 'stop' : 'start'}" data-bot="${bot.id}">${ready ? 'Disconnect' : 'Join server'}</button>${cameraButtons}<button class="button secondary" data-edit-bot="${bot.id}">Edit & inventory</button><button class="button danger" data-delete-bot="${bot.id}">Delete</button></div></article>`; }
function renderCameras() {
  const wall = $('#cameraWall'); const active = state.bots.filter(bot => bot.runtime?.camera?.active && bot.runtime.camera.port); const ids = new Set(active.map(bot => bot.id));
  wall.querySelectorAll('[data-camera-card]').forEach(card => { if (!ids.has(card.dataset.cameraCard)) card.remove(); }); wall.querySelector('.camera-empty')?.remove();
  for (const bot of active) {
    if (wall.querySelector(`[data-camera-card="${CSS.escape(bot.id)}"]`)) continue;
    const card = document.createElement('article'); card.className = 'camera-card'; card.dataset.cameraCard = bot.id;
    const mode = bot.runtime.camera.mode === 'surrounding' ? '3D AREA' : 'FIRST PERSON'; const warning = bot.runtime.camera.versionSupported === false ? `<span class="camera-warning">${escapeHtml(bot.runtime.camera.version)} → renderer ${escapeHtml(bot.runtime.camera.renderVersion)}</span>` : `<span class="camera-live">${mode}</span>`;
    card.innerHTML = `<header><div><b>◉ ${escapeHtml(bot.name)}</b>${warning}</div><button class="button danger" data-camera="stop" data-bot="${escapeHtml(bot.id)}">Stop</button></header><div class="camera-loading">Connecting to camera…</div><iframe loading="eager" title="Camera ${escapeHtml(bot.name)}" src="http://${location.hostname}:${bot.runtime.camera.port}"></iframe>`;
    const frame = card.querySelector('iframe'); frame.onload = () => card.querySelector('.camera-loading')?.remove(); wall.append(card);
  }
  if (!active.length && !wall.querySelector('.camera-empty')) wall.innerHTML = '<div class="camera-empty">Start a camera from the Bots menu to show it here.</div>';
}
function empty(text) { return `<div class="camera-empty" style="padding:28px">${text}</div>`; }

function bindDynamic() {
  $$('[data-bot-action]').forEach(button => button.onclick = () => performBot(button.dataset.bot, button.dataset.botAction));
  $$('[data-camera]').forEach(button => button.onclick = () => camera(button.dataset.bot, button.dataset.camera, button.dataset.cameraMode));
  $$('[data-delete-bot]').forEach(button => button.onclick = () => deleteBot(button.dataset.deleteBot));
  $$('[data-edit-bot]').forEach(button => button.onclick = () => editBot(button.dataset.editBot));
  $$('[data-remove-admin]').forEach(button => button.onclick = () => removeAdmin(button.dataset.removeAdmin));
  $$('[data-remove-objective]').forEach(button => button.onclick = () => removeObjective(button.dataset.removeObjective));
}
async function performBot(id, action) { try { await api(`/api/v1/bots/${id}/${action}`, { method: 'POST' }); toast(action === 'start' ? 'Bot is joining the server' : 'Bot disconnected'); await refresh(); } catch (error) { toast(error.message, true); } }
async function camera(id, action, mode) { try { await api(`/api/v1/bots/${id}/camera/${action}`, { method: 'POST', body: JSON.stringify(mode ? { mode } : {}) }); toast(action === 'start' ? `${mode === 'surrounding' ? '3D area' : 'First-person viewer'} started` : 'Viewer stopped'); await refresh(); if (action === 'start') showView('cameras'); } catch (error) { toast(error.message, true); } }
async function deleteBot(id) { if (!confirm('Disconnect and permanently remove this bot profile?')) return; try { await api(`/api/v1/bots/${id}`, { method: 'DELETE' }); toast('Bot removed'); await refresh(); } catch (error) { toast(error.message, true); } }
function editBot(id) { const bot = state.bots.find(item => item.id === id); if (!bot) return; const profile = bot.profile ?? {}; state.editorBotId = id; $('#editBotId').value = bot.id; $('#editBotName').value = profile.name ?? bot.name; $('#editBotUsername').value = profile.username ?? bot.name; $('#editBotHost').value = profile.host ?? 'localhost'; $('#editBotPort').value = profile.port ?? 25565; $('#editBotAuth').value = profile.auth ?? 'offline'; $('#editBotVersion').value = profile.version ?? ''; $('#editBotAlias').value = bot.metadata?.commandAlias ?? bot.name; $('#editBotClass').value = bot.metadata?.className ?? 'worker'; $('#editBotAutoConnect').checked = Boolean(profile.autoConnect); renderBotInventory(bot); $('#botEditor').showModal(); }
function renderOpenBotInventory() { if (!state.editorBotId || !$('#botEditor').open) return; const bot = state.bots.find(item => item.id === state.editorBotId); if (bot) renderBotInventory(bot); }
function renderBotInventory(bot) { const inventory = bot.runtime?.inventorySummary ?? []; $('#editBotTitle').textContent = `${bot.name} · ${bot.status}`; $('#editBotInventory').innerHTML = inventory.length ? inventory.map(item => `<div class="inventory-item"><span>${escapeHtml(item.name)}</span><b>${item.count}</b></div>`).join('') : empty('Inventory empty or bot offline'); $('#editBotInventoryUpdated').textContent = `Live · ${new Date(bot.runtime?.timestamp ?? Date.now()).toLocaleTimeString()}`; $('#editBotHint').textContent = online(bot) ? 'Nama tampilan, alias, kelompok, dan auto-connect dapat diubah sekarang. Disconnect bot sebelum mengganti username, server, authentication, atau protocol.' : 'Semua konfigurasi dapat diedit saat bot offline.'; }
async function removeAdmin(username) { try { await api(`/api/v1/admins/${encodeURIComponent(username)}`, { method: 'DELETE' }); toast('Admin removed'); await refresh(); } catch (error) { toast(error.message, true); } }
async function removeObjective(id) { try { await api(`/api/v1/autonomy/objectives/${encodeURIComponent(id)}`, { method: 'DELETE' }); toast('Autonomy objective removed'); await refresh(); } catch (error) { toast(error.message, true); } }

$('#botForm').onsubmit = async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); data.port = Number(data.port); data.autoConnect = data.autoConnect === 'on'; if (!data.version) delete data.version; try { const bot = await api('/api/v1/bots', { method: 'POST', body: JSON.stringify(data) }); toast(`Bot ${bot.name} added`); event.target.reset(); await refresh(); } catch (error) { toast(error.message, true); } };
$('#closeBotEditor').onclick = () => $('#botEditor').close(); $('#botEditor').addEventListener('close', () => { state.editorBotId = null; });
$('#botEditorForm').onsubmit = async event => { event.preventDefault(); const id = $('#editBotId').value; const input = { name: $('#editBotName').value.trim(), username: $('#editBotUsername').value.trim(), host: $('#editBotHost').value.trim(), port: Number($('#editBotPort').value), auth: $('#editBotAuth').value, version: $('#editBotVersion').value.trim() || null, commandAlias: $('#editBotAlias').value.trim(), className: $('#editBotClass').value.trim(), autoConnect: $('#editBotAutoConnect').checked }; try { await api(`/api/v1/bots/${id}`, { method: 'PATCH', body: JSON.stringify(input) }); $('#botEditor').close(); toast('Bot configuration saved'); await refresh(); } catch (error) { toast(error.message, true); } };
$('#adminForm').onsubmit = async event => { event.preventDefault(); const username = new FormData(event.target).get('username'); try { await api('/api/v1/admins', { method: 'POST', body: JSON.stringify({ username }) }); event.target.reset(); toast('Admin added'); await refresh(); } catch (error) { toast(error.message, true); } };
$('#llmSettingsForm').onsubmit = async event => { event.preventDefault(); const openRouterApiKeys = [$('#openRouterKey1').value.trim(), $('#openRouterKey2').value.trim(), $('#openRouterKey3').value.trim()].filter(Boolean); const nvidiaApiKeys = [$('#nvidiaKey1').value.trim(), $('#nvidiaKey2').value.trim(), $('#nvidiaKey3').value.trim()].filter(Boolean); const input = { provider: $('#llmProvider').value, openRouterModel: $('#openRouterModel').value.trim(), openRouterEndpoint: $('#openRouterEndpoint').value.trim(), nvidiaModel: $('#nvidiaNimModel').value.trim(), nvidiaEndpoint: $('#nvidiaNimEndpoint').value.trim(), ...(openRouterApiKeys.length ? { openRouterApiKeys } : {}), ...(nvidiaApiKeys.length ? { nvidiaApiKeys } : {}) }; try { await api('/api/v1/settings/llm', { method: 'PATCH', body: JSON.stringify(input) }); for (const id of ['#openRouterKey1', '#openRouterKey2', '#openRouterKey3', '#nvidiaKey1', '#nvidiaKey2', '#nvidiaKey3']) $(id).value = ''; markClean(event.target); toast('LLM runtime settings applied'); await refresh(); } catch (error) { toast(error.message, true); } };
$('#autonomySettingsForm').onsubmit = async event => { event.preventDefault(); const input = { enabled: $('#autonomyEnabled').checked, intervalMs: Number($('#autonomyInterval').value), maxActionsPerHour: Number($('#autonomyBudget').value) }; try { await api('/api/v1/settings/autonomy', { method: 'PATCH', body: JSON.stringify(input) }); markClean(event.target); toast('Autonomy settings applied'); await refresh(); } catch (error) { toast(error.message, true); } };
$('#autonomyObjectiveForm').onsubmit = async event => { event.preventDefault(); const input = { text: $('#autonomyObjective').value.trim(), selector: $('#autonomySelector').value.trim() }; try { await api('/api/v1/autonomy/objectives', { method: 'POST', body: JSON.stringify(input) }); $('#autonomyObjective').value = ''; toast('Autonomy objective added'); await refresh(); } catch (error) { toast(error.message, true); } };
$('#logSettingsForm').onsubmit = async event => { event.preventDefault(); try { await api('/api/v1/settings/log', { method: 'PATCH', body: JSON.stringify({ level: $('#logLevel').value }) }); markClean(event.target); toast('Runtime log level applied'); await refresh(); await loadRuntimeLogs(); } catch (error) { toast(error.message, true); } };
$('#acquisitionSettingsForm').onsubmit = async event => { event.preventDefault(); const input = { enabled: $('#acquisitionEnabled').checked, maxDepth: Number($('#acquisitionMaxDepth').value), maxSubtasks: Number($('#acquisitionMaxSubtasks').value), maxAttempts: Number($('#acquisitionMaxAttempts').value), maxDistance: Number($('#acquisitionMaxDistance').value), storageFirst: $('#acquisitionStorageFirst').checked, allowFleet: $('#acquisitionAllowFleet').checked, allowCraft: $('#acquisitionAllowCraft').checked, allowSmelt: $('#acquisitionAllowSmelt').checked, allowCollect: $('#acquisitionAllowCollect').checked, allowPartial: $('#acquisitionAllowPartial').checked, toolPreservation: $('#acquisitionToolPreservation').checked }; try { await api('/api/v1/settings/acquisition', { method: 'PATCH', body: JSON.stringify(input) }); markClean(event.target); toast('Acquisition settings applied'); await refresh(); } catch (error) { toast(error.message, true); } };
$('#memorySettingsForm').onsubmit = async event => { event.preventDefault(); const input = { maxRecords: Number($('#memoryMaxRecords').value), shortTermMaxRecords: Number($('#memoryShortLimit').value), shortTermTtlMs: Number($('#memoryShortTtl').value), promotionAccesses: Number($('#memoryPromotionAccesses').value), promotionImportance: Number($('#memoryPromotionImportance').value), consolidationIntervalMs: Number($('#memoryConsolidationInterval').value) }; try { await api('/api/v1/settings/memory', { method: 'PATCH', body: JSON.stringify(input) }); markClean(event.target); toast('Memory runtime settings applied'); await loadMemory(); } catch (error) { toast(error.message, true); } };
$('#recoverySettingsForm').onsubmit = async event => { event.preventDefault(); const input = { enabled: $('#recoveryEnabled').checked, maxAttempts: Number($('#recoveryMaxAttempts').value), minScore: Number($('#recoveryMinScore').value), optionalScore: Number($('#recoveryOptionalScore').value), urgentScore: Number($('#recoveryUrgentScore').value), despawnTicks: Number($('#recoveryDespawnTicks').value), safetyMarginTicks: Number($('#recoverySafetyMarginTicks').value), maxDistance: Number($('#recoveryMaxDistance').value), dangerLimit: Number($('#recoveryDangerLimit').value) }; try { await api('/api/v1/settings/recovery', { method: 'PATCH', body: JSON.stringify(input) }); markClean(event.target); toast('Death recovery settings applied'); await loadRecovery(); } catch (error) { toast(error.message, true); } };
$('#commandForm').onsubmit = async event => { event.preventDefault(); await executeCommand($('#commandBot').value, $('#commandInput').value); };
$('#aiForm').onsubmit = async event => { event.preventDefault(); const text = $('#aiInput').value.trim(); if (!text) return; log(`> AI ${$('#commandBot').value}: ${text}`); try { const result = await api('/api/v1/ai/command', { method: 'POST', body: JSON.stringify({ text, selector: selectorForApi($('#commandBot').value) }) }); log(JSON.stringify(result, null, 2)); await refresh(); } catch (error) { log(`AI ERROR: ${error.message}`, true); } };
$$('.quick-commands button').forEach(button => button.onclick = () => { $('#commandInput').value = button.dataset.command; $('#commandInput').focus(); });
async function executeCommand(target, text) {
  const [command, ...args] = text.trim().split(/\s+/); let action = command; let input = {};
  if (['collect', 'craft', 'smelt', 'cook', 'masak', 'lebur', 'survey', 'scan', 'jelajah', 'eksplorasi', 'register_chest', 'daftar_chest', 'store', 'simpan', 'retrieve', 'withdraw', 'ambil_chest', 'stock', 'stok', 'farm', 'farming', 'deforest', 'reforest', 'guard', 'combat', 'meat', 'remember', 'place', 'tebang', 'reboisasi'].includes(command)) { log(`> coordinator ${target}: ${text}`); try { const result = await api('/api/v1/ai/command', { method: 'POST', body: JSON.stringify({ text, selector: selectorForApi(target) }) }); log(JSON.stringify(result, null, 2)); await refresh(); } catch (error) { log(`COORDINATOR ERROR: ${error.message}`, true); } return; }
  if (command === 'status' || command === 'inventory') action = 'observe';
  else if (command === 'goto') { action = 'navigate'; input = { x: Number(args[0]), y: Number(args[1]), z: Number(args[2]) }; }
  else if (command === 'follow') input = { username: args[0] };
  else if (command === 'come') input = { username: args[0] };
  else if (command === 'sethome') { action = 'sethome'; input = { name: args[0] ?? 'home' }; }
  else if (command === 'home') input = { name: args[0] ?? 'home' };
  else if (command === 'chat') input = { message: args.join(' ') };
  else if (command !== 'stop' && command !== 'observe') return log(`Unknown command: ${command}`, true);
  const targets = target === 'scope:global' ? state.bots : target.startsWith('class:') ? state.bots.filter(bot => bot.metadata?.className === target.slice(6)) : state.bots.filter(bot => bot.id === target.slice(4));
  if (!targets.length) return log('No bots match the selected target', true);
  log(`> ${target}: ${text}`); const results = await Promise.allSettled(targets.map(bot => api(`/api/v1/bots/${bot.id}/actions/${action}`, { method: 'POST', body: JSON.stringify(input) })));
  results.forEach((result, index) => log(`${targets[index].name}: ${result.status === 'fulfilled' ? JSON.stringify(result.value) : `ERROR ${result.reason.message}`}`, result.status === 'rejected')); await refresh();
}
function selectorForApi(target) { return target === 'scope:global' ? 'global' : target.startsWith('class:') ? target : `bot:${state.bots.find(bot => bot.id === target.slice(4))?.metadata?.commandAlias ?? target.slice(4)}`; }
function log(message, error = false) { const output = $('#commandLog'); output.textContent += `\n[${new Date().toLocaleTimeString()}] ${message}`; output.scrollTop = output.scrollHeight; if (error) toast(message, true); }
$('#clearLog').onclick = () => { $('#commandLog').textContent = 'Log cleared.'; }; $('#refreshBots').onclick = refresh;
$('#refreshRuntimeLogs').onclick = loadRuntimeLogs;
$('#refreshLogistics').onclick = loadLogistics;
$('#refreshRecovery').onclick = loadRecovery;
$('#refreshMemory').onclick = loadMemory;
$('#consolidateMemory').onclick = async () => { try { const result = await api('/api/v1/memory/consolidate', { method: 'POST' }); toast(`Consolidation complete · ${result.promoted ?? 0} promoted · ${result.forgotten ?? 0} forgotten`); await loadMemory(); } catch (error) { toast(error.message, true); } };
$('#memoryFilterForm').onsubmit = event => { event.preventDefault(); void reloadMemoryFromStart(); };
$('#memoryPrevious').onclick = () => { state.memoryBrowser.offset = Math.max(0, state.memoryBrowser.offset - state.memoryBrowser.limit); void loadMemory(); };
$('#memoryNext').onclick = () => { if (!state.memoryBrowser.data?.hasMore) return; state.memoryBrowser.offset += state.memoryBrowser.limit; void loadMemory(); };
$('#memoryList').onclick = event => { const button = event.target.closest('[data-delete-memory]'); if (button) void deleteMemoryRecord(button.dataset.memoryCategory, button.dataset.memoryId, button); };
$('#logisticsStorages').onclick = event => { const button = event.target.closest('[data-rename-storage]'); if (button) void renameStorage(button.dataset.storageId, button.dataset.storageName, button); };
$('#resetSettings').onclick = async () => { if (!confirm('Reset LLM, runtime keys, log level, autonomy, recovery, and memory lifecycle settings to startup configuration? Bot profiles, admins, memory records, database, and API token will be preserved.')) return; try { const result = await api('/api/v1/settings/reset', { method: 'POST' }); resetHydration($('#llmSettingsForm')); for (const form of [$('#autonomySettingsForm'), $('#logSettingsForm'), $('#memorySettingsForm'), $('#recoverySettingsForm')]) markClean(form); toast(`Runtime settings reset · ${result.preserved.join(', ')} preserved`); await refresh(); if ($('#memory').classList.contains('active')) await loadMemory(); if ($('#recovery').classList.contains('active')) await loadRecovery(); } catch (error) { toast(error.message, true); } };
$('#saveToken').onclick = () => { state.token = $('#apiToken').value.trim(); localStorage.setItem('minehive.token', state.token); toast('API token saved in this browser'); refresh(); };
$$('.nav').forEach(button => button.onclick = () => showView(button.dataset.view)); $$('.goto').forEach(button => button.onclick = () => showView(button.dataset.target));
function showView(id) { clearTimeout(state.recovery.timer); $$('.view').forEach(view => view.classList.toggle('active', view.id === id)); $$('.nav').forEach(nav => nav.classList.toggle('active', nav.dataset.view === id)); $('#pageTitle').textContent = ({ overview: 'System overview', bots: 'Bots & server join', cameras: 'Live camera wall', commands: 'Command center', logistics: 'Storage & logistics', recovery: 'Intelligent death recovery', memory: 'Shared memory', admins: 'Admin access', settings: 'System settings' })[id]; if (id === 'settings') void loadRuntimeLogs(); if (id === 'logistics') void loadLogistics(); if (id === 'recovery') void loadRecovery(); if (id === 'memory') void loadMemory(); }
async function loadRuntimeLogs() { try { const [records, files] = await Promise.all([api('/api/v1/settings/logs?limit=150'), api('/api/v1/settings/log-files')]); $('#runtimeLogs').textContent = records.length ? records.map(record => JSON.stringify(record)).join('\n') : 'No runtime logs available.'; $('#runtimeLogs').scrollTop = $('#runtimeLogs').scrollHeight; $('#savedLogFiles').innerHTML = files.length ? files.map(file => `<button class="button secondary" data-saved-log="${escapeHtml(file.name)}">${file.active ? '● ' : ''}${escapeHtml(new Date(file.modifiedAt).toLocaleString())} · ${Math.ceil(file.size / 1024)} KB</button>`).join('') : '<span class="hint">Belum ada saved log.</span>'; $$('[data-saved-log]').forEach(button => button.onclick = () => loadSavedLog(button.dataset.savedLog)); } catch (error) { $('#runtimeLogs').textContent = `ERROR: ${error.message}`; } }
async function loadSavedLog(name) { try { const records = await api(`/api/v1/settings/log-files/${encodeURIComponent(name)}?limit=1000`); $('#runtimeLogs').textContent = records.length ? records.map(record => JSON.stringify(record)).join('\n') : 'Saved log is empty.'; $('#runtimeLogs').scrollTop = $('#runtimeLogs').scrollHeight; } catch (error) { $('#runtimeLogs').textContent = `ERROR: ${error.message}`; } }
async function loadLogistics() {
  try {
    const [status, storages, reservations, transfers, timeline, locks] = await Promise.all([api('/api/v1/logistics/status'), api('/api/v1/logistics/storages'), api('/api/v1/logistics/reservations'), api('/api/v1/logistics/transfers'), api('/api/v1/logistics/timeline?limit=100'), api('/api/v1/logistics/locks')]);
    $('#logisticsActive').textContent = status.activeReservations; $('#logisticsInFlight').textContent = status.inFlightTransfers; $('#logisticsRecovery').textContent = status.recoveryRequired; $('#logisticsLockCount').textContent = status.activeLocks;
    $('#logisticsStorages').innerHTML = storages.length ? storages.map(storage => `<div class="goal-row"><div><b>${escapeHtml(storage.name)}</b><small>${escapeHtml(storage.kind)} · ${storage.position.x}, ${storage.position.y}, ${storage.position.z} · ${storage.occupiedSlots}/${storage.capacitySlots} slots</small><small>${storage.availableInventory.map(item => `${escapeHtml(item.name)}:${item.available}${item.reserved ? ` (${item.reserved} reserved)` : ''}`).join(' · ') || 'empty'}</small></div><div class="actions"><span class="badge">${storage.status}</span><button class="button secondary" type="button" data-rename-storage data-storage-id="${escapeHtml(storage.id)}" data-storage-name="${escapeHtml(storage.name)}">Rename</button></div></div>`).join('') : empty('No storage registered. Use register_chest near a chest or barrel.');
    $('#logisticsReservations').innerHTML = reservations.length ? reservations.slice().reverse().map(reservation => `<div class="goal-row"><div><b>${escapeHtml(reservation.item)} × ${reservation.count}</b><small>${escapeHtml(reservation.requesterBotId)} · expires ${new Date(reservation.expiresAt).toLocaleString()}</small></div><span class="badge">${reservation.status}</span></div>`).join('') : empty('No stock reservations');
    $('#logisticsTransfers').innerHTML = transfers.length ? transfers.slice().reverse().map(transfer => `<div class="goal-row"><div><b>${transfer.direction} ${escapeHtml(transfer.item)} × ${transfer.requestedCount}</b><small>${escapeHtml(transfer.botId)} ↔ ${escapeHtml(transfer.storageName)} · ${transfer.failure ? `${escapeHtml(transfer.failure.code)}: ${escapeHtml(transfer.failure.message)}` : `${transfer.transferredCount}/${transfer.requestedCount} verified`}</small></div><span class="badge">${transfer.status}</span></div>`).join('') : empty('No transactional transfers');
    $('#logisticsTimeline').innerHTML = timeline.length ? timeline.map(entry => `<div class="goal-row"><div><b>${escapeHtml(entry.entityType)} · ${escapeHtml(entry.state)}</b><small>${escapeHtml(entry.item)} · ${escapeHtml(entry.botId)} · ${new Date(entry.at).toLocaleString()}</small></div></div>`).join('') : empty('No lifecycle events');
    $('#logisticsLocks').innerHTML = locks.length ? locks.map(lock => `<div class="goal-row"><div><b>${escapeHtml(lock.key)}</b><small>${escapeHtml(lock.owner)} · expires ${new Date(lock.expiresAt).toLocaleString()}</small></div><span class="badge">LOCKED</span></div>`).join('') : empty('No active storage locks');
  } catch (error) { $('#logisticsStorages').innerHTML = empty(`ERROR: ${escapeHtml(error.message)}`); }
}

async function renameStorage(id, currentName, button) { const name = prompt(`Rename storage "${currentName}"`, currentName); if (name === null || name.trim() === currentName) return; button.disabled = true; try { await api(`/api/v1/logistics/storages/${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify({ name: name.trim() }) }); toast(`Storage renamed to ${name.trim()}`); await loadLogistics(); await refresh(); } catch (error) { button.disabled = false; toast(error.message, true); } }

function requireRecoveryRecord(value, label) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`Recovery dashboard ${label} must be an object`); return value; }
function requireRecoveryNumber(record, field, label) { const value = record[field]; if (typeof value !== 'number' || !Number.isFinite(value)) throw new TypeError(`Recovery dashboard ${label}.${field} must be a finite number`); return value; }
function validateRecoveryDashboard(value) {
  const dashboard = requireRecoveryRecord(value, 'response'); const metrics = requireRecoveryRecord(dashboard.metrics, 'metrics'); const settings = requireRecoveryRecord(dashboard.settings, 'settings');
  if (!Array.isArray(dashboard.jobs)) throw new TypeError('Recovery dashboard jobs must be an array');
  if (!Array.isArray(dashboard.timeline)) throw new TypeError('Recovery dashboard timeline must be an array');
  for (const [index, job] of dashboard.jobs.entries()) requireRecoveryRecord(job, `jobs[${index}]`);
  for (const [index, entry] of dashboard.timeline.entries()) requireRecoveryRecord(entry, `timeline[${index}]`);
  for (const field of ['activeJobs', 'urgentRecoveries', 'recoveredItems', 'permanentLoss', 'ignoredJunk', 'successRate']) requireRecoveryNumber(metrics, field, 'metrics');
  if (typeof settings.enabled !== 'boolean') throw new TypeError('Recovery dashboard settings.enabled must be a boolean');
  for (const field of ['maxAttempts', 'minScore', 'optionalScore', 'urgentScore', 'despawnTicks', 'safetyMarginTicks', 'maxDistance', 'dangerLimit']) requireRecoveryNumber(settings, field, 'settings');
  if (typeof dashboard.status !== 'string' && (!dashboard.status || typeof dashboard.status !== 'object' || Array.isArray(dashboard.status))) throw new TypeError('Recovery dashboard status must be a string or object');
  return { metrics, jobs: dashboard.jobs, timeline: dashboard.timeline, settings, status: dashboard.status };
}
function recoveryViewActive() { return $('#recovery').classList.contains('active') && !document.hidden; }
function scheduleRecoveryPoll(delayMs) { clearTimeout(state.recovery.timer); if (recoveryViewActive()) state.recovery.timer = setTimeout(loadRecovery, delayMs); }
async function loadRecovery() {
  if (state.recovery.loading || !recoveryViewActive()) return; state.recovery.loading = true; if (!state.recovery.data) { $('#recoverySystemStatus').textContent = 'LOADING'; $('#recoveryJobs').innerHTML = empty('Loading recovery jobs…'); }
  try { const data = validateRecoveryDashboard(await api('/api/v1/recovery/dashboard')); state.recovery.data = data; renderRecovery(data); }
  catch (error) { $('#recoverySystemStatus').textContent = 'ERROR'; $('#recoveryJobs').innerHTML = empty(`ERROR: ${escapeHtml(error.message)}`); $('#recoveryTimeline').innerHTML = empty(`ERROR: ${escapeHtml(error.message)}`); }
  finally { state.recovery.loading = false; scheduleRecoveryPoll(5_000); }
}
function renderRecovery(data) {
  const metrics = data.metrics; $('#recoveryActiveJobs').textContent = formatRecoveryCount(metrics.activeJobs); $('#recoveryUrgentRecoveries').textContent = formatRecoveryCount(metrics.urgentRecoveries); $('#recoveryRecoveredItems').textContent = formatRecoveryCount(metrics.recoveredItems); $('#recoveryPermanentLoss').textContent = formatRecoveryCount(metrics.permanentLoss); $('#recoveryIgnoredJunk').textContent = formatRecoveryCount(metrics.ignoredJunk); $('#recoverySuccessRate').textContent = formatRecoveryRate(metrics.successRate);
  const status = recoveryStatusText(data.status, data.settings.enabled); $('#recoverySystemStatus').textContent = status; $('#recoverySettingStatus').textContent = data.settings.enabled ? 'ENABLED' : 'DISABLED'; $('#recoveryJobCount').textContent = `${data.jobs.length} ${data.jobs.length === 1 ? 'job' : 'jobs'}`;
  $('#recoveryJobs').innerHTML = data.jobs.length ? data.jobs.map(job => recoveryJobCard(job, data.settings)).join('') : empty('No active recovery jobs');
  $('#recoveryTimeline').innerHTML = data.timeline.length ? data.timeline.map(recoveryTimelineEntry).join('') : empty('No recovery events recorded');
  hydrateCleanForm($('#recoverySettingsForm'), () => { $('#recoveryEnabled').checked = data.settings.enabled; $('#recoveryMaxAttempts').value = data.settings.maxAttempts; $('#recoveryMinScore').value = data.settings.minScore; $('#recoveryOptionalScore').value = data.settings.optionalScore; $('#recoveryUrgentScore').value = data.settings.urgentScore; $('#recoveryDespawnTicks').value = data.settings.despawnTicks; $('#recoverySafetyMarginTicks').value = data.settings.safetyMarginTicks; $('#recoveryMaxDistance').value = data.settings.maxDistance; $('#recoveryDangerLimit').value = data.settings.dangerLimit; });
}
function recoveryStatusText(status, enabled) { if (typeof status === 'string') return status; if (typeof status.status === 'string') return status.status; if (typeof status.state === 'string') return status.state; return enabled ? 'ACTIVE' : 'DISABLED'; }
function formatRecoveryCount(value) { return Math.max(0, value).toLocaleString(); }
function formatRecoveryRate(value) { const percentage = value <= 1 ? value * 100 : value; return `${Math.max(0, Math.min(100, percentage)).toFixed(percentage % 1 === 0 ? 0 : 1)}%`; }
function classifiedRecoveryItems(job) {
  const manifestItems = Array.isArray(job.items) ? job.items : Array.isArray(job.manifest?.items) ? job.manifest.items : [];
  return { required: Array.isArray(job.requiredItems) ? job.requiredItems : manifestItems.filter(item => String(item?.decision ?? '').toUpperCase() === 'REQUIRED'), optional: Array.isArray(job.optionalItems) ? job.optionalItems : manifestItems.filter(item => String(item?.decision ?? '').toUpperCase() === 'OPTIONAL'), ignored: Array.isArray(job.ignoredItems) ? job.ignoredItems : manifestItems.filter(item => String(item?.decision ?? '').toUpperCase() === 'IGNORE') };
}
function recoveryJobCard(job, settings) {
  const items = classifiedRecoveryItems(job); const id = job.id ?? job.manifestId ?? 'unknown'; const status = job.status ?? 'UNKNOWN'; const botId = job.deadBotId ?? job.botId ?? job.manifest?.botId ?? 'unknown'; const assignedBotId = job.assignedBotId ?? job.recoveryBotId ?? 'unassigned'; const attempts = finiteRecoveryValue(job.recoveryAttempts ?? job.attempts); const score = finiteRecoveryValue(job.recoveryScore); const budget = recoveryDespawnBudget(job, settings); const failure = recoveryFailureText(job); const relatedTransfer = job.relatedTransferId ?? job.manifest?.relatedTransferId;
  return `<article class="recovery-job-card"><div class="recovery-job-head"><div><p class="eyebrow">RECOVERY ${escapeHtml(id)}</p><h3>${escapeHtml(botId)}</h3></div><span class="badge">${escapeHtml(status)}</span></div><dl class="recovery-job-detail"><div><dt>Death location</dt><dd>${escapeHtml(recoveryPosition(job.position ?? job.deathPosition ?? job.manifest?.position))}</dd></div><div><dt>Assigned bot</dt><dd>${escapeHtml(assignedBotId)}</dd></div><div><dt>Attempts</dt><dd>${attempts === null ? '—' : attempts} / ${settings.maxAttempts}</dd></div><div><dt>Recovery score</dt><dd>${score === null ? '—' : score}</dd></div>${relatedTransfer ? `<div class="full"><dt>Related transfer</dt><dd>${escapeHtml(relatedTransfer)}</dd></div>` : ''}</dl><div class="recovery-budget"><div><span>Despawn budget</span><b>${budget.remaining === null ? 'unknown' : `${budget.remaining} / ${budget.total} ticks`}</b></div><div class="recovery-budget-track"><i style="width:${budget.percentage}%"></i></div></div><div class="recovery-item-groups">${recoveryItemGroup('REQUIRED', items.required, 'required')}${recoveryItemGroup('OPTIONAL', items.optional, 'optional')}${recoveryItemGroup('IGNORE', items.ignored, 'ignored')}</div>${failure ? `<p class="recovery-failure">${escapeHtml(failure)}</p>` : ''}<time>Updated ${escapeHtml(formatMemoryDate(job.updatedAt ?? job.createdAt))}</time></article>`;
}
function finiteRecoveryValue(value) { const number = Number(value); return value !== null && value !== undefined && Number.isFinite(number) ? number : null; }
function recoveryPosition(position) { if (!position || typeof position !== 'object') return 'unknown'; const coordinates = [finiteRecoveryValue(position.x), finiteRecoveryValue(position.y), finiteRecoveryValue(position.z)]; return coordinates.every(value => value !== null) ? coordinates.join(', ') : 'unknown'; }
function recoveryDespawnBudget(job, settings) { const total = finiteRecoveryValue(job.despawnBudgetTicks ?? job.despawn?.budgetTicks) ?? settings.despawnTicks; const remaining = finiteRecoveryValue(job.remainingDespawnTicks ?? job.despawn?.remainingTicks); const explicitPercentage = finiteRecoveryValue(job.despawnBudgetPercent ?? job.despawn?.percentage); const percentage = explicitPercentage ?? (remaining === null || total <= 0 ? 0 : (remaining / total) * 100); return { total, remaining, percentage: Math.max(0, Math.min(100, percentage)) }; }
function recoveryItemGroup(label, items, className) { if (!items.length) return `<section class="recovery-items ${className}"><b>${label}</b><span>none</span></section>`; return `<section class="recovery-items ${className}"><b>${label}</b><ul>${items.map(recoveryItem).join('')}</ul></section>`; }
function recoveryItem(item) { const record = item && typeof item === 'object' ? item : { name: item }; const count = finiteRecoveryValue(record.count); const score = finiteRecoveryValue(record.dynamicScore ?? record.score); return `<li><span>${escapeHtml(record.name ?? 'unknown item')}${count === null ? '' : ` × ${count}`}</span>${score === null ? '' : `<small>score ${score}</small>`}</li>`; }
function recoveryFailureText(job) { if (typeof job.failureCode === 'string') return job.failureCode; if (typeof job.failure === 'string') return job.failure; if (job.failure && typeof job.failure === 'object') return [job.failure.code, job.failure.message].filter(value => typeof value === 'string' && value).join(': '); return '';
}
function recoveryTimelineEntry(entry) { const title = entry.message ?? entry.event ?? entry.type ?? entry.state ?? 'Recovery event'; const details = [entry.jobId ? `job ${entry.jobId}` : '', entry.botId ? `bot ${entry.botId}` : '', entry.item ? `${entry.item}${finiteRecoveryValue(entry.count) === null ? '' : ` × ${finiteRecoveryValue(entry.count)}`}` : ''].filter(Boolean).join(' · '); return `<article class="recovery-timeline-entry"><time>${escapeHtml(formatMemoryDate(entry.at ?? entry.createdAt))}</time><div><b>${escapeHtml(title)}</b>${details ? `<small>${escapeHtml(details)}</small>` : ''}</div></article>`; }

async function reloadMemoryFromStart() { state.memoryBrowser.offset = 0; await loadMemory(); }
async function loadMemory() {
  if (state.memoryBrowser.loading) return; state.memoryBrowser.loading = true; $('#memoryPageStatus').textContent = 'loading';
  try {
    const parameters = new URLSearchParams({ category: $('#memoryCategory').value, offset: String(state.memoryBrowser.offset), limit: String(state.memoryBrowser.limit) });
    for (const [key, value] of [['q', $('#memorySearch').value.trim()], ['type', $('#memoryType').value.trim()], ['worldKey', $('#memoryWorld').value.trim()], ['dimension', $('#memoryDimension').value.trim()]]) if (value) parameters.set(key, value);
    const data = await api(`/api/v1/memory/dashboard?${parameters}`); state.memoryBrowser.data = data; renderMemory(data);
  } catch (error) { $('#memoryList').innerHTML = empty(`ERROR: ${escapeHtml(error.message)}`); $('#memoryPageStatus').textContent = 'error'; toast(error.message, true); }
  finally { state.memoryBrowser.loading = false; }
}
function renderMemory(data) {
  $('#memoryCountAll').textContent = data.counts.all; $('#memoryCountWorld').textContent = data.counts.world; $('#memoryCountSemantic').textContent = data.counts.semantic; $('#memoryCountShort').textContent = data.counts.shortTerm; $('#memoryCountLong').textContent = data.counts.longTerm;
  const first = data.total ? data.offset + 1 : 0; const last = Math.min(data.offset + data.items.length, data.total); $('#memoryPageStatus').textContent = `${first}-${last} / ${data.total}`; $('#memoryPrevious').disabled = data.offset === 0; $('#memoryNext').disabled = !data.hasMore;
  $('#memoryList').innerHTML = data.items.length ? data.items.map(memoryRecord).join('') : empty('No memory matches these filters');
  const settings = data.settings; hydrateCleanForm($('#memorySettingsForm'), () => { $('#memoryMaxRecords').value = settings.maxRecords; $('#memoryShortLimit').value = settings.shortTermMaxRecords; $('#memoryShortTtl').value = settings.shortTermTtlMs; $('#memoryPromotionAccesses').value = settings.promotionAccesses; $('#memoryPromotionImportance').value = settings.promotionImportance; $('#memoryConsolidationInterval').value = settings.consolidationIntervalMs; });
  $('#memorySettingStatus').textContent = settings.embedding ? `${settings.embedding.model} · ${settings.embedding.dimensions}d` : 'configured'; const lifecycle = data.lifecycle; $('#memoryLifecycleDetail').innerHTML = `<div><dt>Status</dt><dd>${escapeHtml(lifecycle.status)}</dd></div><div><dt>Interval</dt><dd>${formatDuration(lifecycle.intervalMs)}</dd></div><div><dt>Runs</dt><dd>${lifecycle.runs}</dd></div><div><dt>Promoted</dt><dd>${lifecycle.promoted}</dd></div><div><dt>Forgotten</dt><dd>${lifecycle.forgotten}</dd></div><div><dt>Last run</dt><dd>${formatMemoryDate(lifecycle.lastRunAt)}</dd></div>${lifecycle.lastError ? `<div class="full"><dt>Last error</dt><dd>${escapeHtml(lifecycle.lastError)}</dd></div>` : ''}`;
}
function memoryRecord(record) {
  const world = record.category === 'world'; const title = world ? record.name : record.content; const location = [record.worldKey, record.dimension].filter(Boolean).join(' · ') || 'global scope'; const source = record.sourceBotId ?? record.source ?? 'unknown'; const positionText = world && record.position ? ` · ${record.position.x}, ${record.position.y}, ${record.position.z}` : ''; const lifecycle = !world ? ` · access ${record.accessCount ?? 0}${record.expiresAt ? ` · expires ${formatMemoryDate(record.expiresAt)}` : ''}` : ''; const tags = record.tags?.length ? `<div class="memory-tags">${record.tags.map(tag => `<span>${escapeHtml(tag)}</span>`).join('')}</div>` : '';
  return `<article class="memory-record"><div class="memory-record-head"><span class="badge">${world ? 'WORLD' : 'SEMANTIC'} · ${escapeHtml(record.displayType)}</span><div class="memory-record-actions"><time>${formatMemoryDate(record.updatedAt ?? record.createdAt)}</time><button class="button danger" type="button" data-delete-memory data-memory-category="${record.category}" data-memory-id="${escapeHtml(record.id)}">Delete</button></div></div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(location)}${escapeHtml(positionText)}</p><small>source ${escapeHtml(source)} · confidence ${Number(record.confidence ?? 0).toFixed(2)} · importance ${Number(record.importance ?? 0).toFixed(2)}${escapeHtml(lifecycle)}</small>${tags}</article>`;
}
async function deleteMemoryRecord(category, id, button) { const record = state.memoryBrowser.data?.items.find(item => item.id === id && item.category === category); if (!record) return toast('Memory record is no longer available', true); const label = record.category === 'world' ? record.name : record.content; if (!confirm(`Delete ${category} memory "${String(label).slice(0, 100)}"? This cannot be undone.`)) return; button.disabled = true; const path = category === 'semantic' ? `/api/v1/memory/semantic/${encodeURIComponent(id)}` : `/api/v1/memory/${encodeURIComponent(id)}`; try { await api(path, { method: 'DELETE' }); if (state.memoryBrowser.data.items.length === 1 && state.memoryBrowser.offset > 0) state.memoryBrowser.offset = Math.max(0, state.memoryBrowser.offset - state.memoryBrowser.limit); toast('Memory deleted'); await loadMemory(); await refresh(); } catch (error) { button.disabled = false; toast(error.message, true); } }
function formatMemoryDate(value) { if (!value) return 'never'; const date = new Date(value); return Number.isFinite(date.getTime()) ? date.toLocaleString() : 'invalid timestamp'; }
function formatDuration(milliseconds) { const seconds = Math.round(Number(milliseconds) / 1000); return seconds >= 60 ? `${Math.round(seconds / 60)} min` : `${seconds} sec`; }

[$('#llmSettingsForm'), $('#autonomySettingsForm'), $('#acquisitionSettingsForm'), $('#logSettingsForm'), $('#memorySettingsForm'), $('#recoverySettingsForm')].forEach(trackDirty);
document.addEventListener('visibilitychange', () => { if (document.hidden) { clearTimeout(state.polling.timer); clearTimeout(state.recovery.timer); } else { void refresh(); if (recoveryViewActive()) void loadRecovery(); } });
void refresh();
