import { randomUUID } from 'node:crypto';
import { ConflictError, ValidationError } from '../core/errors.js';

export function createHiveService({ repositories, events, ml, heartbeatTimeoutMs }) {
  if (!repositories?.messages || !repositories?.state || !repositories?.locks || !repositories?.decisions) throw new ValidationError('HiveMind repositories are required');
  if (!Number.isInteger(heartbeatTimeoutMs) || heartbeatTimeoutMs < 1000) throw new ValidationError('HiveMind heartbeat timeout must be at least 1000ms');
  const members = new Map(); const processed = new Set();

  const syncMembers = bots => { const now = new Date().toISOString(); for (const bot of bots) { const existing = members.get(bot.id); members.set(bot.id, { id: bot.id, role: bot.metadata?.className ?? 'worker', status: ['READY', 'ACTIVE', 'PAUSED'].includes(bot.status) ? 'ACTIVE' : bot.status === 'DEGRADED' ? 'DEGRADED' : 'OFFLINE', capabilities: [...bot.capabilities], joinedAt: existing?.joinedAt ?? now, lastHeartbeat: now, version: (existing?.version ?? 0) + 1 }); } return [...members.values()].map(member => structuredClone(member)); };
  const heartbeat = (id, status) => { const member = members.get(id); if (!member) throw new ValidationError(`HiveMind member '${id}' is not registered`); const updated = { ...member, status, lastHeartbeat: new Date().toISOString(), version: member.version + 1 }; members.set(id, updated); return structuredClone(updated); };
  const publish = async input => { const message = normalizeMessage(input); if (processed.has(message.id)) return { duplicate: true, message }; processed.add(message.id); if (processed.size > 5000) processed.delete(processed.values().next().value); if (Date.parse(message.timestamp) + message.ttl <= Date.now()) return { expired: true, message }; const record = await repositories.messages.create({ ...message, state: 'DELIVERED' }); await events?.publish('hivemind.message.delivered', record, { source: 'hivemind', correlationId: message.correlationId }); return { duplicate: false, expired: false, message: record }; };
  const setState = async input => { const key = String(input.key ?? ''); if (!/^[A-Za-z0-9_.:-]{1,100}$/.test(key)) throw new ValidationError('HiveMind state key is invalid'); const current = (await repositories.state.list()).find(record => record.key === key); if (current && input.expectedVersion !== undefined && current.version !== input.expectedVersion) throw new ConflictError(`HiveMind state '${key}' expected version ${input.expectedVersion} but found ${current.version}`); const value = { key, value: structuredClone(input.value), source: String(input.source ?? 'system'), version: (current?.version ?? 0) + 1, updatedAt: new Date().toISOString() }; return current ? repositories.state.update(current.id, { ...value, id: current.id }) : repositories.state.create({ ...value, id: randomUUID() }); };
  const acquireLock = async input => { const key = String(input.key ?? ''); const owner = String(input.owner ?? ''); const ttlMs = Number(input.ttlMs); if (!key || !owner || !Number.isInteger(ttlMs) || ttlMs < 1000) throw new ValidationError('HiveMind lock requires key, owner, and ttlMs >= 1000'); const current = (await repositories.locks.list()).find(lock => lock.key === key); if (current && Date.parse(current.expiresAt) > Date.now() && current.owner !== owner) return null; const value = { key, owner, expiresAt: new Date(Date.now() + ttlMs).toISOString(), version: (current?.version ?? 0) + 1, updatedAt: new Date().toISOString() }; return current ? repositories.locks.update(current.id, { ...value, id: current.id }) : repositories.locks.create({ ...value, id: randomUUID() }); };
  const releaseLock = async (key, owner) => { const current = (await repositories.locks.list()).find(lock => lock.key === key && lock.owner === owner); return current ? repositories.locks.delete(current.id) : false; };
  const propose = async input => { const voters = [...members.values()].filter(member => member.status === 'ACTIVE'); if (!voters.length) throw new ConflictError('HiveMind consensus has no active voters'); const votes = await Promise.all(voters.map(async member => { const prediction = await ml.predict({ botId: member.id, intent: input.intent ?? 'unknown' }); return { memberId: member.id, approve: prediction.prediction >= Number(input.threshold ?? 0.5), weight: Math.max(0.1, prediction.prediction), evidence: prediction }; })); const approvedWeight = votes.filter(vote => vote.approve).reduce((sum, vote) => sum + vote.weight, 0); const totalWeight = votes.reduce((sum, vote) => sum + vote.weight, 0); const quorum = voters.length >= Math.max(1, Math.ceil(members.size / 2)); const decision = { id: randomUUID(), proposal: structuredClone(input), votes, quorum, approved: quorum && approvedWeight / totalWeight >= 0.5, createdAt: new Date().toISOString() }; await repositories.decisions.create(decision); await events?.publish('hivemind.consensus.decided', decision, { source: 'hivemind' }); return decision; };
  const status = async () => { const now = Date.now(); const listed = [...members.values()].map(member => ({ ...member, status: now - Date.parse(member.lastHeartbeat) > heartbeatTimeoutMs ? 'SUSPECT' : member.status })); const locks = (await repositories.locks.list()).filter(lock => Date.parse(lock.expiresAt) > now); return { status: listed.some(member => member.status === 'SUSPECT') ? 'DEGRADED' : 'HEALTHY', members: listed, activeMembers: listed.filter(member => member.status === 'ACTIVE').length, locks: locks.length, messages: (await repositories.messages.list()).length, decisions: (await repositories.decisions.list()).length }; };
  return Object.freeze({ syncMembers, heartbeat, publish, setState, acquireLock, releaseLock, propose, status, state: () => repositories.state.list(), decisions: () => repositories.decisions.list() });
}

function normalizeMessage(input) { const timestamp = input.timestamp ?? new Date().toISOString(); const ttl = Number(input.ttlMs); if (!input.sender || !input.type || !Number.isInteger(ttl) || ttl < 1) throw new ValidationError('HiveMind message requires sender, type, and positive ttlMs'); return { id: input.id ?? randomUUID(), sender: String(input.sender), recipient: input.recipient ?? 'broadcast', type: String(input.type), payload: structuredClone(input.payload ?? {}), timestamp, correlationId: input.correlationId ?? randomUUID(), causationId: input.causationId ?? null, ttl, priority: Number(input.priority ?? 50) }; }
