import { ConflictError, ValidationError } from '../core/errors.js';
import { blueprintPreview, importBlueprint } from './blueprint.js';

const DEFAULTS = { approvalRequired: true, maxBots: 4, placementDelayMs: 150, maxAttempts: 3, replaceExisting: false, allowScaffolding: false, maxBlocks: 100000, maxDimension: 256 };
const ACTIVE = new Set(['BUILDING', 'PAUSING']); const TERMINAL = new Set(['COMPLETED', 'CANCELLED']);
export function createBuildingService(options) { return new BuildingService(options); }

class BuildingService {
  constructor({ repository, settingsRepository, events, bots, capabilities, memory, settings = {} }) { this.repository = repository; this.settingsRepository = settingsRepository; this.events = events; this.bots = bots; this.capabilities = capabilities; this.memory = memory; this.config = normalizeSettings({ ...DEFAULTS, ...settings }); this.controllers = new Map(); }
  async initialize() { const saved = (await this.settingsRepository.list())[0]; if (saved) this.config = normalizeSettings({ ...this.config, ...saved }); for (const project of await this.repository.list()) if (ACTIVE.has(project.status)) await this.repository.update(project.id, { status: 'PAUSED', pauseReason: 'APPLICATION_RESTART', activeBots: [] }); }
  settings() { return structuredClone(this.config); }
  async configure(input) { this.config = normalizeSettings({ ...this.config, ...(input ?? {}) }); const current = (await this.settingsRepository.list())[0]; if (current) await this.settingsRepository.update(current.id, this.config); else await this.settingsRepository.create({ id: 'global', ...this.config }); await this.emit('building.settings.updated', { settings: this.settings() }); return this.settings(); }
  protocol() { return { protocol: 'minehive.building', version: '1.0', apiVersion: 'v1', transports: ['http-poll'], synchronization: { snapshot: true, delta: true, revisionField: 'revision' }, commands: ['approve', 'build', 'pause', 'resume', 'cancel'], formats: [{ id: 'minehive-json', mode: 'native' }, { id: 'schem', mode: 'decoder-adapter' }, { id: 'litematic', mode: 'decoder-adapter' }] }; }
  async import(input) { const base = importBlueprint(input, this.config); const now = iso(); const project = { ...base, revision: 0, status: this.config.approvalRequired ? 'PENDING_APPROVAL' : 'READY', target: input.target ? target(input.target) : null, activeBots: [], progress: { total: base.blocks.length, completed: 0, failed: 0, pending: base.blocks.length }, placements: Object.fromEntries(base.blocks.map(block => [block.key, { status: 'PENDING', attempts: 0, ownerBotId: null, verifiedAt: null, error: null }])), deltas: [], createdAt: now, updatedAt: now }; await this.repository.create(project); await this.record(project.id, 'IMPORTED', { status: project.status }); return this.get(project.id); }
  async list() { return (await this.repository.list()).map(summary).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
  async get(id) { return this.repository.find(id); }
  async preview(id, layer) { return blueprintPreview(await this.get(id), layer); }
  async snapshot(id) { return { protocol: this.protocol().protocol, protocolVersion: this.protocol().version, project: await this.get(id) }; }
  async deltas(id, afterRevision = 0) { const project = await this.get(id); const after = Number(afterRevision); if (!Number.isInteger(after) || after < 0) throw new ValidationError('afterRevision must be a non-negative integer'); return { blueprintId: id, revision: project.revision, resetRequired: after > project.revision, deltas: project.deltas.filter(delta => delta.revision > after) }; }
  async approve(id, input = {}) { const project = await this.get(id); if (project.status !== 'PENDING_APPROVAL') throw new ConflictError(`Blueprint cannot be approved from ${project.status}`); await this.repository.update(id, { status: 'READY', approvedBy: String(input.actor ?? 'dashboard'), updatedAt: iso() }); await this.record(id, 'APPROVED', { actor: String(input.actor ?? 'dashboard') }); return this.get(id); }
  async build(id, input = {}) { const project = await this.get(id); if (!['READY', 'PAUSED', 'FAILED'].includes(project.status)) throw new ConflictError(`Blueprint cannot build from ${project.status}`); const destination = target(input.target ?? project.target); const workers = this.workers(input.botIds); if (!workers.length) throw new ValidationError('No READY bot supporting minecraft.blueprint-place is available'); const controller = new AbortController(); this.controllers.get(id)?.abort(new Error('Superseded')); this.controllers.set(id, controller); await this.repository.update(id, { status: 'BUILDING', target: destination, activeBots: workers, pauseReason: null, updatedAt: iso() }); await this.record(id, project.status === 'PAUSED' ? 'RESUMED' : 'BUILD_STARTED', { target: destination, botIds: workers }); void this.run(id, workers, controller.signal); return this.get(id); }
  async pause(id) { const project = await this.get(id); if (project.status !== 'BUILDING') throw new ConflictError(`Blueprint cannot pause from ${project.status}`); await this.repository.update(id, { status: 'PAUSING', updatedAt: iso() }); this.controllers.get(id)?.abort(new Error('Paused by operator')); await this.record(id, 'PAUSE_REQUESTED', {}); return this.get(id); }
  async cancel(id) { const project = await this.get(id); if (TERMINAL.has(project.status)) throw new ConflictError(`Blueprint is already ${project.status}`); this.controllers.get(id)?.abort(new Error('Cancelled by operator')); await this.repository.update(id, { status: 'CANCELLED', activeBots: [], updatedAt: iso() }); await this.record(id, 'CANCELLED', {}); return this.get(id); }
  async status() { const projects = await this.repository.list(); return { status: 'HEALTHY', projects: projects.length, active: projects.filter(item => ACTIVE.has(item.status)).length, pendingApproval: projects.filter(item => item.status === 'PENDING_APPROVAL').length, settings: this.settings() }; }
  workers(requested) { const wanted = Array.isArray(requested) && requested.length ? new Set(requested.map(String)) : null; return this.bots.list().filter(bot => bot.status === 'READY' && (!wanted || wanted.has(bot.id)) && (bot.capabilities ?? []).includes('minecraft.blueprint-place')).slice(0, this.config.maxBots).map(bot => bot.id); }
  async run(id, workers, signal) { try { await Promise.all(workers.map(botId => this.worker(id, botId, signal))); const project = await this.get(id); if (project.status === 'CANCELLED') return; const left = Object.values(project.placements).filter(item => item.status !== 'VERIFIED').length; await this.repository.update(id, { status: left ? 'FAILED' : 'COMPLETED', activeBots: [], updatedAt: iso() }); await this.record(id, left ? 'BUILD_FAILED' : 'BUILD_COMPLETED', { remaining: left }); } catch (error) { const project = await this.get(id); if (project.status === 'CANCELLED') return; const paused = signal.aborted || project.status === 'PAUSING'; await this.repository.update(id, { status: paused ? 'PAUSED' : 'FAILED', pauseReason: paused ? String(signal.reason?.message ?? 'Paused') : null, activeBots: [], failure: paused ? null : { code: error.code ?? 'BUILD_FAILED', message: error.message }, updatedAt: iso() }); await this.record(id, paused ? 'PAUSED' : 'BUILD_FAILED', { error: error.message }); } finally { this.controllers.delete(id); } }
  async worker(id, botId, signal) { while (!signal.aborted) { const project = await this.get(id); const block = project.blocks.find(item => project.placements[item.key].status === 'PENDING' && item.dependencies.every(key => project.placements[key]?.status === 'VERIFIED')); if (!block) return; const state = project.placements[block.key]; const worldPosition = { x: project.target.x + block.x - project.origin.x, y: project.target.y + block.y - project.origin.y, z: project.target.z + block.z - project.origin.z }; const scope = this.scope(botId); const remembered = scope && this.memory ? await this.memory.placement({ ...scope, blueprintId: project.id, blockKey: block.key }) : null; if (remembered) { await this.patch(id, block.key, { status: 'VERIFIED', ownerBotId: remembered.metadata.ownerBotId ?? 'memory', attempts: state.attempts, verifiedAt: remembered.updatedAt, error: null }, 'BLOCK_RESTORED_FROM_MEMORY'); continue; } await this.patch(id, block.key, { ...state, status: 'PLACING', ownerBotId: botId, attempts: state.attempts + 1 }, 'BLOCK_ASSIGNED'); try { const result = await this.capabilities.execute('minecraft.blueprint-place', { block: { ...block, position: worldPosition }, settings: this.config }, { botId, signal }); if (!result?.verified) throw new ValidationError(`Placement ${block.key} was not verified`); await this.patch(id, block.key, { status: 'VERIFIED', ownerBotId: botId, attempts: state.attempts + 1, verifiedAt: iso(), error: null }, 'BLOCK_VERIFIED'); if (scope && this.memory) await this.memory.recordPlacement({ ...scope, blueprintId: project.id, checksum: project.checksum, blockKey: block.key, block, position: worldPosition, ownerBotId: botId }); } catch (error) { if (signal.aborted) throw error; const retry = state.attempts + 1 < this.config.maxAttempts; await this.patch(id, block.key, { status: retry ? 'PENDING' : 'FAILED', ownerBotId: null, attempts: state.attempts + 1, verifiedAt: null, error: { code: error.code ?? 'PLACEMENT_FAILED', message: error.message } }, retry ? 'BLOCK_RETRY' : 'BLOCK_FAILED'); } if (this.config.placementDelayMs) await sleep(this.config.placementDelayMs, signal); } }
  scope(botId) { try { const runtime = this.bots.get(botId); const snapshot = runtime.adapter.snapshot(); return { worldKey: `${String(runtime.options?.host ?? 'localhost').toLowerCase()}:${Number(runtime.options?.port ?? 25565)}`, dimension: String(snapshot.dimension ?? 'overworld') }; } catch { return null; } }
  async patch(id, key, state, event) { const project = await this.get(id); const placements = { ...project.placements, [key]: state }; const values = Object.values(placements); const progress = { total: values.length, completed: values.filter(item => item.status === 'VERIFIED').length, failed: values.filter(item => item.status === 'FAILED').length, pending: values.filter(item => !['VERIFIED', 'FAILED'].includes(item.status)).length }; await this.repository.update(id, { placements, progress, updatedAt: iso() }); await this.record(id, event, { blockKey: key, state, progress }); }
  async record(id, type, payload) { const project = await this.get(id); const delta = { revision: project.revision + 1, type, at: iso(), payload }; await this.repository.update(id, { revision: delta.revision, deltas: [...project.deltas, delta].slice(-2000), updatedAt: delta.at }); await this.emit(`building.${type.toLowerCase()}`, { blueprintId: id, ...delta }); }
  async emit(type, payload) { await this.events?.publish(type, payload, { source: 'building', correlationId: payload.blueprintId }); }
}
function summary(project) { const { blocks, placements, deltas, ...result } = project; return result; }
function normalizeSettings(value) { return { approvalRequired: Boolean(value.approvalRequired), maxBots: number(value.maxBots, 1, 32, 'maxBots'), placementDelayMs: number(value.placementDelayMs, 0, 60000, 'placementDelayMs'), maxAttempts: number(value.maxAttempts, 1, 20, 'maxAttempts'), replaceExisting: Boolean(value.replaceExisting), allowScaffolding: Boolean(value.allowScaffolding), maxBlocks: number(value.maxBlocks, 1, 2000000, 'maxBlocks'), maxDimension: number(value.maxDimension, 1, 2048, 'maxDimension') }; }
function target(value) { if (!value || typeof value !== 'object') throw new ValidationError('Build target is required'); return Object.fromEntries(['x', 'y', 'z'].map(axis => [axis, number(value[axis], -30000000, 30000000, `target.${axis}`)])); }
function number(value, min, max, label) { const result = Number(value); if (!Number.isInteger(result) || result < min || result > max) throw new ValidationError(`${label} must be an integer from ${min} to ${max}`); return result; }
function iso() { return new Date().toISOString(); }
function sleep(ms, signal) { return new Promise((resolve, reject) => { const timer = setTimeout(resolve, ms); signal?.addEventListener('abort', () => { clearTimeout(timer); reject(signal.reason ?? new Error('Cancelled')); }, { once: true }); }); }
