import { randomUUID } from 'node:crypto';
import { ConflictError, NotFoundError, ValidationError } from '../core/errors.js';

const TYPES = new Set(['PROCEDURE', 'STRATEGY']);
const STATUSES = new Set(['DRAFT', 'ACTIVE', 'DEPRECATED']);
const VISIBILITIES = new Set(['PRIVATE', 'TEAM', 'HIVE', 'SYSTEM']);

export function createKnowledgeService({ repository, episodicMemory, embeddingProvider, events, governance = null, maxRecords = 5000, minimumEvidence = 3 }) {
  if (!repository || !episodicMemory || !embeddingProvider) throw new ValidationError('Knowledge repository, episodic memory, and embedding provider are required');
  if (!Number.isInteger(maxRecords) || maxRecords < 1 || !Number.isInteger(minimumEvidence) || minimumEvidence < 2) throw new ValidationError('Knowledge capacity and minimum evidence are invalid');
  let initialized = false; let queue = Promise.resolve(); const mutate = operation => { const result = queue.then(operation); queue = result.then(() => undefined, () => undefined); return result; };

  const remember = input => mutate(async () => {
    const value = normalize(input); const records = await repository.list(); const existing = records.find(item => item.key === value.key); const now = new Date().toISOString(); const vector = embeddingProvider.embed(searchText(value));
    const record = { ...value, id: existing?.id ?? randomUUID(), createdAt: existing?.createdAt ?? now, updatedAt: now, version: Number(existing?.version ?? 0) + 1, schemaVersion: 1, embedding: { model: embeddingProvider.model, version: embeddingProvider.version, dimensions: embeddingProvider.dimensions, generatedAt: now, vector } };
    const saved = existing ? await repository.update(existing.id, record) : await repository.create(record); await governance?.record({ action: existing ? 'KNOWLEDGE_REVISED' : 'KNOWLEDGE_CREATED', memoryId: saved.id, details: { knowledgeType: saved.knowledgeType, key: saved.key, version: saved.version } }); await prune(); return publicKnowledge(saved);
  });
  const revise = (id, input) => mutate(async () => { const current = await rawFind(id); const expected = Number(input?.expectedVersion); if (!Number.isInteger(expected) || expected !== current.version) throw new ConflictError(`Knowledge '${id}' version conflict`, { expectedVersion: expected, actualVersion: current.version }); return rememberInternal({ ...current, ...input, id: undefined, key: current.key, evidence: input.evidence ?? current.evidence }); });
  const feedback = (id, input) => mutate(async () => { const current = await rawFind(id); const success = input?.success; if (typeof success !== 'boolean') throw new ValidationError('Knowledge feedback success must be boolean'); const episodeId = input.episodeId == null ? null : String(input.episodeId); const evidence = { ...current.evidence, episodeIds: episodeId ? [...new Set([...current.evidence.episodeIds, episodeId])].slice(-100) : current.evidence.episodeIds, samples: current.evidence.samples + 1, successes: current.evidence.successes + (success ? 1 : 0), failures: current.evidence.failures + (success ? 0 : 1) }; const confidence = confidenceFrom(evidence); const updated = await repository.update(id, { evidence, confidence, updatedAt: new Date().toISOString(), version: current.version + 1 }); await governance?.record({ action: 'KNOWLEDGE_FEEDBACK', memoryId: id, details: { success, confidence, samples: evidence.samples } }); return publicKnowledge(updated); });
  const synthesize = action => mutate(async () => { const intent = required(action, 'action'); const episodes = (await episodicMemory.search({ text: intent, episodeType: 'TASK_OUTCOME', limit: 100 })).filter(item => item.action === intent); if (episodes.length < minimumEvidence) return null; const successes = episodes.filter(item => item.outcome === 'SUCCESS').length; const failures = episodes.filter(item => item.outcome === 'FAILURE').length; const causes = [...new Set(episodes.filter(item => item.cause).map(item => item.cause))].slice(0, 10); const evidence = { episodeIds: episodes.map(item => item.id).slice(-100), samples: episodes.length, successes, failures }; const recommendation = successes >= failures ? `Gunakan pola ${intent} yang tervalidasi; verifikasi hasil setiap langkah.` : `Gunakan ${intent} secara konservatif dan siapkan fallback deterministik.`; return rememberInternal({ knowledgeType: 'STRATEGY', key: `auto:strategy:${intent}`, name: `Strategi ${intent}`, intent, status: 'ACTIVE', visibility: 'HIVE', recommendations: [recommendation], avoidConditions: causes, evidence, confidence: confidenceFrom(evidence), source: 'episodic-synthesis' }); });
  const rememberInternal = async input => { const value = normalize(input); const existing = (await repository.list()).find(item => item.key === value.key); const now = new Date().toISOString(); const record = { ...value, id: existing?.id ?? randomUUID(), createdAt: existing?.createdAt ?? now, updatedAt: now, version: Number(existing?.version ?? 0) + 1, schemaVersion: 1, embedding: { model: embeddingProvider.model, version: embeddingProvider.version, dimensions: embeddingProvider.dimensions, generatedAt: now, vector: embeddingProvider.embed(searchText(value)) } }; const saved = existing ? await repository.update(existing.id, record) : await repository.create(record); await governance?.record({ action: existing ? 'KNOWLEDGE_REVISED' : 'KNOWLEDGE_CREATED', memoryId: saved.id, details: { knowledgeType: saved.knowledgeType, key: saved.key, version: saved.version } }); await prune(); return publicKnowledge(saved); };
  const search = async (query = {}) => { const vector = String(query.text ?? '').trim() ? embeddingProvider.embed(query.text) : null; return (await repository.list()).filter(item => (!query.knowledgeType || item.knowledgeType === String(query.knowledgeType).toUpperCase()) && (!query.status || item.status === String(query.status).toUpperCase()) && (!query.intent || item.intent === query.intent) && (!query.worldKey || !item.worldKey || item.worldKey === query.worldKey) && (!query.dimension || !item.dimension || item.dimension === query.dimension)).map(item => ({ item, relevance: score(item, vector) })).sort((a, b) => b.relevance - a.relevance).slice(0, limit(query.limit)).map(({ item, relevance }) => ({ ...publicKnowledge(item), relevance: round(relevance) })); };
  const rawFind = async id => { const item = (await repository.list()).find(value => value.id === id); if (!item) throw new NotFoundError('Knowledge', id); return item; }; const find = async id => publicKnowledge(await rawFind(id));
  const initialize = async () => { const records = await repository.list(); let archived = 0; for (const item of records) { try { normalize(item); } catch (error) { await governance?.archive(item, 'knowledge-corrupt'); await repository.delete(item.id); archived++; } } await prune(); initialized = true; return { scanned: records.length, archived, retained: (await repository.list()).length }; };
  const status = async () => { const records = await repository.list(); return { status: initialized ? 'HEALTHY' : 'DEGRADED', count: records.length, maxRecords, minimumEvidence, byType: Object.fromEntries([...TYPES].map(type => [type, records.filter(item => item.knowledgeType === type).length])), active: records.filter(item => item.status === 'ACTIVE').length }; };
  const prune = async () => { const records = await repository.list(); const excess = records.sort((a, b) => (a.status === 'DEPRECATED' ? -1 : 0) - (b.status === 'DEPRECATED' ? -1 : 0) || a.confidence - b.confidence || a.updatedAt.localeCompare(b.updatedAt)).slice(0, Math.max(0, records.length - maxRecords)); for (const item of excess) { await governance?.archive(item, 'knowledge-capacity-limit'); await repository.delete(item.id); } return excess.length; };
  const unsubscribe = events?.subscribe('memory.episodic.recorded', event => event.payload.action ? synthesize(event.payload.action) : null); const dispose = () => unsubscribe?.();
  return Object.freeze({ initialize, remember, revise, feedback, synthesize, search, find, status, dispose });
}

function normalize(input) { if (!input || typeof input !== 'object') throw new ValidationError('Knowledge input must be an object'); const knowledgeType = String(input.knowledgeType ?? '').toUpperCase(); if (!TYPES.has(knowledgeType)) throw new ValidationError('Knowledge type must be PROCEDURE or STRATEGY'); const status = String(input.status ?? 'DRAFT').toUpperCase(); if (!STATUSES.has(status)) throw new ValidationError('Knowledge status is invalid'); const visibility = String(input.visibility ?? 'HIVE').toUpperCase(); if (!VISIBILITIES.has(visibility)) throw new ValidationError('Knowledge visibility is invalid'); const steps = array(input.steps, 64); const recommendations = strings(input.recommendations, 32); if (knowledgeType === 'PROCEDURE' && !steps.length) throw new ValidationError('Procedure requires at least one step'); if (knowledgeType === 'STRATEGY' && !recommendations.length) throw new ValidationError('Strategy requires at least one recommendation'); const evidence = normalizeEvidence(input.evidence); return { knowledgeType, key: required(input.key ?? `${knowledgeType}:${input.name}`, 'key'), name: required(input.name, 'name'), intent: required(input.intent, 'intent'), status, visibility, worldKey: nullable(input.worldKey), dimension: nullable(input.dimension), preconditions: array(input.preconditions, 32), steps, recommendations, avoidConditions: strings(input.avoidConditions, 32), evidence, confidence: bounded(input.confidence, confidenceFrom(evidence)), source: nullable(input.source) ?? 'manual', metadata: object(input.metadata) }; }
function normalizeEvidence(value = {}) { const source = object(value); const samples = integer(source.samples, 0); const successes = integer(source.successes, 0); const failures = integer(source.failures, 0); if (successes + failures > samples) throw new ValidationError('Knowledge evidence counts exceed samples'); return { episodeIds: strings(source.episodeIds, 100), samples, successes, failures }; }
function confidenceFrom(evidence) { return (evidence.successes + 1) / (evidence.successes + evidence.failures + 2); }
function searchText(value) { return `${value.name} ${value.intent} ${value.recommendations.join(' ')} ${value.steps.map(step => step.action ?? JSON.stringify(step)).join(' ')} ${value.avoidConditions.join(' ')}`; }
function score(item, vector) { const similarity = vector ? Math.max(0, cosine(item.embedding.vector, vector)) : 0.5; return similarity * 0.55 + item.confidence * 0.35 + (item.status === 'ACTIVE' ? 0.1 : 0); }
function publicKnowledge(item) { const { embedding, ...value } = item; return { ...value, embedding: { model: embedding.model, version: embedding.version, dimensions: embedding.dimensions, generatedAt: embedding.generatedAt } }; }
function cosine(a, b) { return Array.isArray(a) && a.length === b.length ? a.reduce((sum, value, index) => sum + value * b[index], 0) : 0; }
function required(value, field) { const result = String(value ?? '').trim(); if (!result || result.length > 300) throw new ValidationError(`Knowledge ${field} must contain 1-300 characters`); return result; }
function nullable(value) { if (value == null) return null; return String(value).trim().slice(0, 300) || null; }
function strings(value, max) { return Array.isArray(value) ? [...new Set(value.map(String).map(item => item.trim()).filter(Boolean))].slice(0, max) : []; }
function array(value, max) { return Array.isArray(value) ? structuredClone(value).slice(0, max) : []; }
function object(value) { return value && typeof value === 'object' && !Array.isArray(value) ? structuredClone(value) : {}; }
function integer(value, fallback) { const number = Number(value); return Number.isInteger(number) && number >= 0 ? number : fallback; }
function bounded(value, fallback) { const number = Number(value); return Math.max(0, Math.min(1, Number.isFinite(number) ? number : fallback)); }
function limit(value) { return Math.max(1, Math.min(50, Number.parseInt(value ?? 10, 10) || 10)); }
function round(value) { return Math.round(value * 10_000) / 10_000; }
