import { randomUUID } from 'node:crypto';
import { CancelledError, ConflictError, ValidationError } from '../core/errors.js';

export const SYSTEM_MODES = Object.freeze(['NORMAL', 'DEGRADED', 'EMERGENCY', 'RECOVERY', 'SHUTDOWN']);
export const EMERGENCY_TYPES = Object.freeze(['BOT_DEATH', 'CRITICAL_FOOD', 'BASE_ATTACK', 'RESOURCE_CRISIS', 'PLUGIN_FAILURE', 'COMMUNICATION_LOSS', 'DATABASE_FAILURE', 'HIVEMIND_FAILURE', 'INFRASTRUCTURE_DAMAGE', 'MASS_DISCONNECT']);

export function createResilienceService({ repositories, events, delay = ms => new Promise(resolve => setTimeout(resolve, ms)), circuitFailureThreshold = 3, circuitCooldownMs = 30_000 }) {
  if (!repositories?.incidents || !repositories?.deadLetters || !repositories?.recovery || !repositories?.commands) throw new ValidationError('Resilience repositories are required'); let mode = 'NORMAL'; const dependencies = new Map(); const circuits = new Map();
  const raise = async input => { const type = String(input?.type ?? '').trim().toUpperCase(); if (!EMERGENCY_TYPES.includes(type)) throw new ValidationError(`Emergency type must be one of ${EMERGENCY_TYPES.join(', ')}`); const severity = severityValue(input.severity); const key = safeKey(input.idempotencyKey ?? `${type}:${input.sourceId ?? 'global'}`); const duplicate = (await repositories.incidents.list()).find(item => item.idempotencyKey === key && item.status === 'ACTIVE'); if (duplicate) return duplicate; const now = new Date().toISOString(); const incident = await repositories.incidents.create({ id: randomUUID(), idempotencyKey: key, type, severity, status: 'ACTIVE', response: emergencyResponse(type, severity), details: structuredClone(input.details ?? {}), createdAt: now, updatedAt: now }); mode = severity >= 3 ? 'EMERGENCY' : 'DEGRADED'; await events?.publish('system.emergency.raised', incident, { source: 'resilience', correlationId: incident.id }); return incident; };
  const resolve = async (id, input = {}) => { const incident = await repositories.incidents.find(id); if (incident.status !== 'ACTIVE') throw new ConflictError(`Emergency '${id}' is already resolved`); mode = 'RECOVERY'; const now = new Date().toISOString(); const updated = await repositories.incidents.update(id, { status: 'RESOLVED', resolution: safeText(input.resolution ?? 'System stabilized'), resolvedAt: now, updatedAt: now }); await events?.publish('system.emergency.resolved', updated, { source: 'resilience', correlationId: id }); await recomputeMode(); return updated; };
  const reportDependency = async input => { const name = safeKey(input.name); const status = String(input.status ?? '').toUpperCase(); if (!['HEALTHY', 'DEGRADED', 'FAILED'].includes(status)) throw new ValidationError('Dependency status is invalid'); dependencies.set(name, { name, status, critical: input.critical === true, error: input.error ? safeText(input.error) : null, checkedAt: new Date().toISOString() }); await recomputeMode(); return structuredClone(dependencies.get(name)); };
  const execute = async input => { if (typeof input?.operation !== 'function') throw new ValidationError('Resilient operation must be a function'); const key = safeKey(input.idempotencyKey); const previous = (await repositories.commands.list()).find(item => item.idempotencyKey === key && item.status === 'COMPLETED'); if (previous) return { ...structuredClone(previous.result), replayed: true }; const dependency = safeKey(input.dependency ?? 'default'); assertCircuit(dependency); const maxAttempts = boundedInteger(input.maxAttempts ?? 4, 1, 8, 'maxAttempts'); const baseDelayMs = boundedInteger(input.baseDelayMs ?? 1000, 0, 60_000, 'baseDelayMs'); const timeoutMs = boundedInteger(input.timeoutMs ?? 30_000, 1, 300_000, 'timeoutMs'); let error;
    for (let attempt = 1; attempt <= maxAttempts; attempt++) { try { if (input.signal?.aborted) throw new CancelledError(input.signal.reason ? String(input.signal.reason) : 'Resilient operation cancelled'); const value = await withTimeout(() => input.operation({ attempt, signal: input.signal }), timeoutMs); circuits.delete(dependency); const now = new Date().toISOString(); const command = await repositories.commands.create({ id: randomUUID(), idempotencyKey: key, dependency, status: 'COMPLETED', attempts: attempt, result: { value }, createdAt: now, updatedAt: now }); await events?.publish('resilience.command.completed', command, { source: 'resilience', correlationId: command.id }); return { value, attempts: attempt, replayed: false }; } catch (caught) { if (caught?.code === 'CANCELLED' || input.signal?.aborted) throw caught?.code === 'CANCELLED' ? caught : new CancelledError(String(input.signal.reason ?? 'Resilient operation cancelled')); error = caught; registerCircuitFailure(dependency); await events?.publish('resilience.command.retry', { idempotencyKey: key, dependency, attempt, maxAttempts, error: errorMessage(caught) }, { source: 'resilience' }); if (attempt < maxAttempts) await delay(baseDelayMs * 2 ** (attempt - 1)); } }
    const now = new Date().toISOString(); const failure = { id: randomUUID(), idempotencyKey: key, dependency, status: 'PENDING', attempts: maxAttempts, error: { code: error?.code ?? 'OPERATION_FAILED', message: errorMessage(error) }, createdAt: now, updatedAt: now }; await repositories.deadLetters.create({ ...failure, status: 'DEAD_LETTER' }); await repositories.recovery.create(failure); mode = 'DEGRADED'; await events?.publish('resilience.command.dead-lettered', failure, { source: 'resilience', correlationId: failure.id }); throw error;
  };
  const recover = async (id, operation) => { if (typeof operation !== 'function') throw new ValidationError('Recovery operation must be a function'); const item = await repositories.recovery.find(id); if (item.status !== 'PENDING') throw new ConflictError(`Recovery '${id}' is ${item.status}`); mode = 'RECOVERY'; try { const result = await operation(item); const updated = await repositories.recovery.update(id, { status: 'RECOVERED', result: structuredClone(result), recoveredAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); await events?.publish('resilience.recovery.completed', updated, { source: 'resilience', correlationId: id }); await recomputeMode(); return updated; } catch (error) { const updated = await repositories.recovery.update(id, { status: 'FAILED', error: { code: error?.code ?? 'RECOVERY_FAILED', message: errorMessage(error) }, updatedAt: new Date().toISOString() }); mode = 'DEGRADED'; return updated; } };
  const shutdown = async () => { mode = 'SHUTDOWN'; await events?.publish('system.mode.changed', { mode }, { source: 'resilience' }); return { mode }; };
  const status = async () => ({ status: mode === 'NORMAL' ? 'HEALTHY' : mode === 'SHUTDOWN' ? 'FAILED' : 'DEGRADED', mode, activeIncidents: (await repositories.incidents.list()).filter(item => item.status === 'ACTIVE').length, deadLetters: (await repositories.deadLetters.list()).length, recoveryPending: (await repositories.recovery.list()).filter(item => item.status === 'PENDING').length, dependencies: [...dependencies.values()].map(item => structuredClone(item)), circuits: [...circuits].map(([name, value]) => ({ name, state: circuitOpen(value) ? 'OPEN' : 'CLOSED', failures: value.failures, openedAt: value.openedAt })) });
  const recomputeMode = async () => { if (mode === 'SHUTDOWN') return; const active = (await repositories.incidents.list()).filter(item => item.status === 'ACTIVE'); const recovery = (await repositories.recovery.list()).some(item => item.status === 'PENDING'); if (active.some(item => item.severity >= 3)) mode = 'EMERGENCY'; else if (active.length || recovery || [...dependencies.values()].some(item => item.status !== 'HEALTHY')) mode = 'DEGRADED'; else mode = 'NORMAL'; await events?.publish('system.mode.changed', { mode }, { source: 'resilience' }); };
  function registerCircuitFailure(name) { const current = circuits.get(name) ?? { failures: 0, openedAt: null }; current.failures += 1; if (current.failures >= circuitFailureThreshold && !current.openedAt) current.openedAt = Date.now(); circuits.set(name, current); }
  function assertCircuit(name) { const current = circuits.get(name); if (!current || !circuitOpen(current)) return; if (Date.now() - current.openedAt >= circuitCooldownMs) { circuits.delete(name); return; } throw new ConflictError(`Circuit '${name}' is open`); }
  function circuitOpen(value) { return Boolean(value.openedAt) && Date.now() - value.openedAt < circuitCooldownMs; }
  return Object.freeze({ raise, resolve, reportDependency, execute, recover, shutdown, status, incidents: () => repositories.incidents.list(), deadLetters: () => repositories.deadLetters.list(), recoveryQueue: () => repositories.recovery.list() });
}

function emergencyResponse(type, severity) { if (type === 'BASE_ATTACK') return severity >= 4 ? 'EVACUATE_AND_INTERCEPT' : 'DEFEND_AND_REQUEST_BACKUP'; if (type === 'CRITICAL_FOOD') return 'PAUSE_AND_ACQUIRE_FOOD'; if (type === 'BOT_DEATH') return 'PROTECT_CARGO_AND_RECOVER'; if (['DATABASE_FAILURE', 'HIVEMIND_FAILURE', 'COMMUNICATION_LOSS'].includes(type)) return 'ENTER_DEGRADED_MODE'; if (type === 'MASS_DISCONNECT') return 'STOP_AND_RECONNECT_BOUNDED'; return severity >= 3 ? 'INTERRUPT_AND_STABILIZE' : 'ISOLATE_AND_MONITOR'; }
function severityValue(value) { const key = String(value ?? 'HIGH').toUpperCase(); const values = { LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4 }; if (!values[key]) throw new ValidationError('Emergency severity is invalid'); return values[key]; }
function withTimeout(operation, timeoutMs) { let handle; return Promise.race([Promise.resolve().then(operation), new Promise((_, reject) => { handle = setTimeout(() => reject(Object.assign(new Error(`Operation timed out after ${timeoutMs}ms`), { code: 'TIMEOUT' })), timeoutMs); })]).finally(() => clearTimeout(handle)); }
function safeKey(value) { const key = String(value ?? '').trim(); if (!/^[A-Za-z0-9_.:-]{1,160}$/.test(key)) throw new ValidationError('Resilience key is invalid'); return key; }
function safeText(value) { const text = String(value ?? '').trim(); if (!text || text.length > 500 || /[\u0000-\u001f]/.test(text)) throw new ValidationError('Resilience text is invalid'); return text; }
function boundedInteger(value, minimum, maximum, field) { const number = Number(value); if (!Number.isInteger(number) || number < minimum || number > maximum) throw new ValidationError(`Resilience ${field} must be between ${minimum} and ${maximum}`); return number; }
function errorMessage(error) { return error instanceof Error ? error.message : String(error); }
