import { randomUUID } from 'node:crypto';
import { ConflictError, ValidationError } from '../core/errors.js';
import { EXPANSION_DIRECTIONS, normalizeExpansionProposal, validateExpansion } from './expansion-validator.js';

export function createExpansionService({ repository, territory, events, policy = {} }) {
  if (!repository || !territory) throw new ValidationError('Expansion service requires repository and territory');
  const get = id => repository.find(id);
  const list = async filter => (await repository.list()).filter(item => (!filter?.status || item.status === String(filter.status).toUpperCase()) && (!filter?.source || item.proposal.source === String(filter.source).toUpperCase()));
  const propose = async input => { const proposal = normalizeExpansionProposal(input); const decision = validateExpansion(proposal, input.context, policy); const now = new Date().toISOString(); const record = await repository.create({ id: randomUUID(), proposal, context: structuredClone(input.context), decision, status: decision.outcome, approval: null, appliedRegionId: null, version: 1, createdAt: now, updatedAt: now }); await publish('territory.expansion.proposed', record); await publish(`territory.expansion.${record.status.toLowerCase()}`, record); return record; };
  const revalidate = async (id, context) => { const previous = await get(id); if (['APPLIED', 'CANCELLED'].includes(previous.status)) throw new ConflictError(`Expansion proposal '${id}' cannot be revalidated`); const decision = validateExpansion(previous.proposal, context, policy); const updated = await repository.update(id, { context: structuredClone(context), decision, status: decision.outcome, approval: null, version: previous.version + 1, updatedAt: new Date().toISOString() }); await publish('territory.expansion.revalidated', updated); return updated; };
  const approve = async (id, input = {}) => { const previous = await get(id); if (previous.status !== 'APPROVAL_REQUIRED') throw new ConflictError(`Expansion proposal '${id}' is not awaiting approval`); const approvedBy = String(input.approvedBy ?? '').trim(); if (!/^[A-Za-z0-9_.@ -]{1,80}$/.test(approvedBy)) throw new ValidationError('Expansion approvedBy is invalid'); const now = new Date().toISOString(); const updated = await repository.update(id, { status: 'APPROVED', approval: { approvedBy, approvedAt: now }, version: previous.version + 1, updatedAt: now }); await publish('territory.expansion.approved', updated); return updated; };
  const apply = async id => { const previous = await get(id); if (previous.status !== 'APPROVED') throw new ConflictError(`Expansion proposal '${id}' is not approved`); const vector = EXPANSION_DIRECTIONS[previous.proposal.direction]; const diagonal = vector.x && vector.z ? 1 / Math.sqrt(2) : 1; const center = { x: previous.proposal.origin.x + vector.x * previous.proposal.radiusIncrease * diagonal, y: previous.proposal.origin.y, z: previous.proposal.origin.z + vector.z * previous.proposal.radiusIncrease * diagonal }; const type = previous.proposal.needsOutpost ? 'OUTPOST' : 'FRONTIER'; const region = await territory.create({ worldKey: previous.proposal.worldKey, dimension: previous.proposal.dimension, name: `${type === 'OUTPOST' ? 'Outpost' : 'Expansion'} ${previous.proposal.direction.replaceAll('_', ' ')}`, type, center, radius: Math.min(128, Math.max(16, previous.proposal.radiusIncrease / 4)), resources: previous.proposal.targetResource ? [previous.proposal.targetResource] : [], explored: false, metadata: { expansion: { proposalId: previous.id, source: previous.proposal.source, reason: previous.proposal.reason, appliedAt: new Date().toISOString(), needsWarehouse: previous.proposal.needsWarehouse } } }); const now = new Date().toISOString(); const updated = await repository.update(id, { status: 'APPLIED', appliedRegionId: region.id, version: previous.version + 1, updatedAt: now, appliedAt: now }); await publish('territory.expansion.applied', { proposal: updated, region }); return { proposal: updated, region }; };
  const cancel = async id => { const previous = await get(id); if (['APPLIED', 'CANCELLED'].includes(previous.status)) throw new ConflictError(`Expansion proposal '${id}' cannot be cancelled`); const updated = await repository.update(id, { status: 'CANCELLED', version: previous.version + 1, updatedAt: new Date().toISOString() }); await publish('territory.expansion.cancelled', updated); return updated; };
  const status = async () => { const items = await repository.list(); const counts = Object.fromEntries(['APPROVED', 'APPROVAL_REQUIRED', 'REJECTED', 'APPLIED', 'CANCELLED'].map(status => [status.toLowerCase(), items.filter(item => item.status === status).length])); return { status: 'HEALTHY', proposals: items.length, ...counts, policy: { ...policy } }; };
  const publish = (type, payload) => events?.publish(type, payload, { source: 'territory-expansion', correlationId: payload.id ?? payload.proposal?.id });
  return Object.freeze({ propose, revalidate, approve, apply, cancel, get, list, status });
}
