import { randomUUID } from 'node:crypto';
import { ConflictError, ValidationError } from '../core/errors.js';

const ACTIVE = new Set(['ASSIGNED', 'RUNNING']);
const DIRECTIONS = Object.freeze([{ name: 'N', x: 0, z: -1 }, { name: 'NE', x: 1, z: -1 }, { name: 'E', x: 1, z: 0 }, { name: 'SE', x: 1, z: 1 }, { name: 'S', x: 0, z: 1 }, { name: 'SW', x: -1, z: 1 }, { name: 'W', x: -1, z: 0 }, { name: 'NW', x: -1, z: -1 }]);

export function createExplorationService({ repository, territory, bots, navigation, discovery, events }) {
  if (!repository || !territory || !bots || !navigation || !discovery) throw new ValidationError('Exploration requires repository, territory, bots, navigation, and discovery');
  const running = new Set();
  const initialize = async () => { const now = new Date().toISOString(); const recovered = []; for (const mission of await repository.list()) if (mission.status === 'RUNNING') recovered.push(await repository.update(mission.id, { status: 'FAILED', failure: { code: 'INTERRUPTED_BY_RESTART', message: 'Exploration execution was interrupted by application restart' }, finishedAt: now, updatedAt: now })); return recovered; };
  const seedFrontiers = async input => { const request = normalizeArea(input); const distance = bounded(input.distance, 32, 2048, 128, 'distance'); const radius = bounded(input.radius, 8, 128, 24, 'radius'); const existing = await territory.list({ worldKey: request.worldKey, dimension: request.dimension, type: 'FRONTIER' }); const created = []; for (const direction of DIRECTIONS) { const scale = direction.x && direction.z ? distance / Math.sqrt(2) : distance; const center = { x: request.origin.x + direction.x * scale, y: request.origin.y, z: request.origin.z + direction.z * scale }; if (existing.some(region => planar(region.center, center) < radius)) continue; created.push(await territory.create({ worldKey: request.worldKey, dimension: request.dimension, name: `Frontier ${direction.name} ${Math.floor(center.x)}-${Math.floor(center.z)}`, type: 'FRONTIER', center, radius, dangerLevel: 0, explored: false, metadata: { exploration: { direction: direction.name, seededAt: new Date().toISOString() } } })); } await events?.publish('territory.frontiers.seeded', { worldKey: request.worldKey, dimension: request.dimension, created }, { source: 'exploration' }); return created; };
  const plan = async input => { const request = normalizeArea(input); const maximum = bounded(input.maxDistance, 16, 100_000, 2048, 'maxDistance'); const frontiers = (await territory.list({ worldKey: request.worldKey, dimension: request.dimension, type: 'FRONTIER' })).filter(region => !region.explored).map(region => ({ region, distance: planar(request.origin, region.center) })).filter(item => item.distance <= maximum); const ranked = []; for (const item of frontiers) { const overlaps = await territory.at({ worldKey: request.worldKey, dimension: request.dimension, position: item.region.center }); const danger = Math.max(item.region.dangerLevel, ...overlaps.filter(region => region.type === 'DANGER').map(region => region.dangerLevel), 0); ranked.push({ ...item, danger, score: round(100 - Math.min(40, item.distance / maximum * 40) - danger * 60) }); } ranked.sort((a, b) => b.score - a.score || a.distance - b.distance || a.region.id.localeCompare(b.region.id)); const target = ranked[0] ?? null; const scout = target ? await selectScout({ target: target.region.center, worldKey: request.worldKey, dimension: request.dimension }) : null; return { ...request, target: target?.region ?? null, scout, candidates: ranked.map(item => ({ regionId: item.region.id, score: item.score, distance: round(item.distance), danger: item.danger })), plannedAt: new Date().toISOString() }; };
  const createMission = async input => { const proposal = await plan(input); if (!proposal.target) throw new ValidationError('No unexplored frontier is available'); if (!proposal.scout) throw new ValidationError('No eligible scout is available'); const now = new Date().toISOString(); const mission = await repository.create({ id: randomUUID(), status: 'ASSIGNED', worldKey: proposal.worldKey, dimension: proposal.dimension, origin: proposal.origin, frontierId: proposal.target.id, target: proposal.target.center, scoutBotId: proposal.scout.botId, score: proposal.candidates[0].score, attempts: 0, result: null, failure: null, createdAt: now, updatedAt: now, startedAt: null, finishedAt: null }); await events?.publish('exploration.mission.assigned', mission, { source: 'exploration', correlationId: mission.id }); return mission; };
  const execute = async id => { let mission = await get(id); if (running.has(mission.id) || mission.status !== 'ASSIGNED') throw new ConflictError(`Exploration mission '${mission.id}' is not executable`); running.add(mission.id); const startedAt = new Date().toISOString(); mission = await repository.update(mission.id, { status: 'RUNNING', attempts: mission.attempts + 1, startedAt, updatedAt: startedAt }); await events?.publish('exploration.mission.started', mission, { source: 'exploration', correlationId: mission.id }); try { await navigation.moveTo({ botId: mission.scoutBotId, target: mission.target, mode: 'SAFE', source: 'AUTONOMY' }); const runtime = bots.get(mission.scoutBotId); const frontier = await territory.get(mission.frontierId); const survey = await runtime.adapter.survey({ maxDistance: Math.min(128, frontier.radius) }); const result = await discovery.record({ runtime, survey, reason: 'exploration' }); await territory.update(frontier.id, { explored: true, lastSeen: survey.scannedAt ?? new Date().toISOString(), metadata: { ...frontier.metadata, exploration: { ...(frontier.metadata?.exploration ?? {}), missionId: mission.id, scoutBotId: mission.scoutBotId, completedAt: new Date().toISOString() } } }); const finishedAt = new Date().toISOString(); mission = await repository.update(mission.id, { status: 'COMPLETED', result: { discoveries: result.memories.length, scannedAt: result.scannedAt }, finishedAt, updatedAt: finishedAt }); await events?.publish('exploration.mission.completed', mission, { source: 'exploration', correlationId: mission.id }); return mission; } catch (error) { const finishedAt = new Date().toISOString(); mission = await repository.update(mission.id, { status: 'FAILED', failure: { code: error.code ?? 'EXPLORATION_FAILED', message: error.message }, finishedAt, updatedAt: finishedAt }); await events?.publish('exploration.mission.failed', mission, { source: 'exploration', correlationId: mission.id }); throw error; } finally { running.delete(mission.id); } };
  const cancel = async id => { const mission = await get(id); if (!ACTIVE.has(mission.status)) throw new ConflictError(`Exploration mission '${mission.id}' is not active`); if (mission.status === 'RUNNING') await navigation.cancel({ botId: mission.scoutBotId, reason: 'Exploration mission cancelled' }); const now = new Date().toISOString(); const cancelled = await repository.update(mission.id, { status: 'CANCELLED', finishedAt: now, updatedAt: now }); await events?.publish('exploration.mission.cancelled', cancelled, { source: 'exploration', correlationId: mission.id }); return cancelled; };
  const get = id => repository.find(String(id)); const list = async query => (await repository.list()).filter(mission => (!query?.status || mission.status === String(query.status).toUpperCase()) && (!query?.botId || mission.scoutBotId === query.botId)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); const status = async () => { const missions = await repository.list(); return { status: 'HEALTHY', missions: missions.length, active: missions.filter(item => ACTIVE.has(item.status)).length, running: running.size, completed: missions.filter(item => item.status === 'COMPLETED').length, failed: missions.filter(item => item.status === 'FAILED').length }; };
  async function selectScout({ target, worldKey, dimension }) { const missions = await repository.list(); const busy = new Set(missions.filter(item => ACTIVE.has(item.status)).map(item => item.scoutBotId)); const candidates = bots.list().filter(bot => ['READY', 'ACTIVE'].includes(bot.status) && !busy.has(bot.id)).map(bot => { const runtime = bots.get(bot.id); const key = `${String(runtime.options?.host ?? 'localhost').toLowerCase()}:${Number(runtime.options?.port ?? 25565)}`; const position = bot.runtime?.position; if (key !== worldKey || bot.runtime?.dimension !== dimension || !position) return null; const specialist = String(bot.metadata?.className ?? '').toLowerCase() === 'scout' ? 30 : 0; const health = Number(bot.runtime?.health ?? 20); const food = Number(bot.runtime?.food ?? 20); const distance = planar(position, target); return { botId: bot.id, score: round(50 + specialist + Math.min(10, health / 2) + Math.min(10, food / 2) - Math.min(30, distance / 64)), distance: round(distance), specialist: specialist > 0 }; }).filter(Boolean).sort((a, b) => b.score - a.score || a.distance - b.distance || a.botId.localeCompare(b.botId)); return candidates[0] ?? null; }
  return Object.freeze({ initialize, seedFrontiers, plan, createMission, execute, cancel, get, list, status });
}

function normalizeArea(input) { const worldKey = String(input?.worldKey ?? '').trim().toLowerCase(); const dimension = String(input?.dimension ?? 'overworld').trim(); const origin = input?.origin; if (!/^[a-z0-9.-]+:[1-9][0-9]{0,4}$/.test(worldKey) || !origin || ![origin.x, origin.y, origin.z].every(value => Number.isFinite(Number(value)))) throw new ValidationError('Exploration requires valid worldKey, dimension, and origin'); return { worldKey, dimension, origin: { x: Number(origin.x), y: Number(origin.y), z: Number(origin.z) } }; }
function bounded(value, minimum, maximum, fallback, field) { const number = Number(value ?? fallback); if (!Number.isFinite(number) || number < minimum || number > maximum) throw new ValidationError(`Exploration ${field} must be between ${minimum} and ${maximum}`); return number; }
function planar(left, right) { return Math.hypot(left.x - right.x, left.z - right.z); }
function round(value) { return Math.round(value * 1000) / 1000; }
