import { randomUUID } from 'node:crypto';
import { ConflictError, ValidationError } from '../core/errors.js';

export const THREAT_LEVELS = Object.freeze(['NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']);

export function createThreatService({ repository, events }) {
  if (!repository) throw new ValidationError('Threat service requires repository');
  const detect = async input => { const observation = normalizeThreat(input); const score = scoreThreat(observation); const level = score < 0.15 ? 'NONE' : score < 0.35 ? 'LOW' : score < 0.6 ? 'MEDIUM' : score < 0.82 ? 'HIGH' : 'CRITICAL'; const response = responseFor(level, observation); const now = new Date().toISOString(); const threat = await repository.create({ id: randomUUID(), ...observation, score, level, response, status: level === 'NONE' ? 'CLOSED' : 'ACTIVE', createdAt: now, updatedAt: now, resolvedAt: level === 'NONE' ? now : null }); await events?.publish('territory.threat.detected', threat, { source: 'territory-defense', correlationId: threat.id }); if (['HIGH', 'CRITICAL'].includes(level)) await events?.publish('territory.threat.escalated', threat, { source: 'territory-defense', correlationId: threat.id }); return threat; };
  const resolve = async (id, input = {}) => { const threat = await repository.find(id); if (threat.status === 'CLOSED') throw new ConflictError(`Threat '${id}' is already closed`); const now = new Date().toISOString(); const result = await repository.update(id, { status: 'CLOSED', resolution: safeReason(input.resolution ?? 'Threat no longer observed'), resolvedAt: now, updatedAt: now }); await events?.publish('territory.threat.resolved', result, { source: 'territory-defense', correlationId: id }); return result; };
  const list = async filter => (await repository.list()).filter(item => (!filter?.status || item.status === String(filter.status).toUpperCase()) && (!filter?.level || item.level === String(filter.level).toUpperCase()));
  const status = async () => { const threats = await repository.list(); const active = threats.filter(item => item.status === 'ACTIVE'); const highest = THREAT_LEVELS.reduce((best, level) => active.some(item => item.level === level) ? level : best, 'NONE'); return { status: active.some(item => ['HIGH', 'CRITICAL'].includes(item.level)) ? 'DEGRADED' : 'HEALTHY', threats: threats.length, active: active.length, highestLevel: highest }; };
  return Object.freeze({ detect, resolve, get: id => repository.find(id), list, status });
}

export function scoreThreat(input) { const hostile = entityRisk(input.entityType); const proximity = 1 - Math.min(1, input.distance / 64); const vulnerability = 1 - input.botHealth / 20; const equipmentRisk = (1 - input.armor) * 0.1 + (1 - input.weapon) * 0.08; const numbers = Math.min(1, input.enemyCount / Math.max(1, input.nearbyFriendlyBots + 1)); const night = input.time === 'NIGHT' ? 0.08 : 0; const baseRisk = 1 - Math.min(1, input.distanceFromBase / 256); const trapped = input.escapeRoute ? 0 : 0.15; const mission = input.missionImportance * 0.05; return round(Math.min(1, hostile * 0.24 + proximity * 0.14 + vulnerability * 0.12 + equipmentRisk + numbers * 0.12 + night + baseRisk * 0.05 + trapped + mission)); }
function responseFor(level, input) { if (level === 'NONE') return 'IGNORE'; if (level === 'LOW') return 'OBSERVE'; if (level === 'MEDIUM') return input.escapeRoute ? 'AVOID' : 'RETREAT'; if (level === 'HIGH') return input.nearbyFriendlyBots > 0 && input.botHealth >= 12 ? 'DEFEND' : 'REQUEST_BACKUP'; return input.distanceFromBase <= 64 ? 'INTERCEPT' : 'EVACUATE'; }
function normalizeThreat(input) { if (!input || typeof input !== 'object') throw new ValidationError('Threat observation must be an object'); return { entityType: token(input.entityType, 'entityType'), distance: nonNegative(input.distance, 'distance'), botHealth: bounded(input.botHealth, 0, 20, 'botHealth'), armor: ratio(input.armor ?? 0, 'armor'), weapon: ratio(input.weapon ?? 0, 'weapon'), enemyCount: integer(input.enemyCount, 'enemyCount'), time: String(input.time ?? 'DAY').toUpperCase() === 'NIGHT' ? 'NIGHT' : 'DAY', nearbyFriendlyBots: integer(input.nearbyFriendlyBots ?? 0, 'nearbyFriendlyBots'), distanceFromBase: nonNegative(input.distanceFromBase, 'distanceFromBase'), escapeRoute: input.escapeRoute === true, missionImportance: ratio(input.missionImportance ?? 0.5, 'missionImportance'), worldKey: token(input.worldKey, 'worldKey'), dimension: token(input.dimension ?? 'overworld', 'dimension'), position: position(input.position), sourceBotId: token(input.sourceBotId, 'sourceBotId') }; }
function entityRisk(value) { return ({ warden: 1, wither: 1, ender_dragon: 1, creeper: 0.8, ravager: 0.85, vindicator: 0.72, pillager: 0.58, skeleton: 0.52, zombie: 0.45, spider: 0.4 })[String(value).toLowerCase()] ?? 0.35; }
function safeReason(value) { const result = String(value).trim(); if (!result || result.length > 300 || /[\u0000-\u001f]/.test(result)) throw new ValidationError('Threat resolution is invalid'); return result; }
function token(value, field) { const result = String(value ?? '').trim().toLowerCase(); if (!/^[a-z0-9_.:-]{1,100}$/.test(result)) throw new ValidationError(`Threat ${field} is invalid`); return result; }
function position(value) { if (!value || ![value.x, value.y, value.z].every(item => Number.isFinite(Number(item)))) throw new ValidationError('Threat position requires finite x, y, z'); return { x: Number(value.x), y: Number(value.y), z: Number(value.z) }; }
function nonNegative(value, field) { const number = Number(value); if (!Number.isFinite(number) || number < 0) throw new ValidationError(`Threat ${field} must be non-negative`); return number; }
function integer(value, field) { const number = nonNegative(value, field); if (!Number.isInteger(number)) throw new ValidationError(`Threat ${field} must be an integer`); return number; }
function bounded(value, minimum, maximum, field) { const number = Number(value); if (!Number.isFinite(number) || number < minimum || number > maximum) throw new ValidationError(`Threat ${field} must be between ${minimum} and ${maximum}`); return number; }
function ratio(value, field) { return bounded(value, 0, 1, field); }
function round(value) { return Math.round(value * 1000) / 1000; }
