import { randomUUID } from 'node:crypto';
import { ConflictError, NotFoundError, ValidationError } from '../core/errors.js';

export function createLogisticsService({ repositories, hive, events }) {
  if (!repositories?.storages || !repositories?.reservations || !repositories?.transfers || !hive) throw new ValidationError('Logistics repositories and HiveMind are required');
  let mutationQueue = Promise.resolve();
  const mutate = operation => { const result = mutationQueue.then(operation); mutationQueue = result.then(() => undefined, () => undefined); return result; };
  const listStorages = async query => (await repositories.storages.list()).filter(storage => matchesScope(storage, query));
  const registerNearest = async ({ runtime, name, maxDistance }) => {
    validateRuntime(runtime); const label = validateName(name); const observation = await runtime.adapter.findNearestStorage({ maxDistance }); const scope = runtimeScope(runtime); const storages = await repositories.storages.list(); const samePosition = storages.find(storage => storage.worldKey === scope.worldKey && storage.dimension === scope.dimension && positionKey(storage.position) === positionKey(observation.position)); const sameName = storages.find(storage => storage.worldKey === scope.worldKey && storage.dimension === scope.dimension && storage.name.toLowerCase() === label.toLowerCase() && storage.id !== samePosition?.id); if (sameName) throw new ConflictError(`Storage name '${label}' is already used in this world`);
    const now = new Date().toISOString(); const value = { ...scope, name: label, kind: observation.kind, position: observation.position, inventory: observation.inventory, capacitySlots: observation.capacitySlots, occupiedSlots: observation.occupiedSlots, status: 'ACTIVE', sourceBotId: runtime.bot.id, observedAt: now, updatedAt: now };
    const storage = samePosition ? await repositories.storages.update(samePosition.id, { ...value, id: samePosition.id, createdAt: samePosition.createdAt, version: (samePosition.version ?? 1) + 1 }) : await repositories.storages.create({ ...value, id: randomUUID(), createdAt: now, version: 1 }); await events?.publish('logistics.storage.registered', storage, { source: 'logistics' }); return storage;
  };
  const sync = async ({ runtime, storageId }) => { validateRuntime(runtime); const storage = await scopedStorage(repositories.storages, storageId, runtime); const observation = await runtime.adapter.inspectStorage({ position: storage.position }); const updated = await repositories.storages.update(storage.id, { inventory: observation.inventory, capacitySlots: observation.capacitySlots, occupiedSlots: observation.occupiedSlots, observedAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: (storage.version ?? 1) + 1 }); await events?.publish('logistics.storage.synced', updated, { source: 'logistics' }); return updated; };
  const reserve = input => mutate(async () => {
    validateRuntime(input.runtime); const item = validateItem(input.item); const count = validateCount(input.count); const scope = runtimeScope(input.runtime); const active = await activeReservations(repositories.reservations); const storages = (await listStorages(scope)).filter(storage => storage.status === 'ACTIVE' && (!input.storageName || storage.name.toLowerCase() === String(input.storageName).toLowerCase())).sort((left, right) => distance(input.runtime.adapter.snapshot().position, left.position) - distance(input.runtime.adapter.snapshot().position, right.position)); if (!storages.length) throw new NotFoundError('Storage', input.storageName ?? 'in current world');
    const allocations = []; let remaining = count;
    for (const storage of storages) { const observation = await input.runtime.adapter.inspectStorage({ position: storage.position }); const fresh = await updateStorage(repositories.storages, storage, observation); const held = active.flatMap(reservation => reservation.allocations).filter(allocation => allocation.storageId === fresh.id && allocation.item === item).reduce((sum, allocation) => sum + allocation.count, 0); const available = Math.max(0, itemCount(fresh.inventory, item) - held); const allocated = Math.min(remaining, available); if (allocated) allocations.push({ storageId: fresh.id, storageName: fresh.name, item, count: allocated }); remaining -= allocated; if (!remaining) break; }
    if (remaining) throw new ConflictError(`Logistics stock cannot reserve ${count} '${item}'; ${count - remaining} available after active reservations`, { item, requested: count, available: count - remaining });
    const ttl = Number(input.ttlMs); if (!Number.isInteger(ttl) || ttl < 5_000 || ttl > 300_000) throw new ValidationError('Logistics reservation ttlMs must be between 5000 and 300000'); const now = new Date().toISOString(); const reservation = await repositories.reservations.create({ id: randomUUID(), requesterBotId: input.runtime.bot.id, ...scope, item, count, allocations, status: 'ACTIVE', expiresAt: new Date(Date.now() + ttl).toISOString(), createdAt: now, updatedAt: now }); await events?.publish('logistics.stock.reserved', reservation, { source: 'logistics' }); return reservation;
  });
  const release = input => mutate(async () => { const reservation = await repositories.reservations.find(input.reservationId); if (reservation.requesterBotId !== input.requesterBotId) throw new ConflictError(`Reservation '${reservation.id}' belongs to another requester`); if (reservation.status !== 'ACTIVE') throw new ConflictError(`Reservation '${reservation.id}' is ${reservation.status}`); const updated = await repositories.reservations.update(reservation.id, { status: 'RELEASED', releasedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); await events?.publish('logistics.stock.released', updated, { source: 'logistics' }); return updated; });
  const store = async ({ runtime, storageName, item, count }) => { validateRuntime(runtime); const storage = await chooseStorage(repositories.storages, runtime, storageName, false, item); return withStorageLock(hive, storage, runtime.bot.id, async () => { const transfer = await runtime.adapter.depositStorage({ position: storage.position, item: validateItem(item), count: validateCount(count) }); const updated = await updateStorage(repositories.storages, storage, transfer.storage); const record = await recordTransfer(repositories.transfers, events, { direction: 'DEPOSIT', runtime, storage: updated, item, count: transfer.transferred, verification: transfer.verification, reservationId: null }); return { storage: updated, transfer: record }; }); };
  const retrieve = async ({ runtime, storageName, item, count }) => {
    validateRuntime(runtime); const reservation = await reserve({ runtime, storageName, item, count, ttlMs: 60_000 }); const completed = [];
    try {
      for (const allocation of reservation.allocations) { const storage = await repositories.storages.find(allocation.storageId); const result = await withStorageLock(hive, storage, runtime.bot.id, async () => { const transfer = await runtime.adapter.withdrawStorage({ position: storage.position, item: allocation.item, count: allocation.count }); const updated = await updateStorage(repositories.storages, storage, transfer.storage); const record = await recordTransfer(repositories.transfers, events, { direction: 'WITHDRAW', runtime, storage: updated, item: allocation.item, count: transfer.transferred, verification: transfer.verification, reservationId: reservation.id }); return { storage: updated, transfer: record }; }); completed.push(result); }
      const updatedReservation = await repositories.reservations.update(reservation.id, { status: 'COMPLETED', completedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); return { reservation: updatedReservation, transfers: completed };
    } catch (error) { await repositories.reservations.update(reservation.id, { status: completed.length ? 'PARTIAL' : 'FAILED', completedAllocations: completed.length, error: error.message, updatedAt: new Date().toISOString() }); throw error; }
  };
  const stock = async query => { const storages = await listStorages(query); const active = await activeReservations(repositories.reservations); return storages.map(storage => ({ ...storage, availableInventory: storage.inventory.map(entry => ({ ...entry, reserved: active.flatMap(reservation => reservation.allocations).filter(allocation => allocation.storageId === storage.id && allocation.item === entry.name).reduce((sum, allocation) => sum + allocation.count, 0), available: Math.max(0, entry.count - active.flatMap(reservation => reservation.allocations).filter(allocation => allocation.storageId === storage.id && allocation.item === entry.name).reduce((sum, allocation) => sum + allocation.count, 0)) })) })); };
  const status = async () => { const storages = await repositories.storages.list(); const reservations = await activeReservations(repositories.reservations); const transfers = await repositories.transfers.list(); return { status: 'HEALTHY', storages: storages.length, activeStorages: storages.filter(storage => storage.status === 'ACTIVE').length, activeReservations: reservations.length, transfers: transfers.length, stockItems: storages.reduce((sum, storage) => sum + storage.inventory.reduce((total, item) => total + item.count, 0), 0) }; };
  return Object.freeze({ registerNearest, sync, reserve, release, store, retrieve, stock, status, storages: listStorages, reservations: () => repositories.reservations.list(), transfers: () => repositories.transfers.list() });
}

async function activeReservations(repository) { const records = await repository.list(); const active = []; for (const record of records) { if (record.status !== 'ACTIVE') continue; if (Date.parse(record.expiresAt) <= Date.now()) await repository.update(record.id, { status: 'EXPIRED', updatedAt: new Date().toISOString() }); else active.push(record); } return active; }
async function chooseStorage(repository, runtime, name, needsItem, item) { const scope = runtimeScope(runtime); const candidates = (await repository.list()).filter(storage => matchesScope(storage, scope) && storage.status === 'ACTIVE' && (!name || storage.name.toLowerCase() === String(name).toLowerCase()) && (!needsItem || itemCount(storage.inventory, item) > 0)).sort((left, right) => distance(runtime.adapter.snapshot().position, left.position) - distance(runtime.adapter.snapshot().position, right.position)); if (!candidates.length) throw new NotFoundError('Storage', name ?? 'in current world'); return candidates[0]; }
async function scopedStorage(repository, id, runtime) { const storage = await repository.find(id); if (!matchesScope(storage, runtimeScope(runtime))) throw new ConflictError(`Storage '${id}' belongs to another server or dimension`); return storage; }
async function updateStorage(repository, storage, observation) { return repository.update(storage.id, { inventory: observation.inventory, capacitySlots: observation.capacitySlots, occupiedSlots: observation.occupiedSlots, observedAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: (storage.version ?? 1) + 1 }); }
async function recordTransfer(repository, events, input) { const record = await repository.create({ id: randomUUID(), direction: input.direction, botId: input.runtime.bot.id, storageId: input.storage.id, storageName: input.storage.name, item: validateItem(input.item), count: validateCount(input.count), verification: input.verification, reservationId: input.reservationId, status: 'VERIFIED', createdAt: new Date().toISOString() }); await events?.publish('logistics.transfer.verified', record, { source: 'logistics' }); return record; }
async function withStorageLock(hive, storage, botId, operation) { const owner = `logistics:${botId}:${randomUUID()}`; const lock = await hive.acquireLock({ key: `storage:${storage.id}`, owner, ttlMs: 120_000 }); if (!lock) throw new ConflictError(`Storage '${storage.name}' is busy with another logistics transaction`); try { return await operation(); } finally { await hive.releaseLock(`storage:${storage.id}`, owner); } }
function runtimeScope(runtime) { const snapshot = runtime.adapter.snapshot(); return { worldKey: `${String(runtime.options?.host ?? 'localhost').toLowerCase()}:${Number(runtime.options?.port ?? 25565)}`, dimension: String(snapshot.dimension ?? 'overworld') }; }
function matchesScope(storage, query) { return (!query?.worldKey || storage.worldKey === query.worldKey) && (!query?.dimension || storage.dimension === query.dimension); }
function validateRuntime(runtime) { if (!runtime?.bot?.id || !runtime.adapter) throw new ValidationError('Logistics operation requires a bot runtime'); }
function validateName(value) { const name = String(value ?? '').trim(); if (!/^[A-Za-z0-9_. -]{2,80}$/.test(name)) throw new ValidationError('Storage name must contain 2-80 safe characters'); return name; }
function validateItem(value) { const item = String(value ?? '').toLowerCase(); if (!/^[a-z0-9_]{1,80}$/.test(item)) throw new ValidationError('Logistics item must be a Minecraft registry name'); return item; }
function validateCount(value) { const count = Number(value); if (!Number.isInteger(count) || count < 1 || count > 2304) throw new ValidationError('Logistics count must be an integer between 1 and 2304'); return count; }
function itemCount(inventory, name) { return inventory.filter(item => item.name === name).reduce((sum, item) => sum + item.count, 0); }
function positionKey(position) { return `${position.x}:${position.y}:${position.z}`; }
function distance(left, right) { if (!left || !right) return Number.POSITIVE_INFINITY; return Math.hypot(left.x - right.x, left.y - right.y, left.z - right.z); }
