import { randomUUID } from 'node:crypto';
import { ConflictError, NotFoundError, ValidationError } from '../core/errors.js';

const HOLDING_STATUSES = new Set(['ACTIVE', 'IN_PROGRESS', 'RECOVERY_REQUIRED']);
const TRANSFER_TERMINAL_STATUSES = new Set(['COMPLETED', 'FAILED', 'RECOVERED', 'PERMANENT_LOSS']);

export function createLogisticsService({ repositories, hive, events }) {
  if (!repositories?.storages || !repositories?.reservations || !repositories?.transfers || !hive) throw new ValidationError('Logistics repositories and HiveMind are required');
  let mutationQueue = Promise.resolve();
  const mutate = operation => { const result = mutationQueue.then(operation); mutationQueue = result.then(() => undefined, () => undefined); return result; };
  const listStorages = async query => (await repositories.storages.list()).filter(storage => matchesScope(storage, query));

  const registerNearest = async input => {
    validateRuntime(input.runtime); const label = validateName(input.name); const normalized = validateObservation(await input.runtime.adapter.findNearestStorage({ maxDistance: input.maxDistance }), true); const scope = runtimeScope(input.runtime);
    return mutate(async () => { const storages = await repositories.storages.list(); const samePosition = storages.find(storage => storage.worldKey === scope.worldKey && storage.dimension === scope.dimension && positionKey(storage.position) === positionKey(normalized.position)); if (samePosition) throw new ConflictError(`Storage at ${positionKey(normalized.position)} is already registered as '${samePosition.name}'. Rename it from the dashboard instead`, { storageId: samePosition.id, storageName: samePosition.name, position: normalized.position }); const sameName = storages.find(storage => storage.worldKey === scope.worldKey && storage.dimension === scope.dimension && storage.name.toLowerCase() === label.toLowerCase()); if (sameName) throw new ConflictError(`Storage name '${label}' is already used in this world`); const now = new Date().toISOString(); const storage = await repositories.storages.create({ ...scope, name: label, kind: normalized.kind, position: normalized.position, inventory: normalized.inventory, capacitySlots: normalized.capacitySlots, occupiedSlots: normalized.occupiedSlots, status: 'ACTIVE', sourceBotId: input.runtime.bot.id, observedAt: now, updatedAt: now, id: randomUUID(), createdAt: now, version: 1 }); await events?.publish('logistics.storage.registered', storage, eventOptions(storage.id)); return storage; });
  };

  const renameStorage = input => mutate(async () => { const storageId = validateStorageId(input.storageId); const name = validateName(input.name); const storage = await repositories.storages.find(storageId); const duplicate = (await repositories.storages.list()).find(candidate => candidate.id !== storage.id && candidate.worldKey === storage.worldKey && candidate.dimension === storage.dimension && candidate.name.toLowerCase() === name.toLowerCase()); if (duplicate) throw new ConflictError(`Storage name '${name}' is already used in this world`); if (storage.name === name) return storage; const updated = await repositories.storages.update(storage.id, { name, updatedAt: new Date().toISOString(), version: (storage.version ?? 1) + 1 }); await events?.publish('logistics.storage.renamed', { ...updated, previousName: storage.name }, eventOptions(storage.id)); return updated; });

  const sync = async ({ runtime, storageId }) => { validateRuntime(runtime); const storage = await scopedStorage(repositories.storages, storageId, runtime); const observation = await inspectRegisteredStorage(repositories, events, runtime, storage); if (!observation) throw new NotFoundError('Storage', storage.name); const updated = await updateStorage(repositories.storages, storage, observation); await events?.publish('logistics.storage.synced', updated, eventOptions()); if (updated.occupiedSlots >= updated.capacitySlots) await events?.publish('logistics.storage.full', updated, eventOptions()); return updated; };

  const reserve = input => mutate(async () => {
    validateRuntime(input.runtime); const item = validateItem(input.item); const count = validateCount(input.count); const scope = runtimeScope(input.runtime); const active = await activeReservations(repositories.reservations, events); const ledger = reservationLedger(active); const origin = input.runtime.adapter.snapshot().position; const storages = (await listStorages(scope)).filter(storage => storage.status === 'ACTIVE' && (!input.storageName || storage.name.toLowerCase() === String(input.storageName).toLowerCase())).sort((left, right) => distance(origin, left.position) - distance(origin, right.position)); if (!storages.length) throw new NotFoundError('Storage', input.storageName ?? 'in current world');
    const allocations = []; let remaining = count;
    for (const storage of storages) { const observation = await inspectRegisteredStorage(repositories, events, input.runtime, storage); if (!observation) continue; const fresh = await updateStorage(repositories.storages, storage, observation); const held = ledger.get(allocationKey(fresh.id, item)) ?? 0; const allocated = Math.min(remaining, Math.max(0, itemCount(fresh.inventory, item) - held)); if (allocated) allocations.push({ storageId: fresh.id, storageName: fresh.name, item, count: allocated }); remaining -= allocated; if (!remaining) break; }
    if (remaining) throw new ConflictError(`Logistics stock cannot reserve ${count} '${item}'; ${count - remaining} available after active reservations`, { item, requested: count, available: count - remaining });
    const ttl = validateTtl(input.ttlMs); const now = new Date().toISOString(); const reservation = await repositories.reservations.create({ id: randomUUID(), requesterBotId: input.runtime.bot.id, ...scope, item, count, allocations, status: 'ACTIVE', expiresAt: new Date(Date.now() + ttl).toISOString(), lifecycle: [lifecycleEntry('ACTIVE', now)], createdAt: now, updatedAt: now }); await events?.publish('logistics.reservation.created', reservation, eventOptions(reservation.id)); return reservation;
  });

  const release = input => mutate(async () => { const reservation = await repositories.reservations.find(input.reservationId); if (reservation.requesterBotId !== input.requesterBotId) throw new ConflictError(`Reservation '${reservation.id}' belongs to another requester`); if (!['ACTIVE', 'RECOVERY_REQUIRED'].includes(reservation.status)) throw new ConflictError(`Reservation '${reservation.id}' is ${reservation.status}`); return transitionReservation(repositories.reservations, events, reservation, 'RELEASED', { releasedAt: new Date().toISOString() }); });

  const store = async ({ runtime, storageName, item, count }) => {
    validateRuntime(runtime); const validItem = validateItem(item); const requested = validateCount(count); const storage = await chooseStorage(repositories.storages, runtime, storageName, false, validItem); if (!await inspectRegisteredStorage(repositories, events, runtime, storage)) throw new NotFoundError('Storage', storage.name); const transfer = await createTransfer(repositories.transfers, events, { direction: 'DEPOSIT', runtime, storage, item: validItem, count: requested, reservationId: null });
    try { const result = await executeTransfer({ repositories, hive, events, transfer, storage, runtime, actionState: 'DEPOSITING', action: () => runtime.adapter.depositStorage({ position: storage.position, item: validItem, count: requested }), direction: 'DEPOSIT', item: validItem, count: requested }); return { storage: result.storage, transfer: result.transfer }; } catch (error) { await failTransfer(repositories.transfers, events, transfer.id, error); throw error; }
  };

  const retrieve = async ({ runtime, storageName, item, count }) => {
    validateRuntime(runtime); const reservation = await reserve({ runtime, storageName, item, count, ttlMs: 60_000 }); const running = await transitionReservation(repositories.reservations, events, reservation, 'IN_PROGRESS', { startedAt: new Date().toISOString() }); const completed = [];
    try {
      for (const allocation of running.allocations) { const storage = await repositories.storages.find(allocation.storageId); if (!await inspectRegisteredStorage(repositories, events, runtime, storage)) throw new NotFoundError('Storage', storage.name); const transfer = await createTransfer(repositories.transfers, events, { direction: 'WITHDRAW', runtime, storage, item: allocation.item, count: allocation.count, reservationId: running.id }); try { completed.push(await executeTransfer({ repositories, hive, events, transfer, storage, runtime, actionState: 'WITHDRAWING', action: () => runtime.adapter.withdrawStorage({ position: storage.position, item: allocation.item, count: allocation.count }), direction: 'WITHDRAW', item: allocation.item, count: allocation.count })); } catch (error) { await failTransfer(repositories.transfers, events, transfer.id, error); throw error; } }
      const updated = await transitionReservation(repositories.reservations, events, running, 'COMPLETED', { completedAt: new Date().toISOString() }); return { reservation: updated, transfers: completed };
    } catch (error) { await transitionReservation(repositories.reservations, events, running, completed.length ? 'PARTIAL' : 'FAILED', { completedAllocations: completed.length, error: errorMessage(error) }); throw error; }
  };

  const stock = async query => { const storages = await listStorages(query); const ledger = reservationLedger(await activeReservations(repositories.reservations, events)); return storages.map(storage => ({ ...storage, availableInventory: storage.inventory.map(entry => { const reserved = ledger.get(allocationKey(storage.id, entry.name)) ?? 0; return { ...entry, reserved, available: Math.max(0, entry.count - reserved) }; }) })); };
  const reservations = async () => { await activeReservations(repositories.reservations, events); return repositories.reservations.list(); };
  const locks = async () => (await hive.locks()).filter(lock => lock.key.startsWith('storage:'));
  const timeline = async input => buildTimeline(await repositories.reservations.list(), await repositories.transfers.list(), validateTimelineLimit(input.limit));
  const deathContext = async input => { const botId = validateBotId(input.botId); const transfers = (await repositories.transfers.list()).filter(record => record.botId === botId && !TRANSFER_TERMINAL_STATUSES.has(record.status)); const reservations = (await repositories.reservations.list()).filter(record => record.requesterBotId === botId && HOLDING_STATUSES.has(record.status)); return { relatedTransferId: transfers.at(-1)?.id ?? null, transferIds: transfers.map(record => record.id), reservationIds: reservations.map(record => record.id), cargo: aggregateItems(transfers.map(record => ({ name: record.item, count: record.requestedCount }))) }; };
  const markDeathRecovery = input => mutate(async () => { const context = await deathContext(input); const now = new Date().toISOString(); for (const id of context.transferIds) { const current = await repositories.transfers.find(id); await repositories.transfers.update(id, { status: 'RECOVERY_REQUIRED', recoveryManifestId: input.manifestId, lifecycle: [...(current.lifecycle ?? []), lifecycleEntry('RECOVERY_REQUIRED', now)], updatedAt: now }); } for (const id of context.reservationIds) { const current = await repositories.reservations.find(id); if (current.status !== 'RECOVERY_REQUIRED') await transitionReservation(repositories.reservations, events, current, 'RECOVERY_REQUIRED', { recoveryManifestId: input.manifestId, recoveryReason: `Bot '${input.botId}' died while carrying logistics cargo` }); } await events?.publish('logistics.recovery.transfer.protected', { botId: input.botId, manifestId: input.manifestId, ...context }, eventOptions(input.manifestId)); return context; });
  const reconcileDeathRecovery = input => mutate(async () => { const status = input.status === 'RECOVERED' ? 'RECOVERED' : 'PERMANENT_LOSS'; const now = new Date().toISOString(); const transferRecords = (await repositories.transfers.list()).filter(record => record.recoveryManifestId === input.manifestId); for (const record of transferRecords) await repositories.transfers.update(record.id, { status, recoveryBotId: input.recoveryBotId ?? null, recoveredItems: structuredClone(input.recoveredItems ?? []), lostItems: structuredClone(input.lostItems ?? []), lifecycle: [...(record.lifecycle ?? []), lifecycleEntry(status, now)], updatedAt: now }); const reservationRecords = (await repositories.reservations.list()).filter(record => record.recoveryManifestId === input.manifestId && record.status === 'RECOVERY_REQUIRED'); for (const record of reservationRecords) await transitionReservation(repositories.reservations, events, record, status, { recoveryBotId: input.recoveryBotId ?? null, recoveredItems: structuredClone(input.recoveredItems ?? []), lostItems: structuredClone(input.lostItems ?? []) }); const result = { manifestId: input.manifestId, status, transfers: transferRecords.length, reservations: reservationRecords.length }; await events?.publish('logistics.recovery.reconciled', result, eventOptions(input.manifestId)); return result; });
  const status = async () => { const storages = await repositories.storages.list(); const active = await activeReservations(repositories.reservations, events); const reservationRecords = await repositories.reservations.list(); const transfers = await repositories.transfers.list(); const activeLocks = await locks(); const recoveryRequired = reservationRecords.filter(record => record.status === 'RECOVERY_REQUIRED').length; const inFlightTransfers = transfers.filter(record => !TRANSFER_TERMINAL_STATUSES.has(record.status)).length; return { status: recoveryRequired || inFlightTransfers ? 'DEGRADED' : 'HEALTHY', storages: storages.length, activeStorages: storages.filter(storage => storage.status === 'ACTIVE').length, activeReservations: active.length, recoveryRequired, transfers: transfers.length, completedTransfers: transfers.filter(record => record.status === 'COMPLETED').length, failedTransfers: transfers.filter(record => record.status === 'FAILED').length, inFlightTransfers, activeLocks: activeLocks.length, stockItems: storages.reduce((sum, storage) => sum + storage.inventory.reduce((total, entry) => total + entry.count, 0), 0) }; };
  return Object.freeze({ registerNearest, renameStorage, sync, reserve, release, store, retrieve, stock, status, storages: listStorages, reservations, transfers: () => repositories.transfers.list(), timeline, locks, deathContext, markDeathRecovery, reconcileDeathRecovery });
}

async function executeTransfer(input) {
  const result = await withStorageLock(input.hive, input.events, input.storage, input.runtime.bot.id, async () => { await transitionTransfer(input.repositories.transfers, input.events, input.transfer.id, 'LOCK_ACQUIRED', {}); await transitionTransfer(input.repositories.transfers, input.events, input.transfer.id, input.actionState, {}); const operation = await input.action(); await transitionTransfer(input.repositories.transfers, input.events, input.transfer.id, 'VERIFYING', {}); validateTransferResult(operation, input.direction, input.item, input.count); return { operation, storage: await updateStorage(input.repositories.storages, input.storage, operation.storage) }; });
  const transfer = await transitionTransfer(input.repositories.transfers, input.events, input.transfer.id, 'COMPLETED', { transferredCount: input.count, verification: result.operation.verification, completedAt: new Date().toISOString() }); return { storage: result.storage, transfer };
}

async function activeReservations(repository, events) { const records = await repository.list(); const active = []; for (const record of records) { if (!HOLDING_STATUSES.has(record.status)) continue; if (Date.parse(record.expiresAt) > Date.now()) { active.push(record); continue; } if (record.status === 'ACTIVE') { await transitionReservation(repository, events, record, 'EXPIRED', { expiredAt: new Date().toISOString() }); continue; } if (record.status === 'IN_PROGRESS') { active.push(await transitionReservation(repository, events, record, 'RECOVERY_REQUIRED', { recoveryReason: 'Reservation lease expired during transfer' })); continue; } active.push(record); } return active; }
async function inspectRegisteredStorage(repositories, events, runtime, storage) { let missingError; for (let attempt = 1; attempt <= 3; attempt++) { try { return await runtime.adapter.inspectStorage({ position: storage.position }); } catch (error) { if (!isMissingStorageError(error)) throw error; missingError = error; await events?.publish('logistics.storage.missing-check', { storageId: storage.id, storageName: storage.name, position: storage.position, attempt, maximumAttempts: 3 }, eventOptions(storage.id)); } } await removeMissingStorage(repositories, events, storage, missingError); return null; }
async function removeMissingStorage(repositories, events, storage, error) { const reservations = await repositories.reservations.list(); for (const reservation of reservations.filter(record => HOLDING_STATUSES.has(record.status) && record.allocations?.some(allocation => allocation.storageId === storage.id))) await transitionReservation(repositories.reservations, events, reservation, 'RECOVERY_REQUIRED', { recoveryReason: `Registered storage '${storage.name}' no longer exists`, missingStorageId: storage.id }); const removed = await repositories.storages.delete(storage.id); if (!removed) throw new NotFoundError('Storage', storage.id); await events?.publish('logistics.storage.removed', { storageId: storage.id, storageName: storage.name, position: storage.position, reason: errorMessage(error), verificationAttempts: 3 }, eventOptions(storage.id)); }
async function createTransfer(repository, events, input) { const now = new Date().toISOString(); const record = await repository.create({ id: randomUUID(), direction: input.direction, botId: input.runtime.bot.id, storageId: input.storage.id, storageName: input.storage.name, item: validateItem(input.item), requestedCount: validateCount(input.count), count: validateCount(input.count), transferredCount: 0, reservationId: input.reservationId, status: 'CREATED', lifecycle: [lifecycleEntry('CREATED', now)], failure: null, createdAt: now, updatedAt: now }); await events?.publish('logistics.transfer.created', record, eventOptions(record.id)); return record; }
async function transitionTransfer(repository, events, id, state, patch) { const current = await repository.find(id); const now = new Date().toISOString(); const updated = await repository.update(id, { ...patch, status: state, lifecycle: [...(current.lifecycle ?? []), lifecycleEntry(state, now)], updatedAt: now }); await events?.publish(`logistics.transfer.${state.toLowerCase()}`, updated, eventOptions(id)); return updated; }
async function failTransfer(repository, events, id, error) { const current = await repository.find(id); if (current.status === 'FAILED') return current; return transitionTransfer(repository, events, id, 'FAILED', { failedAt: new Date().toISOString(), failure: { code: classifyFailure(error), message: errorMessage(error) } }); }
async function transitionReservation(repository, events, reservation, state, patch) { const current = await repository.find(reservation.id); const now = new Date().toISOString(); const updated = await repository.update(current.id, { ...patch, status: state, lifecycle: [...(current.lifecycle ?? []), lifecycleEntry(state, now)], updatedAt: now }); await events?.publish(`logistics.reservation.${state.toLowerCase()}`, updated, eventOptions(current.id)); return updated; }
async function withStorageLock(hive, events, storage, botId, operation) { const owner = `logistics:${botId}:${randomUUID()}`; const key = `storage:${storage.id}`; const lock = await hive.acquireLock({ key, owner, ttlMs: 120_000 }); if (!lock) { await events?.publish('logistics.lock.timeout', { key, storageId: storage.id, botId }, eventOptions()); throw new ConflictError(`Storage '${storage.name}' is busy with another logistics transaction`); } await events?.publish('logistics.lock.acquired', lock, eventOptions()); try { return await operation(); } finally { const released = await hive.releaseLock(key, owner); if (!released) throw new ConflictError(`Storage lock '${key}' could not be released by owner '${owner}'`); await events?.publish('logistics.lock.released', { key, owner, storageId: storage.id }, eventOptions()); } }
async function chooseStorage(repository, runtime, name, needsItem, item) { const scope = runtimeScope(runtime); const candidates = (await repository.list()).filter(storage => matchesScope(storage, scope) && storage.status === 'ACTIVE' && (!name || storage.name.toLowerCase() === String(name).toLowerCase()) && (!needsItem || itemCount(storage.inventory, item) > 0)).sort((left, right) => distance(runtime.adapter.snapshot().position, left.position) - distance(runtime.adapter.snapshot().position, right.position)); if (!candidates.length) throw new NotFoundError('Storage', name ?? 'in current world'); return candidates[0]; }
async function scopedStorage(repository, id, runtime) { const storage = await repository.find(id); if (!matchesScope(storage, runtimeScope(runtime))) throw new ConflictError(`Storage '${id}' belongs to another server or dimension`); return storage; }
async function updateStorage(repository, storage, observation) { const normalized = validateObservation(observation, false); return repository.update(storage.id, { inventory: normalized.inventory, capacitySlots: normalized.capacitySlots, occupiedSlots: normalized.occupiedSlots, observedAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: (storage.version ?? 1) + 1 }); }
function reservationLedger(reservations) { const ledger = new Map(); for (const reservation of reservations) for (const allocation of reservation.allocations) { const key = allocationKey(allocation.storageId, allocation.item); ledger.set(key, (ledger.get(key) ?? 0) + allocation.count); } return ledger; }
function buildTimeline(reservations, transfers, limit) { return [...reservations.flatMap(record => (record.lifecycle ?? []).map(entry => ({ ...entry, entityType: 'reservation', entityId: record.id, item: record.item, botId: record.requesterBotId }))), ...transfers.flatMap(record => (record.lifecycle ?? []).map(entry => ({ ...entry, entityType: 'transfer', entityId: record.id, item: record.item, botId: record.botId, storageName: record.storageName, direction: record.direction })))].sort((left, right) => Date.parse(right.at) - Date.parse(left.at)).slice(0, limit); }
function classifyFailure(error) { const code = String(error?.code ?? '').toUpperCase(); const message = errorMessage(error).toLowerCase(); if (code.includes('PATH') || /path|navigation|stuck|cannot reach|unreachable/.test(message)) return 'PATHFINDER_FAILED'; if (/transferred .*expected/.test(message)) return 'PARTIAL_TRANSFER'; if (/verification|delta/.test(message)) return 'VERIFICATION_FAILED'; if (/full|no space|inventory space/.test(message)) return 'DESTINATION_FULL'; if (/source|stock|only has|not found/.test(message)) return 'SOURCE_CHANGED'; if (/lock|busy/.test(message)) return 'LOCK_TIMEOUT'; return 'OPERATION_FAILED'; }
function isMissingStorageError(error) { return error?.code === 'NOT_FOUND' && error?.details?.resource === 'Storage block'; }
function lifecycleEntry(state, at) { return { state, at }; }
function eventOptions(correlationId) { return { source: 'logistics', ...(correlationId ? { correlationId } : {}) }; }
function errorMessage(error) { return error instanceof Error ? error.message : String(error); }
function allocationKey(storageId, item) { return `${storageId}:${item}`; }
function runtimeScope(runtime) { const snapshot = runtime.adapter.snapshot(); return { worldKey: `${String(runtime.options?.host ?? 'localhost').toLowerCase()}:${Number(runtime.options?.port ?? 25565)}`, dimension: String(snapshot.dimension ?? 'overworld') }; }
function matchesScope(storage, query) { return (!query?.worldKey || storage.worldKey === query.worldKey) && (!query?.dimension || storage.dimension === query.dimension); }
function validateRuntime(runtime) { if (!runtime?.bot?.id || !runtime.adapter) throw new ValidationError('Logistics operation requires a bot runtime'); }
function validateName(value) { const name = String(value ?? '').trim(); if (!/^[A-Za-z0-9_. -]{2,80}$/.test(name)) throw new ValidationError('Storage name must contain 2-80 safe characters'); return name; }
function validateStorageId(value) { const id = String(value ?? '').trim(); if (!/^[A-Za-z0-9_.:-]{1,128}$/.test(id)) throw new ValidationError('Storage id must contain 1-128 safe characters'); return id; }
function validateBotId(value) { const id = String(value ?? '').trim(); if (!/^[A-Za-z0-9_.:-]{1,128}$/.test(id)) throw new ValidationError('Logistics bot id must contain 1-128 safe characters'); return id; }
function validateItem(value) { const item = String(value ?? '').toLowerCase(); if (!/^[a-z0-9_]{1,80}$/.test(item)) throw new ValidationError('Logistics item must be a Minecraft registry name'); return item; }
function validateCount(value) { const count = Number(value); if (!Number.isInteger(count) || count < 1 || count > 2304) throw new ValidationError('Logistics count must be an integer between 1 and 2304'); return count; }
function validateTtl(value) { const ttl = Number(value); if (!Number.isInteger(ttl) || ttl < 5_000 || ttl > 300_000) throw new ValidationError('Logistics reservation ttlMs must be between 5000 and 300000'); return ttl; }
function validateTimelineLimit(value) { const limit = Number(value); if (!Number.isInteger(limit) || limit < 1 || limit > 500) throw new ValidationError('Logistics timeline limit must be an integer between 1 and 500'); return limit; }
function validateObservation(observation, requireIdentity) { if (!observation || !Array.isArray(observation.inventory)) throw new ValidationError('Storage observation requires an inventory array'); const inventory = observation.inventory.map(entry => ({ name: validateItem(entry.name), count: nonNegativeInteger(entry.count, 'Storage item count') })).filter(entry => entry.count > 0); const capacitySlots = nonNegativeInteger(observation.capacitySlots, 'Storage capacitySlots'); const occupiedSlots = nonNegativeInteger(observation.occupiedSlots, 'Storage occupiedSlots'); if (occupiedSlots > capacitySlots) throw new ConflictError(`Storage reports ${occupiedSlots} occupied slots but capacity is ${capacitySlots}`); const position = requireIdentity && !validPosition(observation.position) ? null : observation.position; if (requireIdentity && !position) throw new ValidationError('Storage observation requires a finite position'); const kind = String(observation.kind ?? 'storage'); if (requireIdentity && !/^[A-Za-z0-9_:.-]{1,80}$/.test(kind)) throw new ValidationError('Storage observation kind is invalid'); return { kind, position: position ? { x: Number(position.x), y: Number(position.y), z: Number(position.z) } : null, inventory, capacitySlots, occupiedSlots }; }
function validateTransferResult(transfer, direction, item, expectedCount) { if (!transfer || validateItem(transfer.item) !== item) throw new ConflictError(`Logistics ${direction.toLowerCase()} returned the wrong item`); if (validateCount(transfer.transferred) !== expectedCount) throw new ConflictError(`Logistics ${direction.toLowerCase()} transferred ${transfer.transferred} '${item}', expected ${expectedCount}`); const verification = transfer.verification; if (!verification) throw new ConflictError(`Logistics ${direction.toLowerCase()} did not provide transfer verification`); const botBefore = nonNegativeInteger(verification.botBefore, 'Verification botBefore'); const botAfter = nonNegativeInteger(verification.botAfter, 'Verification botAfter'); const storageBefore = nonNegativeInteger(verification.storageBefore, 'Verification storageBefore'); const storageAfter = nonNegativeInteger(verification.storageAfter, 'Verification storageAfter'); const botDelta = direction === 'DEPOSIT' ? botBefore - botAfter : botAfter - botBefore; const storageDelta = direction === 'DEPOSIT' ? storageAfter - storageBefore : storageBefore - storageAfter; if (botDelta !== expectedCount || storageDelta !== expectedCount) throw new ConflictError(`Logistics ${direction.toLowerCase()} verification mismatch for '${item}': bot delta ${botDelta}, storage delta ${storageDelta}, expected ${expectedCount}`); }
function nonNegativeInteger(value, field) { const number = Number(value); if (!Number.isInteger(number) || number < 0) throw new ValidationError(`${field} must be a non-negative integer`); return number; }
function validPosition(position) { return position && [position.x, position.y, position.z].every(value => Number.isFinite(Number(value))); }
function itemCount(inventory, name) { return inventory.filter(item => item.name === name).reduce((sum, item) => sum + item.count, 0); }
function positionKey(position) { return `${position.x}:${position.y}:${position.z}`; }
function distance(left, right) { if (!left || !right) return Number.POSITIVE_INFINITY; return Math.hypot(left.x - right.x, left.y - right.y, left.z - right.z); }
function aggregateItems(items) { const totals = new Map(); for (const item of items) totals.set(item.name, (totals.get(item.name) ?? 0) + Number(item.count ?? 0)); return [...totals].map(([name, count]) => ({ name, count })); }
