import { NotFoundError } from '../core/errors.js';
import { NavigationError } from './navigation-error.js';
import { normalizeNavigationRequest } from './navigation-request.js';
import { createNavigationSession, sessionView, transitionNavigationSession } from './navigation-session.js';
import { navigationResult } from './navigation-result.js';

export function createNavigationService({ bots, capabilities, events, metrics }) {
  if (!bots || !capabilities || !metrics) throw new NavigationError('NAVIGATION_CONFIGURATION_INVALID', 'Navigation service requires bots, capabilities, and metrics', {});
  const active = new Map(); const controllers = new Map(); const history = [];
  const moveTo = async input => {
    const request = normalizeNavigationRequest(input); const runtime = resolveRuntime(bots, request.botId); ensureReady(runtime, request.botId); if (active.has(request.botId)) throw new NavigationError('NAVIGATION_BUSY', `Bot '${request.botId}' already has active navigation '${active.get(request.botId).id}'`, { botId: request.botId, sessionId: active.get(request.botId).id });
    const startPosition = currentPosition(runtime, request.botId); let session = createNavigationSession(request, startPosition); const controller = new AbortController(); active.set(request.botId, session); controllers.set(session.id, controller); metrics.increment('navigation.requests'); await publish(events, 'navigation.requested', session);
    const unlink = linkSignal(request.signal, controller); const timer = setTimeout(() => controller.abort(new NavigationError('NAVIGATION_TIMEOUT', `Navigation '${session.id}' exceeded ${request.policy.timeout}ms`, { botId: request.botId, sessionId: session.id, timeout: request.policy.timeout })), request.policy.timeout);
    try {
      session = transitionNavigationSession(session, 'PLANNING', {}); active.set(request.botId, session); await publish(events, 'navigation.planning', session); const position = await resolvePosition({ target: request.target, runtime, bots, capabilities, botId: request.botId, signal: controller.signal });
      session = transitionNavigationSession(session, 'MOVING', { target: { ...request.target, resolvedPosition: position } }); active.set(request.botId, session); await publish(events, 'navigation.started', session);
      await Promise.race([capabilities.execute('minecraft.navigation', { target: position, tolerance: request.policy.tolerance, mode: request.policy.mode, policy: request.policy }, { botId: request.botId, signal: controller.signal }), abortPromise(controller.signal)]);
      const finalPosition = currentPosition(runtime, request.botId); const distanceRemaining = distance3D(finalPosition, position); if (distanceRemaining > request.policy.tolerance) throw new NavigationError('ARRIVAL_NOT_VERIFIED', `Navigation '${session.id}' ended ${distanceRemaining.toFixed(2)} blocks from target`, { botId: request.botId, sessionId: session.id, target: position, finalPosition, tolerance: request.policy.tolerance, distanceRemaining });
      session = transitionNavigationSession(session, 'ARRIVED', { finalPosition, distanceRemaining }); metrics.increment('navigation.success'); metrics.gauge('navigation.duration', session.durationMs); await publish(events, 'navigation.arrived', session); return navigationResult(session);
    } catch (error) {
      const failure = normalizeFailure(error, controller.signal, session); const finalPosition = safePosition(runtime); const distanceRemaining = finalPosition && session.target.resolvedPosition ? distance3D(finalPosition, session.target.resolvedPosition) : null; session = transitionNavigationSession(session, failure.status, { finalPosition, distanceRemaining, failureCode: failure.code, failureMessage: failure.message }); await stopNavigation(capabilities, request.botId); metrics.increment(failure.metric); metrics.gauge('navigation.duration', session.durationMs); await publish(events, failure.event, session); throw new NavigationError(failure.code, failure.message, { ...navigationResult(session), cause: error?.message ?? null });
    } finally { clearTimeout(timer); unlink(); controllers.delete(session.id); if (active.get(request.botId)?.id === session.id) active.delete(request.botId); remember(history, session); }
  };
  const cancel = async input => { const session = findSession(active, input); const controller = controllers.get(session.id); if (!controller) throw new NavigationError('NAVIGATION_NOT_ACTIVE', `Navigation '${session.id}' is not active`, { sessionId: session.id }); const reason = String(input.reason ?? 'Navigation cancelled').trim() || 'Navigation cancelled'; controller.abort(new NavigationError('NAVIGATION_CANCELLED', reason, { botId: session.botId, sessionId: session.id })); await stopNavigation(capabilities, session.botId); return sessionView(active.get(session.botId) ?? session); };
  const stop = async () => Promise.all([...active.keys()].map(botId => cancel({ botId, reason: 'Application shutdown' })));
  const status = () => ({ status: 'HEALTHY', active: active.size, sessions: [...active.values()].map(sessionView), recent: history.map(sessionView) });
  const statusForBot = botId => { const session = active.get(String(botId)); return session ? sessionView(session) : null; };
  return Object.freeze({ moveTo, cancel, stop, status, statusForBot });
}

function resolveRuntime(bots, botId) { try { return bots.get(botId); } catch (error) { if (error instanceof NotFoundError) throw new NavigationError('BOT_NOT_FOUND', `Navigation bot '${botId}' was not found`, { botId }); throw error; } }
function ensureReady(runtime, botId) { const status = runtime.snapshot?.().status ?? runtime.status ?? runtime.bot?.status; if (!['READY', 'ACTIVE'].includes(status)) throw new NavigationError('BOT_NOT_READY', `Navigation bot '${botId}' is ${status ?? 'unknown'}`, { botId, status: status ?? null }); }
function currentPosition(runtime, botId) { const position = safePosition(runtime); if (!position) throw new NavigationError('TARGET_UNAVAILABLE', `Navigation bot '${botId}' has no runtime position`, { botId }); return position; }
function safePosition(runtime) { const position = runtime.adapter?.snapshot?.().position ?? runtime.snapshot?.().runtime?.position; if (!position || ![position.x, position.y, position.z].every(Number.isFinite)) return null; return { x: Number(position.x), y: Number(position.y), z: Number(position.z) }; }
async function resolvePosition({ target, runtime, bots, capabilities, botId, signal }) { if (target.type === 'POSITION') return target.position; if (target.type === 'BLOCK') return target.position; if (target.type === 'BOT') return currentPosition(resolveRuntime(bots, target.botId), target.botId); try { return await capabilities.execute('minecraft.navigation-target', { target }, { botId, signal }); } catch (error) { throw new NavigationError('TARGET_UNAVAILABLE', `Navigation target '${target.type}' is unavailable`, { target, error: error.message }); } }
async function stopNavigation(capabilities, botId) { try { await capabilities.execute('minecraft.navigation-stop', {}, { botId }); } catch (error) { throw new NavigationError('NAVIGATION_FAILED', `Unable to stop navigation for '${botId}': ${error.message}`, { botId, cause: error.message }); } }
function linkSignal(signal, controller) { if (!signal) return () => {}; const abort = () => controller.abort(signal.reason ?? new NavigationError('NAVIGATION_CANCELLED', 'Navigation cancelled', {})); if (signal.aborted) abort(); else signal.addEventListener('abort', abort, { once: true }); return () => signal.removeEventListener('abort', abort); }
function abortPromise(signal) { return new Promise((resolve, reject) => { if (signal.aborted) reject(signal.reason); else signal.addEventListener('abort', () => reject(signal.reason), { once: true }); }); }
function normalizeFailure(error, signal, session) { const reason = signal.aborted ? signal.reason : error; if (reason?.code === 'NAVIGATION_TIMEOUT') return { status: 'TIMEOUT', code: 'NAVIGATION_TIMEOUT', message: reason.message, metric: 'navigation.timeout', event: 'navigation.timeout' }; if (reason?.code === 'NAVIGATION_CANCELLED') return { status: 'CANCELLED', code: 'NAVIGATION_CANCELLED', message: reason.message, metric: 'navigation.cancelled', event: 'navigation.cancelled' }; const code = error?.code === 'ARRIVAL_NOT_VERIFIED' ? 'ARRIVAL_NOT_VERIFIED' : /path|route|unreachable/i.test(error?.message ?? '') ? 'PATH_NOT_FOUND' : 'NAVIGATION_FAILED'; return { status: 'FAILED', code, message: error?.message ?? `Navigation '${session.id}' failed`, metric: 'navigation.failed', event: 'navigation.failed' }; }
function findSession(active, input) { const sessionId = String(input?.sessionId ?? '').trim(); const botId = String(input?.botId ?? '').trim(); const session = sessionId ? [...active.values()].find(value => value.id === sessionId) : active.get(botId); if (!session) throw new NavigationError('NAVIGATION_NOT_ACTIVE', 'No active navigation matches the cancellation request', { sessionId: sessionId || null, botId: botId || null }); return session; }
function distance3D(left, right) { return Math.hypot(left.x - right.x, left.y - right.y, left.z - right.z); }
function remember(history, session) { history.push(session); if (history.length > 50) history.splice(0, history.length - 50); }
async function publish(events, type, session) { await events?.publish(type, navigationResult(session), { source: 'navigation', correlationId: session.id }); }
