import { NavigationError } from './navigation-error.js';

const MODES = Object.freeze({ FAST: { tolerance: 3, allowSprint: true, allowJump: true, allowDig: false, allowPlace: false, allowScaffolding: false, allowTower: false, allowBridge: false, timeout: 120_000 }, SAFE: { tolerance: 2, allowSprint: true, allowJump: true, allowDig: false, allowPlace: false, allowScaffolding: false, allowTower: false, allowBridge: false, timeout: 120_000 }, PRECISE: { tolerance: 1, allowSprint: false, allowJump: true, allowDig: false, allowPlace: false, allowScaffolding: false, allowTower: false, allowBridge: false, timeout: 120_000 } });

export function normalizeNavigationPolicy(input) {
  const raw = input && typeof input === 'object' && !Array.isArray(input) ? input : {}; const mode = String(raw.mode ?? 'SAFE').trim().toUpperCase(); const defaults = MODES[mode]; if (!defaults) throw new NavigationError('INVALID_POLICY', `Unsupported navigation mode '${mode}'`, { mode });
  const policy = { ...defaults, ...raw, mode, tolerance: raw.tolerance ?? defaults.tolerance, timeout: raw.timeout ?? defaults.timeout };
  if (!Number.isFinite(Number(policy.tolerance)) || Number(policy.tolerance) < 0 || Number(policy.tolerance) > 64) throw new NavigationError('INVALID_POLICY', 'Navigation tolerance must be a finite number between 0 and 64', { tolerance: policy.tolerance });
  if (!Number.isInteger(Number(policy.timeout)) || Number(policy.timeout) < 250 || Number(policy.timeout) > 600_000) throw new NavigationError('INVALID_POLICY', 'Navigation timeout must be an integer between 250 and 600000ms', { timeout: policy.timeout });
  for (const field of ['allowSprint', 'allowJump', 'allowDig', 'allowPlace', 'allowScaffolding', 'allowTower', 'allowBridge']) if (typeof policy[field] !== 'boolean') throw new NavigationError('INVALID_POLICY', `Navigation policy '${field}' must be boolean`, { field, value: policy[field] });
  const normalized = { ...policy, tolerance: Number(policy.tolerance), timeout: Number(policy.timeout), maxScaffoldBlocks: boundedInteger(policy.maxScaffoldBlocks ?? 6, 'maxScaffoldBlocks', 0, 64), maxPillarHeight: boundedInteger(policy.maxPillarHeight ?? 4, 'maxPillarHeight', 0, 16), maxBridgeLength: boundedInteger(policy.maxBridgeLength ?? 5, 'maxBridgeLength', 0, 16), maxScaffoldAttempts: boundedInteger(policy.maxScaffoldAttempts ?? 2, 'maxScaffoldAttempts', 0, 8), scaffoldPreference: normalizePreference(policy.scaffoldPreference ?? ['dirt', 'cobblestone', 'netherrack']), sampleIntervalMs: boundedInteger(policy.sampleIntervalMs ?? 250, 'sampleIntervalMs', 50, 2_000), stuckTimeoutMs: boundedInteger(policy.stuckTimeoutMs ?? 4_000, 'stuckTimeoutMs', 500, 60_000), confirmationSamples: boundedInteger(policy.confirmationSamples ?? 3, 'confirmationSamples', 1, 10), meaningfulPositionDelta: boundedNumber(policy.meaningfulPositionDelta ?? 0.25, 'meaningfulPositionDelta', 0.05, 8), meaningfulDistanceProgress: boundedNumber(policy.meaningfulDistanceProgress ?? 0.35, 'meaningfulDistanceProgress', 0.05, 8), maxRecoveryAttempts: boundedInteger(policy.maxRecoveryAttempts ?? 5, 'maxRecoveryAttempts', 0, 20), maxReplans: boundedInteger(policy.maxReplans ?? 3, 'maxReplans', 0, 10) };
  if ((!normalized.allowPlace || !normalized.allowScaffolding) && (normalized.allowTower || normalized.allowBridge)) throw new NavigationError('INVALID_POLICY', 'Towering and bridging require allowPlace and allowScaffolding', { allowPlace: normalized.allowPlace, allowScaffolding: normalized.allowScaffolding });
  return Object.freeze(normalized);
}

function boundedInteger(value, field, minimum, maximum) { const number = Number(value); if (!Number.isInteger(number) || number < minimum || number > maximum) throw new NavigationError('INVALID_POLICY', `Navigation policy '${field}' must be an integer between ${minimum} and ${maximum}`, { field, value }); return number; }
function boundedNumber(value, field, minimum, maximum) { const number = Number(value); if (!Number.isFinite(number) || number < minimum || number > maximum) throw new NavigationError('INVALID_POLICY', `Navigation policy '${field}' must be a number between ${minimum} and ${maximum}`, { field, value }); return number; }
function normalizePreference(value) { if (!Array.isArray(value) || !value.length) throw new NavigationError('INVALID_POLICY', 'scaffoldPreference must contain at least one item', { scaffoldPreference: value }); const items = value.map(item => String(item).trim().toLowerCase()); if (items.some(item => !/^[a-z0-9_]{1,128}$/.test(item)) || new Set(items).size !== items.length) throw new NavigationError('INVALID_POLICY', 'scaffoldPreference contains invalid or duplicate items', { scaffoldPreference: value }); return Object.freeze(items); }
