import { NotFoundError } from '../core/errors.js';
import { NavigationError } from './navigation-error.js';
import { normalizeNavigationRequest } from './navigation-request.js';
import { createNavigationSession, sessionView, transitionNavigationSession } from './navigation-session.js';
import { navigationResult } from './navigation-result.js';
import { createMovementMonitor } from './movement-monitor.js';
import { createMovementPolicy } from './movement-policy-factory.js';
import { createResourceReservationService } from './resource-reservation-service.js';
import { createScaffoldLedger } from './scaffold-ledger.js';
import { alternateApproaches, microEscapeAction } from './recovery-strategy.js';

export function createNavigationService({ bots, capabilities, events, metrics, reservations }) {
  if (!bots || !capabilities || !metrics) throw new NavigationError('NAVIGATION_CONFIGURATION_INVALID', 'Navigation service requires bots, capabilities, and metrics', {});
  const active = new Map(); const controllers = new Map(); const history = []; const resourceReservations = reservations ?? createResourceReservationService(); const scaffoldLedger = createScaffoldLedger();
  const moveTo = async input => {
    const request = normalizeNavigationRequest(input); const runtime = resolveRuntime(bots, request.botId); ensureReady(runtime, request.botId); if (active.has(request.botId)) throw new NavigationError('NAVIGATION_BUSY', `Bot '${request.botId}' already has active navigation '${active.get(request.botId).id}'`, { botId: request.botId, sessionId: active.get(request.botId).id });
    const startPosition = currentPosition(runtime, request.botId); let session = createNavigationSession(request, startPosition); const controller = new AbortController(); active.set(request.botId, session); controllers.set(session.id, controller); metrics.increment('navigation.requests'); await publish(events, 'navigation.requested', session);
    const unlink = linkSignal(request.signal, controller); const timer = setTimeout(() => controller.abort(new NavigationError('NAVIGATION_TIMEOUT', `Navigation '${session.id}' exceeded ${request.policy.timeout}ms`, { botId: request.botId, sessionId: session.id, timeout: request.policy.timeout })), request.policy.timeout);
    try {
      session = transitionNavigationSession(session, 'PLANNING', {}); active.set(request.botId, session); await publish(events, 'navigation.planning', session); const position = await resolvePosition({ target: request.target, runtime, bots, capabilities, botId: request.botId, signal: controller.signal });
      let lease = acquireScaffoldLease({ reservations: resourceReservations, runtime, session, policy: request.policy }); const movement = createMovementPolicy({ policy: request.policy, lease }); session = transitionNavigationSession(session, 'MOVING', { target: { ...request.target, resolvedPosition: position }, diagnostics: { ...session.diagnostics, scaffold: { leaseId: lease?.id ?? null, item: lease?.item ?? null, reserved: lease?.reserved ?? 0, used: 0 } } }); active.set(request.botId, session); await publish(events, 'navigation.started', session);
      let recoveryAttempts = 0; let replans = 0; let microAttempts = 0; let scaffoldAttempts = 0; const failedApproaches = []; const pillarFailures = new Map();
      while (true) {
        try { await executeMonitoredNavigation({ capabilities, events, runtime, session, target: position, movement, controller }); break; }
        catch (error) {
          if (controller.signal.aborted || !isRecoverableMovementFailure(error)) throw error;
          session = transitionNavigationSession(session, 'STUCK_SUSPECTED', { diagnostics: diagnosticsForRecovery(session, error) }); active.set(request.botId, session); await publish(events, error.code === 'NAVIGATION_LOOP_DETECTED' ? 'navigation.loop.detected' : 'navigation.stuck.suspected', session);
          session = transitionNavigationSession(session, 'STUCK', {}); active.set(request.botId, session); metrics.increment('navigation.stuck.count'); await publish(events, 'navigation.stuck.detected', session);
          if (recoveryAttempts >= request.policy.maxRecoveryAttempts) throw new NavigationError('RECOVERY_EXHAUSTED', `Navigation '${session.id}' exhausted its recovery budget`, { sessionId: session.id, recoveryAttempts, replans, scaffoldAttempts });
          recoveryAttempts++; session = transitionNavigationSession(session, 'RECOVERING', { diagnostics: { ...session.diagnostics, recovery: { attempt: recoveryAttempts, replans } } }); active.set(request.botId, session); metrics.increment('navigation.recovery.attempts'); await publish(events, 'navigation.recovery.started', session); await stopNavigation(capabilities, request.botId);
          if (replans < request.policy.maxReplans) { replans++; session = recoveryDiagnostics(session, { stage: 'RESTART_PATH', replans }); active.set(request.botId, session); await publish(events, 'navigation.recovery.restart-path', session); session = transitionNavigationSession(session, 'REPLANNING', {}); active.set(request.botId, session); await publish(events, 'navigation.replanning.started', session); session = transitionNavigationSession(session, 'MOVING', {}); active.set(request.botId, session); metrics.increment('navigation.replans.total'); await publish(events, 'navigation.replanning.completed', session); continue; }
          if (microAttempts < 4) { const action = microEscapeAction({ attempt: microAttempts, fingerprint: session.diagnostics.loop.fingerprint }); let escaped = false; microAttempts++; session = recoveryDiagnostics(session, { stage: 'MICRO_ESCAPE', microAttempts, action }); active.set(request.botId, session); await publish(events, 'navigation.recovery.micro-escape.started', session); try { const result = await capabilities.execute('minecraft.navigation-recovery', { action, durationMs: 350, minimumDisplacement: 0.25 }, { botId: request.botId, signal: controller.signal }); escaped = true; session = recoveryDiagnostics(session, { stage: 'MICRO_ESCAPE', microAttempts, action, displacement: result.displacement, verified: true }); active.set(request.botId, session); await publish(events, 'navigation.recovery.micro-escape.succeeded', session); } catch (microError) { if (controller.signal.aborted) throw microError; session = recoveryDiagnostics(session, { stage: 'MICRO_ESCAPE', microAttempts, action, verified: false, error: { code: microError.code ?? 'MICRO_ESCAPE_FAILED', message: microError.message } }); active.set(request.botId, session); await publish(events, 'navigation.recovery.micro-escape.failed', session); } await recoveryCooldown(100, controller.signal); if (escaped) { session = transitionNavigationSession(session, 'MOVING', {}); active.set(request.botId, session); continue; } }
          const approaches = canPillar({ session, target: position, lease, scaffoldAttempts }) ? [] : alternateApproaches({ origin: currentPosition(runtime, request.botId), target: position, failed: failedApproaches }); if (approaches.length) { const approach = approaches[0]; session = recoveryDiagnostics(session, { stage: 'ALTERNATE_APPROACH', approach, failedApproaches: [...failedApproaches] }); active.set(request.botId, session); await publish(events, 'navigation.recovery.alternate-approach.started', session); try { await capabilities.execute('minecraft.navigation', { target: approach.position, tolerance: 1, mode: request.policy.mode, policy: request.policy, movement }, { botId: request.botId, signal: controller.signal }); const actual = currentPosition(runtime, request.botId); if (distance3D(actual, approach.position) > 2) throw new NavigationError('ALTERNATE_APPROACH_NOT_VERIFIED', `Bot did not reach alternate approach '${approach.id}'`, { approach, actual }); session = recoveryDiagnostics(session, { stage: 'ALTERNATE_APPROACH', approach, verified: true, failedApproaches: [...failedApproaches] }); active.set(request.botId, session); await publish(events, 'navigation.recovery.alternate-approach.succeeded', session); session = transitionNavigationSession(session, 'MOVING', {}); active.set(request.botId, session); continue; } catch (approachError) { if (controller.signal.aborted) throw approachError; failedApproaches.push(approach.id); session = recoveryDiagnostics(session, { stage: 'ALTERNATE_APPROACH', approach, verified: false, failedApproaches: [...failedApproaches], error: { code: approachError.code ?? 'ALTERNATE_APPROACH_FAILED', message: approachError.message } }); active.set(request.botId, session); await publish(events, 'navigation.recovery.alternate-approach.failed', session); } }
          if (replans >= request.policy.maxReplans && canPillar({ session, target: position, lease, scaffoldAttempts })) {
            scaffoldAttempts++; await publish(events, 'navigation.scaffold.requested', session); let placement;
            try { placement = await capabilities.execute('minecraft.navigation-pillar', { sessionId: session.id, action: 'PILLAR_STEP', reason: 'RECOVERY', item: lease.item, target: position, pillarStartY: session.startPosition.y, maxPillarHeight: request.policy.maxPillarHeight }, { botId: request.botId, signal: controller.signal }); }
            catch (pillarError) {
              if (controller.signal.aborted) throw pillarError; if (pillarError?.details?.blockPlaced) { const committed = resourceReservations.commit({ leaseId: lease.id, count: 1 }); lease = committed; scaffoldLedger.record({ sessionId: session.id, action: 'PILLAR_STEP', reason: 'RECOVERY', item: lease.item, position: pillarError.details.position, verified: false }); }
              const fingerprint = pillarFingerprint(currentPosition(runtime, request.botId), pillarError); const failures = (pillarFailures.get(fingerprint) ?? 0) + 1; pillarFailures.set(fingerprint, failures); const disabled = failures >= 2; session = transitionNavigationSession(session, 'RECOVERING', { diagnostics: { ...session.diagnostics, scaffold: { ...session.diagnostics.scaffold, pillar: { fingerprint, region: positionRegion(currentPosition(runtime, request.botId)), code: pillarError.code ?? 'PILLAR_STEP_FAILED', failures, disabled } } } }); active.set(request.botId, session); metrics.increment('navigation.scaffold.failures'); await publish(events, 'navigation.scaffold.failed', session); if (disabled) { resourceReservations.release({ leaseId: lease.id }); lease = null; await publish(events, 'navigation.scaffold.pillar-loop-detected', session); } session = transitionNavigationSession(session, 'MOVING', {}); active.set(request.botId, session); continue;
            }
            const committed = resourceReservations.commit({ leaseId: lease.id, count: 1 }); lease = committed; const ledgerEntry = scaffoldLedger.record({ sessionId: session.id, action: 'PILLAR_STEP', reason: 'RECOVERY', item: lease.item, position: placement.position, verified: placement.verified }); session = transitionNavigationSession(session, 'RECOVERING', { diagnostics: { ...session.diagnostics, scaffold: { leaseId: lease.id, item: lease.item, reserved: lease.reserved, used: committed.used, lastPlacementId: ledgerEntry.id } } }); active.set(request.botId, session); metrics.increment('navigation.scaffold.blocksPlaced'); await publish(events, 'navigation.scaffold.placed', session);
          }
          else if (replans >= request.policy.maxReplans) throw new NavigationError('RECOVERY_EXHAUSTED', `Navigation '${session.id}' exhausted replan and scaffold budgets`, { sessionId: session.id, recoveryAttempts, replans, scaffoldAttempts });
          replans++; session = transitionNavigationSession(session, 'REPLANNING', { diagnostics: { ...session.diagnostics, recovery: { attempt: recoveryAttempts, replans } } }); active.set(request.botId, session); await publish(events, 'navigation.replanning.started', session);
          session = transitionNavigationSession(session, 'MOVING', {}); active.set(request.botId, session); metrics.increment('navigation.replans.total'); await publish(events, 'navigation.replanning.completed', session);
        }
      }
      const finalPosition = currentPosition(runtime, request.botId); const distanceRemaining = distance3D(finalPosition, position); if (distanceRemaining > request.policy.tolerance) throw new NavigationError('ARRIVAL_NOT_VERIFIED', `Navigation '${session.id}' ended ${distanceRemaining.toFixed(2)} blocks from target`, { botId: request.botId, sessionId: session.id, target: position, finalPosition, tolerance: request.policy.tolerance, distanceRemaining });
      session = transitionNavigationSession(session, 'ARRIVED', { finalPosition, distanceRemaining }); metrics.increment('navigation.success'); metrics.gauge('navigation.duration', session.durationMs); await publish(events, 'navigation.arrived', session); return navigationResult(session);
    } catch (error) {
      const failure = normalizeFailure(error, controller.signal, session); const finalPosition = safePosition(runtime); const distanceRemaining = finalPosition && session.target.resolvedPosition ? distance3D(finalPosition, session.target.resolvedPosition) : null; session = transitionNavigationSession(session, failure.status, { finalPosition, distanceRemaining, failureCode: failure.code, failureMessage: failure.message }); await stopNavigation(capabilities, request.botId); metrics.increment(failure.metric); metrics.gauge('navigation.duration', session.durationMs); await publish(events, failure.event, session); throw new NavigationError(failure.code, failure.message, { ...navigationResult(session), cause: error?.message ?? null });
    } finally { clearTimeout(timer); unlink(); const leaseId = session.diagnostics?.scaffold?.leaseId; if (leaseId) resourceReservations.release({ leaseId }); controllers.delete(session.id); if (active.get(request.botId)?.id === session.id) active.delete(request.botId); remember(history, session); }
  };
  const cancel = async input => { const session = findSession(active, input); const controller = controllers.get(session.id); if (!controller) throw new NavigationError('NAVIGATION_NOT_ACTIVE', `Navigation '${session.id}' is not active`, { sessionId: session.id }); const reason = String(input.reason ?? 'Navigation cancelled').trim() || 'Navigation cancelled'; controller.abort(new NavigationError('NAVIGATION_CANCELLED', reason, { botId: session.botId, sessionId: session.id })); await stopNavigation(capabilities, session.botId); return sessionView(active.get(session.botId) ?? session); };
  const stop = async () => Promise.all([...active.keys()].map(botId => cancel({ botId, reason: 'Application shutdown' })));
  const status = () => ({ status: 'HEALTHY', active: active.size, sessions: [...active.values()].map(sessionView), recent: history.map(sessionView) });
  const statusForBot = botId => { const session = active.get(String(botId)); return session ? sessionView(session) : null; };
  return Object.freeze({ moveTo, cancel, stop, status, statusForBot, reservations: resourceReservations, scaffoldLedger });
}

async function executeMonitoredNavigation({ capabilities, events, runtime, session, target, movement, controller }) {
  const attempt = new AbortController(); const unlink = linkSignal(controller.signal, attempt); let monitor;
  const onSnapshot = async snapshot => { await events?.publish('navigation.progress', snapshot, { source: 'navigation', correlationId: session.id }); };
  const onStuck = async error => { attempt.abort(error); await stopNavigation(capabilities, session.botId); };
  const onLoop = async error => { attempt.abort(error); await stopNavigation(capabilities, session.botId); };
  try { monitor = createMovementMonitor({ session, runtime, target, policy: session.policy, onSnapshot, onStuck, onLoop }); await Promise.race([capabilities.execute('minecraft.navigation', { target, tolerance: session.policy.tolerance, mode: session.policy.mode, policy: session.policy, movement }, { botId: session.botId, signal: attempt.signal }), abortPromise(attempt.signal)]); }
  finally { monitor?.stop(); unlink(); }
}

function acquireScaffoldLease({ reservations, runtime, session, policy }) { if (!policy.allowPlace || !policy.allowScaffolding) return null; const inventory = runtime.adapter?.snapshot?.().inventorySummary ?? []; for (const item of policy.scaffoldPreference) { const available = reservations.available({ botId: session.botId, item, inventory }); if (available > 0) return reservations.reserve({ sessionId: session.id, ownerType: 'NAVIGATION', ownerId: session.id, botId: session.botId, item, count: Math.min(policy.maxScaffoldBlocks, available), inventory, reason: 'NAVIGATION_SCAFFOLD' }); } throw new NavigationError('RESOURCE_UNAVAILABLE', `Navigation '${session.id}' has no permitted scaffold resource`, { sessionId: session.id, botId: session.botId, scaffoldPreference: policy.scaffoldPreference }); }
function diagnosticsForRecovery(session, error) { const loop = error.code === 'NAVIGATION_LOOP_DETECTED'; return { ...session.diagnostics, movement: { ...session.diagnostics.movement, lastAction: loop ? 'LOOP' : 'STUCK', noProgressMs: error.details?.noProgressMs ?? 0, repeatedActionCount: loop ? (session.diagnostics.loop.repeatCount + 1) : (error.details?.confirmations ?? 0) }, loop: loop ? { detected: true, fingerprint: (error.details?.regions ?? []).join('>'), repeatCount: session.diagnostics.loop.repeatCount + 1 } : session.diagnostics.loop }; }
function recoveryDiagnostics(session, patch) { return transitionNavigationSession(session, 'RECOVERING', { diagnostics: { ...session.diagnostics, recovery: { ...session.diagnostics.recovery, ...patch } } }); }
async function recoveryCooldown(durationMs, signal) { const started = Date.now(); while (Date.now() - started < durationMs) { if (signal.aborted) throw signal.reason; await new Promise(resolve => setTimeout(resolve, Math.min(25, durationMs - (Date.now() - started)))); } }
function isRecoverableMovementFailure(error) { return ['NAVIGATION_STUCK', 'NAVIGATION_LOOP_DETECTED'].includes(error?.code); }
function canPillar({ session, target, lease, scaffoldAttempts }) { return Boolean(lease && session.policy.allowTower && target.y > session.startPosition.y && lease.used < lease.reserved && scaffoldAttempts < session.policy.maxScaffoldAttempts); }
function pillarFingerprint(position, error) { return `${positionRegion(position)}:${String(error?.code ?? 'PILLAR_STEP_FAILED')}`; }
function positionRegion(position) { return `${Math.floor(position.x / 2)}:${Math.floor(position.y)}:${Math.floor(position.z / 2)}`; }

function resolveRuntime(bots, botId) { try { return bots.get(botId); } catch (error) { if (error instanceof NotFoundError) throw new NavigationError('BOT_NOT_FOUND', `Navigation bot '${botId}' was not found`, { botId }); throw error; } }
function ensureReady(runtime, botId) { const status = runtime.snapshot?.().status ?? runtime.status ?? runtime.bot?.status; if (!['READY', 'ACTIVE'].includes(status)) throw new NavigationError('BOT_NOT_READY', `Navigation bot '${botId}' is ${status ?? 'unknown'}`, { botId, status: status ?? null }); }
function currentPosition(runtime, botId) { const position = safePosition(runtime); if (!position) throw new NavigationError('TARGET_UNAVAILABLE', `Navigation bot '${botId}' has no runtime position`, { botId }); return position; }
function safePosition(runtime) { const position = runtime.adapter?.snapshot?.().position ?? runtime.snapshot?.().runtime?.position; if (!position || ![position.x, position.y, position.z].every(Number.isFinite)) return null; return { x: Number(position.x), y: Number(position.y), z: Number(position.z) }; }
async function resolvePosition({ target, runtime, bots, capabilities, botId, signal }) { if (target.type === 'POSITION') return target.position; if (target.type === 'BLOCK') return target.position; if (target.type === 'BOT') return currentPosition(resolveRuntime(bots, target.botId), target.botId); try { return await capabilities.execute('minecraft.navigation-target', { target }, { botId, signal }); } catch (error) { throw new NavigationError('TARGET_UNAVAILABLE', `Navigation target '${target.type}' is unavailable`, { target, error: error.message }); } }
async function stopNavigation(capabilities, botId) { try { await capabilities.execute('minecraft.navigation-stop', {}, { botId }); } catch (error) { throw new NavigationError('NAVIGATION_FAILED', `Unable to stop navigation for '${botId}': ${error.message}`, { botId, cause: error.message }); } }
function linkSignal(signal, controller) { if (!signal) return () => {}; const abort = () => controller.abort(signal.reason ?? new NavigationError('NAVIGATION_CANCELLED', 'Navigation cancelled', {})); if (signal.aborted) abort(); else signal.addEventListener('abort', abort, { once: true }); return () => signal.removeEventListener('abort', abort); }
function abortPromise(signal) { return new Promise((resolve, reject) => { if (signal.aborted) reject(signal.reason); else signal.addEventListener('abort', () => reject(signal.reason), { once: true }); }); }
function normalizeFailure(error, signal, session) { const reason = signal.aborted ? signal.reason : error; if (reason?.code === 'NAVIGATION_TIMEOUT') return { status: 'TIMEOUT', code: 'NAVIGATION_TIMEOUT', message: reason.message, metric: 'navigation.timeout', event: 'navigation.timeout' }; if (reason?.code === 'NAVIGATION_CANCELLED') return { status: 'CANCELLED', code: 'NAVIGATION_CANCELLED', message: reason.message, metric: 'navigation.cancelled', event: 'navigation.cancelled' }; const structured = String(error?.code ?? ''); if (structured && structured !== 'CONFLICT' && structured !== 'VALIDATION') return { status: 'FAILED', code: structured, message: error.message, metric: 'navigation.failed', event: 'navigation.failed' }; const code = /path|route|unreachable/i.test(error?.message ?? '') ? 'PATH_NOT_FOUND' : 'NAVIGATION_FAILED'; return { status: 'FAILED', code, message: error?.message ?? `Navigation '${session.id}' failed`, metric: 'navigation.failed', event: 'navigation.failed' }; }
function findSession(active, input) { const sessionId = String(input?.sessionId ?? '').trim(); const botId = String(input?.botId ?? '').trim(); const session = sessionId ? [...active.values()].find(value => value.id === sessionId) : active.get(botId); if (!session) throw new NavigationError('NAVIGATION_NOT_ACTIVE', 'No active navigation matches the cancellation request', { sessionId: sessionId || null, botId: botId || null }); return session; }
function distance3D(left, right) { return Math.hypot(left.x - right.x, left.y - right.y, left.z - right.z); }
function remember(history, session) { history.push(session); if (history.length > 50) history.splice(0, history.length - 50); }
async function publish(events, type, session) { await events?.publish(type, navigationResult(session), { source: 'navigation', correlationId: session.id }); }
