import { randomUUID } from 'node:crypto';
import { ValidationError } from '../core/errors.js';

const INTENTS = ['collect','craft','smelt','follow','come','move','set_home','home','farm','deforest','reforest','combat','survey','register_storage','store','retrieve','stock','remember','place','status','converse','unknown'];
const CLASSES = ['worker','miner','scout','support','logistics','combat','other'];
const DIMENSIONS = ['overworld','the_nether','the_end','other'];
const NUMERIC = ['health','food','distance','hostileCount','inventoryStacks','fleetSize','durationEstimate'];
export const TASK_SUCCESS_FEATURE_SCHEMA = Object.freeze({ version:4, numeric:NUMERIC, boolean:['night','hasTool'], categorical:{ intent:INTENTS, className:CLASSES, dimension:DIMENSIONS } });
const WIDTH = NUMERIC.length + 2 + INTENTS.length + CLASSES.length + DIMENSIONS.length;

/** Explicit-feature Node.js logistic regression. Training is always explicit. */
export function createAdaptiveModel({ outcomeRepository, modelRepository, events, minimumSamples = 20 }) {
  if (!outcomeRepository || !modelRepository) throw new ValidationError('ML outcome and model repositories are required');
  let outcomeCache = null; let modelCache = null; let active = null; let queue = Promise.resolve(); let predictionCount = 0; let totalLatency = 0;
  const outcomes = async () => outcomeCache ??= await outcomeRepository.list();
  const models = async () => modelCache ??= await modelRepository.list();
  const enqueue = operation => { const result=queue.then(operation); queue=result.then(()=>undefined,()=>undefined); return result; };
  const initialize = async () => { active=(await models()).find(item=>item.id==='task-success-logistic-v2')??null; return status(); };
  const train = async ({ epochs=250, learningRate=0.08 }={}) => enqueue(async () => {
    const records=await outcomes(); if(records.length<Math.max(4,minimumSamples)) throw new ValidationError(`Task success training requires at least ${Math.max(4,minimumSamples)} outcomes`);
    const split=records.map(record=>({record,input:vector(record),target:record.success?1:0})); let validation=split.filter(item=>stableBucket(item.record.id)===0), training=split.filter(item=>stableBucket(item.record.id)!==0); if(!validation.length){validation=split.slice(-1);training=split.slice(0,-1);}
    let weights=Array(WIDTH).fill(0),bias=0; const rate=Math.max(0.001,Math.min(0.5,Number(learningRate)||0.08));
    for(let epoch=0;epoch<Math.max(1,Math.min(2000,Number(epochs)||250));epoch++){const gradient=Array(WIDTH).fill(0);let biasGradient=0;for(const sample of training){const error=sigmoid(dot(weights,sample.input)+bias)-sample.target;for(let i=0;i<WIDTH;i++)gradient[i]+=error*sample.input[i];biasGradient+=error;}const scale=1/Math.max(1,training.length);for(let i=0;i<WIDTH;i++)weights[i]-=rate*(gradient[i]*scale+weights[i]*0.0005);bias-=rate*biasGradient*scale;}
    const metrics=evaluate(weights,bias,training,validation); const model={id:'task-success-logistic-v2',version:2,status:'PRODUCTION',modelType:'node-logistic-regression',featureSchema:TASK_SUCCESS_FEATURE_SCHEMA,weights,bias,metrics,trainedAt:new Date().toISOString()}; const previous=(await models()).find(item=>item.id===model.id); if(previous)await modelRepository.update(model.id,model);else await modelRepository.create(model); active=model;modelCache=[model,...(await models()).filter(item=>item.id!==model.id)];await events?.publish('ml.trained',{model:model.modelType,metrics},{source:'task-success-model'});return model;
  });
  const recordOutcome = input => enqueue(async () => { const value=normalize(input);const record=await outcomeRepository.create({id:randomUUID(),...value,createdAt:new Date().toISOString(),schemaVersion:2});outcomeCache=[record,...await outcomes()];await events?.publish('ml.outcome.recorded',record,{source:'task-success-model'});return record; });
  const predict = async input => { const started=performance.now();if(!input?.botId)throw new ValidationError('ML prediction requires botId');if(active===null)active=(await models()).find(item=>item.id==='task-success-logistic-v2')??false;const records=await outcomes();const intent=String(input.intent??'unknown');const evidence=records.filter(item=>item.intent===intent&&item.botId===String(input.botId));const intentEvidence=records.filter(item=>item.intent===intent);let probability,modelName;
    if(active){probability=sigmoid(dot(active.weights,vector({intent,features:normalizeFeatures(input.features??{})}))+active.bias);modelName=active.modelType;}else{const source=evidence.length?evidence:intentEvidence;probability=(source.filter(item=>item.success).length+1)/(source.length+2);modelName='empirical-beta-baseline';}
    predictionCount++;totalLatency+=performance.now()-started;const sampleCount=evidence.length||intentEvidence.length;return {prediction:round(probability),failureProbability:round(1-probability),confidence:round(sampleCount/(sampleCount+Math.max(2,minimumSamples))),modelVersion:active?'task-success-logistic-v2':'empirical-beta-v1',sampleCount,model:modelName,featureSchemaVersion:TASK_SUCCESS_FEATURE_SCHEMA.version,timestamp:new Date().toISOString()}; };
  const status = async () => { const records=await outcomes();if(active===null)active=(await models()).find(item=>item.id==='task-success-logistic-v2')??false;return {status:'HEALTHY',outcomeCount:records.length,inferenceVersion:active?'task-success-logistic-v2':'empirical-beta-v1',productionModel:active||{id:null,status:'UNTRAINED',modelType:'empirical-beta-baseline',featureSchema:TASK_SUCCESS_FEATURE_SCHEMA},trainingPolicy:'explicit-only',monitoring:{predictionCount,averagePredictionLatencyMs:predictionCount?round(totalLatency/predictionCount):0,byIntent:summarize(records,'intent'),byBot:summarize(records,'botId')}}; };
  return Object.freeze({initialize,recordOutcome,predict,status,train,models,outcomes,featureSchema:()=>TASK_SUCCESS_FEATURE_SCHEMA});
}
function normalize(input){if(typeof input.success!=='boolean')throw new ValidationError('ML outcome success must be boolean');if(!input.botId)throw new ValidationError('ML outcome requires botId');return {botId:String(input.botId),intent:String(input.intent??'unknown'),success:input.success,durationMs:Math.max(0,Number(input.durationMs)||0),features:normalizeFeatures(input.features??{}),source:String(input.source??'coordinator')};}
function normalizeFeatures(value){if(!value||typeof value!=='object'||Array.isArray(value))throw new ValidationError('ML features must be an object');return {health:ratio(value.health,20),food:ratio(value.food,20),distance:ratio(value.distance,256),hostileCount:ratio(value.hostileCount,16),inventoryStacks:ratio(value.inventoryStacks,36),fleetSize:ratio(value.fleetSize,32),durationEstimate:ratio(value.durationEstimate,300000),night:Boolean(value.night),hasTool:Boolean(value.hasTool),className:category(value.className,CLASSES,'other'),dimension:category(String(value.dimension??'overworld').replace(/^minecraft:/,''),DIMENSIONS,'other')};}
function vector(value){const f=normalizeFeatures(value.features??{}),result=[];for(const name of NUMERIC)result.push(f[name]);result.push(f.night?1:0,f.hasTool?1:0);oneHot(result,category(value.intent,INTENTS,'unknown'),INTENTS);oneHot(result,f.className,CLASSES);oneHot(result,f.dimension,DIMENSIONS);return result;}
function oneHot(target,value,labels){for(const label of labels)target.push(value===label?1:0);}
function category(value,allowed,fallback){const normalized=String(value??'').toLowerCase();return allowed.includes(normalized)?normalized:fallback;}
function ratio(value,max){const number=Number(value);return Number.isFinite(number)?Math.max(0,Math.min(1,number/max)):0;}
function sigmoid(value){return 1/(1+Math.exp(-Math.max(-30,Math.min(30,value))));}
function dot(left,right){let sum=0;for(let i=0;i<Math.min(left.length,right.length);i++)sum+=left[i]*right[i];return sum;}
function evaluate(weights,bias,training,validation){const metric=samples=>{let correct=0,loss=0,brier=0;for(const sample of samples){const p=sigmoid(dot(weights,sample.input)+bias),bounded=Math.max(1e-7,Math.min(1-1e-7,p));correct+=Number((p>=.5)===Boolean(sample.target));loss+=-(sample.target*Math.log(bounded)+(1-sample.target)*Math.log(1-bounded));brier+=(p-sample.target)**2;}return {samples:samples.length,accuracy:round(correct/Math.max(1,samples.length)),logLoss:round(loss/Math.max(1,samples.length)),brier:round(brier/Math.max(1,samples.length))};};return {train:metric(training),validation:metric(validation),holdout:true};}
function stableBucket(value){let hash=2166136261;for(const char of String(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return (hash>>>0)%5;}
function round(value){return Math.round(Number(value??0)*10000)/10000;}
function summarize(records,field){const result={};for(const item of records){const key=item[field];const value=result[key]??={samples:0,successes:0,durationMs:0};value.samples++;value.successes+=item.success?1:0;value.durationMs+=item.durationMs;}return Object.fromEntries(Object.entries(result).map(([key,value])=>[key,{samples:value.samples,successRate:round(value.successes/value.samples),averageDurationMs:Math.round(value.durationMs/value.samples)}]));}
